### ISSUE TITLE
Update all documentation for 0.4 release

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1544]
By the looks of things, there are enough major changes that there will need to be significant alterations to the docs. This should include.

# Docs issues for 0.4
- [x] Update source guide screenshots from Tails (#2010)
- [x] Update journalist guide screenshots with ones from Tails (#2011)
- [x] Update admin guide screenshots with ones from Tails (#2012)
- [x] Update "Set up the Network Firewall" Tails screenshots and put the Tails version next to them
- [x] Update "Set up the Network Firewall" section to instruct how to use the template
- [x] Update "Set up the Data Transfer Device" pages and put the Tails version next to them (in #1695)
- [x] Update "Generate the SecureDrop Submission Key" pages and put the Tails version next to them. As this is done, we can also fix #1142.
- [x] Update custom notification screenshot on the "Install SecureDrop" page (#1992)
- [x] Write docs describing EV cert procurement for HTTPS deployment (#1605)

**Comment by fowlslegs** [comment]
Definitely worth waiting until we're at a "stable" point. The UI will never be static, but after we get in all of @ninavizz's suggestions there'll be a lot less churn.

**Comment by heartsucker** [comment]
Agreed. Just putting it here so it could be added to the 0.4 project to ensure it gets done.

**Comment by fowlslegs** [comment]
I think this should also include convergence of the "latest" and "stable" versions of the documentation on our website.

**Comment by conorsch** [comment]
@fowlslegs I wouldn't converge them—"stable" still has merit as a label in that it reflects the most recently _shipped_ release, and "latest" represents whatever the head of current development includes.

**Comment by edenemmanuel** [comment]
Someone who recently set up the latest stable version of SecureDrop emailed the following comments, which I'm attaching to this issue:

1. The data transfer device pages seem to be for another version of tails. I’m running the latest 2.11. At the very least, you should put the version number next to one of the screenshots.
2. The firewall section could be a lot better.  You ship a sample configuration with a bunch of redacted fields. How about simply walking the user through how to change the template and how to load it?  For the screenshots on the pf2440, the one you recommend, it would be nice if you had that info perhaps in a table or in text or something that I don’t have to squint at a low-res jpg to try and figure out what you have. I get that firewalls are complicated, but if somebody buys straight off your list of hardware and puts the computers on a dedicated subnet inside the firewall, should be able to give me a better cookbook approach.
-----
It is debatable whether or not we want to put version numbers next to screenshots, but recent versions of Tails (as compared to the ones screencapped), use a different version of GNOME and other applications, which have UI changes, so those will need to be updated.

**Comment by redshiftzero** [comment]
Great feedback, thanks @edenemmanuel for passing those along. 

# Docs issues for 0.4
- [ ] Update source guide screenshots (from Tails)
- [ ] Update journalist guide screenshots with ones (from Tails). This would also closes #1231.
- [ ] Update admin guide screenshots with ones (from Tails)
- [ ] Update "Set up the Network Firewall" Tails screenshots and put the Tails version next to them
- [ ] Update "Set up the Network Firewall" section to instruct how to use the template
- [ ] Update "Set up the Data Transfer Device" pages and put the Tails version next to them
- [ ] Update "Generate the SecureDrop Submission Key" pages and put the Tails version next to them
- [ ] Update custom notification screenshot on the "Install SecureDrop" page

In the interest of not duplicating work, we should do the Tails-based documentation tasks described here in Tails 3.0 (see issue #1551).

**Comment by redshiftzero** [comment]
@edenemmanuel is currently testing the 0.4 docs in #1695 and #1688. If you're currently working on one of the other docs items from the checklist above, please comment!

**Comment by conorsch** [comment]
The only remaining items on the checklist are updating screenshots to use Tails 3 for the various role guides. Now that the interface is stable, and Tails 3 is released and well tested, it's a good time to get those screenshot updates in. I'll handle.

**Comment by conorsch** [comment]
All items on the checklist are now resolved. Also recently merged #2003 and #2015 with additional documentation updates related to 0.4.
