### ISSUE TITLE
Journalist API

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1761]
In order to prototype the journalist reading room application, we first need to create an API such that the SecureDrop app server can talk to clients. This API would not need to go to prod until we want to put the reading room application in beta or prod. The advantage here is that as we prototype and we decide we don't like something we can easily modify it. 

Note: The API is intended to replace only the journalist actions for now, so there is no mention of the source interface actions or admin interface actions (e.g. creating users, etc.). What follows is a sketch of a simple REST API that is able to do the main functions (downloading docs, browsing through sources, submissions, etc.). If you feel strongly that the eventual API should _not_ be something like this, please feel free to comment. 

## Versioning

The API should be versioned such that if we decide to remove or modify functionality then we can do that and support new clients while preserving backwards compatibility. 

The base URL for the initial SecureDrop API will be:

`/api/v1/`

## Content Type

```
'Accept': 'application/json',
'Content-Type': 'application/json'
```

## Authentication

`POST /api/v1/token` to get a token with the username, password, and 2FA token in the request body.

Thereafter in order to authenticate to protected endpints, send the token in HTTP header `Authorization`:

`Authorization: Token myverylongtokengoeshere`

This header will be checked with each API request to see if it is valid and not yet expired. 

# Endpoints

## Root Endpoint

Does not require authentication.

The root endpoint describes the available resources:

`GET /api/v1/`

Response 200 (application/json):

```
{
  "current_user_url": "/api/v1/user/", 
  "sources_url": "/api/v1/sources/", 
  "submissions_url": "/api/v1/submissions/"
  "token_url": "/api/v1/token/"
}
```

### GET `/sources`: get list of all sources

Requires authentication. Gives a list of all sources and data about them.

GET `/api/v1/sources/`

Response 200 (application/json):

```
{
  "sources": [
    {
      "add_star_url": "/api/v1/sources/1/add_star/", 
      "flagged": false, 
      "interaction_count": 2, 
      "journalist_designation": "uneventful vaporization", 
      "last_updated": "Tue, 30 May 2017 03:31:07 GMT", 
      "number_of_documents": 0, 
      "number_of_messages": 2, 
      "remove_star_url": "/api/v1/sources/1/remove_star/", 
      "reply_url": "/api/v1/sources/1/reply/", 
      "source_id": 1, 
      "submissions_url": "/api/v1/sources/1/submissions/", 
      "url": "/api/v1/sources/1/"
    }, 
    {
      "add_star_url": "/api/v1/sources/2/add_star/", 
      "flagged": false, 
      "interaction_count": 1, 
      "journalist_designation": "misanthropic widow", 
      "last_updated": "Tue, 30 May 2017 03:31:17 GMT", 
      "number_of_documents": 0, 
      "number_of_messages": 1, 
      "remove_star_url": "/api/v1/sources/2/remove_star/", 
      "reply_url": "/api/v1/sources/2/reply/", 
      "source_id": 2, 
      "submissions_url": "/api/v1/sources/2/submissions/", 
      "url": "/api/v1/sources/2/"
    }
  ]
}
```

### Individual Source [`/sources/<int:id>`]

Requires authentication

An object representing a single source.

Response 200 (application/json): 

```
{
  "add_star_url": "/api/v1/sources/1/add_star/", 
  "flagged": false, 
  "interaction_count": 2, 
  "journalist_designation": "uneventful vaporization", 
  "last_updated": "Tue, 30 May 2017 03:31:07 GMT", 
  "number_of_documents": 0, 
  "number_of_messages": 2, 
  "remove_star_url": "/api/v1/sources/1/remove_star/", 
  "reply_url": "/api/v1/sources/1/reply/", 
  "source_id": 1, 
  "submissions_url": "/api/v1/sources/1/submissions/", 
  "url": "/api/v1/sources/1/"
}
```

### Get all documents and messages associated with a Source [GET] 

Requires authentication.

`GET /api/v1/sources/<int:source_id>/submissions`

Response 200 (application/json):

```
{
  "submissions": [
    {
      "download_url": "/api/v1/sources/1/submissions/1/download/", 
      "filename": "1-uneventful_vaporization-msg.gpg", 
      "is_read": true, 
      "size": 592, 
      "source_url": "/api/v1/sources/1/", 
      "submission_id": 1, 
      "submission_url": "/api/v1/sources/1/submissions/1/"
    }, 
    {
      "download_url": "/api/v1/sources/1/submissions/2/download/", 
      "filename": "2-uneventful_vaporization-msg.gpg", 
      "is_read": true, 
      "size": 591, 
      "source_url": "/api/v1/sources/1/", 
      "submission_id": 2, 
      "submission_url": "/api/v1/sources/1/submissions/2/"
    }
  ]
}
```

### Get a single submission or message associated with a Source [GET]

Requires authentication.

`GET /api/v1/sources/<int:source_id>/submissions/<int:submission_id>/`

Response 200 (application/json):

```
{
  "download_url": "/api/v1/sources/1/submissions/1/download/", 
  "filename": "1-uneventful_vaporization-msg.gpg", 
  "is_read": true, 
  "size": 592, 
  "source_url": "/api/v1/sources/1/", 
  "submission_id": 1, 
  "submission_url": "/api/v1/sources/1/submissions/1/"
}
```

### Add a reply [POST]

Requires authentication.

`POST /api/v1/sources/<int:id>/`

Response 201 created (application/json):

```
{
  "message": "Your reply has been stored"
}
```

### Delete a submission [DELETE]

Requires authentication.

`DELETE /api/v1/sources/<int:source_id>/submissions/<int:submission_id>/`

Response 200:

```
{
  "message": "Submission deleted"
}
```

### Download a single submission [GET]

Requires authentication.

`GET /api/v1/sources/<int:source_id>/submissions/<int:submission_id>/download`

Response 200 has `Content-Type: application/pgp-encrypted`

### Delete a Source and all their associated submissions 

Requires authentication.

This is known as "delete collection"

`DELETE /api/v1/sources/<int:source_id>/submissions`

Response 200:

```
{
  "message": "Source and submissions deleted"
}
```

### Star a source

Requires authentication.

`POST /api/v1/sources/<int:source_id>/star/`

Response 201 created:

```
{
  "message": "Star added"
}
```

### Remove a star

Requires authentication.

`DELETE /api/v1/sources/<int:source_id>/star/`

Response 200:

```
{
  "message": "Star removed"
}
```

## Submission [`/submissions`]

Requires authentication.

Get all submissions.

`GET /api/v1/submissions/`

Response 200:

```
{
  "submissions": [
    {
      "download_url": "/api/v1/sources/1/submissions/1/download/", 
      "filename": "1-uneventful_vaporization-msg.gpg", 
      "is_read": true, 
      "size": 592, 
      "source_url": "/api/v1/sources/1/", 
      "submission_id": 1, 
      "submission_url": "/api/v1/sources/1/submissions/1/"
    }, 
    {
      "download_url": "/api/v1/sources/1/submissions/2/download/", 
      "filename": "2-uneventful_vaporization-msg.gpg", 
      "is_read": true, 
      "size": 591, 
      "source_url": "/api/v1/sources/1/", 
      "submission_id": 2, 
      "submission_url": "/api/v1/sources/1/submissions/2/"
    }, 
    {
      "download_url": "/api/v1/sources/2/submissions/3/download/", 
      "filename": "1-misanthropic_widow-msg.gpg", 
      "is_read": true, 
      "size": 589, 
      "source_url": "/api/v1/sources/2/", 
      "submission_id": 3, 
      "submission_url": "/api/v1/sources/2/submissions/3/"
    }
  ]
}
```

## User [`/user/`]

Requires authentication.

An object representing the current user.

`GET /api/v1/user/`

Response 200: 

```
{
  "user": {
    "is_admin": true, 
    "last_login": "Tue, 30 May 2017 03:30:21 GMT", 
    "username": "test"
  }
}
```

## TODOS

Other actions that journalists can do that I have not yet specified yet but should be in an eventual journalist API:

- [ ] Password and 2FA change for the current user
- [ ] Bulk downloading of submissions
- [ ] Change codename

To debate:

- [ ] Filter sources by string (this I think could potentially just be done on the client side, or we can implement it in the API, no major feelings either way)

Comment if you have major thoughts on this so far. One other thought is that we could implement a logout endpoint to blacklist tokens (if we want to enable a user to invalidate a token before it expires). 

## Implementation

I've implemented this as written in the branch `journalist-api` if you want to play around with it. Unit tests for the API are in `securedrop/tests/test_api.py`.

**Comment by dachary** [comment]
Is https://github.com/freedomofpress/securedrop/commits/journalist-api up to date ? Or are there unpushed commit somewhere ?

**Comment by redshiftzero** [comment]
Nope everything that has been implemented thus far is in that branch. But let me know if something looks like it is missing.

**Comment by dachary** [comment]
A minor question (no major thought just yet ;-) In
<pre>
GET /api/v1/sources/<int:source_id>/submissions
</pre>
what is the rationale for having `{ "submissions": [ ... ] }` instead of `[] `?

**Comment by fowlslegs** [comment]
We might not want to expose the primary key of Sources through the JI. It can indicate how many Sources have used the system or when in relation to other Sources a particular Source was created. Especially in the case an adversary regularly creates Source accounts, and then compromises a non-admin Journalist account, this has the potential to leak de-anonymizing time-related info that would otherwise not be available. This is not something I have seen brought up before, and should probably factor into our re-write of the threat model document as well.

**Comment by fowlslegs** [comment]
You might want to have a look at http://seriot.ch/parsing_json.php and specifically (note: Trusty is actually on an earlier point release of Python 2.7) http://seriot.ch/json/parsing.html#43.

**Comment by fowlslegs** [comment]
Maybe it's better as a list. Some things to consider (reiterating some already-mentioned ones):

1. Schema/ input validation. It looks like we don't have any plans to this regard yet. Especially with Python's unfortunate decision to use duck typing, we have to be extra careful with input processing, even if there are a limited number of datatypes supported by JSON. There's only a draft spec for [JSON schema](http://json-schema.org/documentation.html), otherwise I might suggest we consider it.
2. Compromising a Journalists account should not be outside of our threat model. We should at least do everything we can to protect deleted/ inactive sources still in the system, even if there's little we can do to protect the data and metadata of active and especially new sources. This has to factor into the API architecture; non-admin journos need to be on a need-to-know basis regarding all information in the system.
3. JSON parsing is problematic (see http://seriot.ch/parsing_json.php and http://seriot.ch/json/parsing.html#43).
4. How can we update the API over time allowing for slight skew in upgrade status of clients and the server?
5. Consider protocol buffers or another mature, verified, schematic serialization solution. In addition to providing a solution to 1, 3, and 4, protocol buffers also conserve bandwidth (especially important to UX given we're using ATHS--a 15-hop round trip).

Most of these points are fine to ignore for the purpose of prototyping, but should be addressed by a production-ready system.

**Comment by redshiftzero** [comment]
Quick note: since some news organizations are interested to use an API on the journalist interface for developing custom software for their organization's SecureDrop, it should stay JSON for simplicity and should be well-documented for other developers (thought: news organizations with the engineering time and interest to develop software for SecureDrop internally might be interested in upstreaming some of their improvements such that the wider SecureDrop ecosystem can benefit).

**Comment by eloquence** [comment]
@redshiftzero and I would like to consider work on this for the next two week sprint (kick-off 4/4) but it would be good to first develop more  consensus on what is achievable/desirable
- within a couple of weeks
- by the 0.7 release (due May 8)
- after the 0.7 release.

My take: 

It sounds  like we have a solid prototype in the `journalist-api` branch that will require extensive pen-testing and hardening to be production-ready. If we're comfortable that the core features of the API may expand but are unlikely to change dramatically, breaking this pen-testing and hardening down into tasks we can handle for the next sprint seems like the most logical near-term step to me.

As for shipping this with 0.7, I'm curious how folks feel about an off-by-default approach, provided that we do feel the code is production ready at release time. This would speak to Jen's use case  above:

>some news organizations are interested to use an API on the journalist interface for developing custom software for their organization's SecureDrop

.. and to near-term work with selected news organizations on testing the alpha releases of the Qubes OS SD Workstation that will consume this API.

"Off-by-default" would not mean "this is not production-ready". The only reason to not enable it for everyone would be to minimize the attack surface for users who don't actually intend to use it yet. Thoughts?

**Comment by redshiftzero** [comment]
I think some reasonable goals for the next sprint might be:

- [ ] Rebase branch on current `develop` (this was written pre-Blueprint refactor and a bunch of other major changes to the app code)
- [ ] Critically examine the unit test suite, are at least all the base cases covered?
- [ ] (Stretch) Security evaluation of the API, file followup tickets (i.e. running through [this](https://www.owasp.org/index.php/REST_Security_Cheat_Sheet) is a good start)

In terms of having this feature be off by default. If we did that, I'm imagining we'd do something like this:

1. Manage config option for enabling the API in `site-specific`
2. Administrators would need to run `./securedrop-admin sdconfig` and `./securedrop-admin install` to turn this option on

I think this is actually a worse workflow from the user perspective than simply adding an API via the `securedrop-app-code` deb package, which requires no admin involvement. So I suggest to make this decision we should: 

1. Evaluate the security of the API (cc @emkll 😇) and, referencing the threat model, determine how much additional risk there really is from a feature like this.
2. IF we determine that there is significant additional risk, we (+ SecureDrop UX team) talk to some admins and see what users think. Do they want to be able to turn off the API? Even though this introduces admin maintenance burden when they have a journalist that wants to start using the Qubes workstation? Generally I'm of the opinion that for the most part, it's our job to evaluate the risk and make application architecture decisions that minimize risk to users overall, but that said - if users do want more flexibility in controlling the application, then we should respect that. 

PS: Earlier in this thread the comment about not exposing primary keys via the API I agree with (we should either use the `journalist_designation` or the `filesystem_id` (as we do in the existing web application)), so that's one additional change to make.

**Comment by emkll** [comment]
I agree with not exposing the primary key. You can find another good list of recommentations [here](https://github.com/shieldfy/API-Security-Checklist/blob/master/README.md). Here are some initial thoughts on this, after taking a quick glance at the journalist-api branch and the spec @redshiftzero described above.

First, areas where risks could be reduced:

- For a client, using an API at the command line would eliminate browser-based attacks, though a significantly larger risk is malware submission through SecureDrop to compromise this same computer. Therefore, benefits are limited for Journalists. However, they would be more significant for Sources, if we were to implement a Source API.
- Using a client can also provide the opportunity and control to implement new security features: 
  - Certificate pinning and ssl/tls for the Journalist interface. 
  - Client certificates to authenticate clients, for an added layer of channel authentication/encryption

Here are the the areas where I think incremental risk is introduced:

- We will be developing/maintaining sensitive (though fairly simple) parts of the the code, specifically authentication, which can increase the risk of developer error.
- The API would expose a duplicate set of functionality, and maybe difficult to use the API for the web application (due to limited use of JavaScript), increasing attack surface, probability of developer error and maintenance burden (client certs would be a great way to mitigate this). 
- Much of this incremental risk will also depend on the client application. Modern browsers have sandboxing capabilities, which will likely not be present in more lightweight/native UI frameworks. For that reason, I think that the client directly handling decrypted, un-sanized submissions is out of the question, and that sanitization should occur outside the domain of client application.
- It is critical we use 2-Factor authentication and fairly short sessions, given the upcoming SecureDrop workstation use case, where we are introducing persistence to the journalist environment.

There would be other ways to implement authentication but I think the method described above makes the most sense:
- OAuth - definitely overkill as we won't use federation and it's quite complex protocol.
- Signed requests: Using a asymmetric key pair to sign your API request. Key management might be a bit of a challenge, but it could be an interesting incremental improvement to the authentication header approach.
