### ISSUE TITLE
Release SecureDrop 0.4

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1922]
This is a tracking issue for the upcoming release of SecureDrop 0.4 - tasks may get added or modified.

# Pre-release
- [x] Prepare changelog - @redshiftzero
- [x] Send 0.4 pre-release notification to admins to give them sufficient time to prepare - @redshiftzero

# Finish release candidate (0.4-rc1)
- [x] Branch release/0.4 off develop once all necessary milestone issues are completed - @redshiftzero
- [x] Merge in any last minute PRs (#1926, #1934) - @redshiftzero
- [x] Build test debs - @conorsch
- [x] Stand up test apt server with 0.4-rc1 packages - @conorsch

# QA (0.4-rc1)

- [x] Unit tests pass on 0.4 staging VMs - @redshiftzero
- [x] Test upgrade from 0.3.12 works on prod w/ test repo debs - @msheiny, @conorsch 
- [x] Test install (not upgrade) of 0.4 works on prod w/ test repo debs - @redshiftzero
- [ ] Test upgrade from 0.3.12 works on hardware w/ test repo debs without running playbooks  [skipped until second round of test debs]
- [ ] Test upgrade from 0.3.12 works on hardware w/ test repo debs and re-running Ansible playbooks from admin workstation [skipped until second round of test debs]
- [x] Test fresh install (not upgrade) of 0.4 works on hardware w/ test repo debs - @redshiftzero

# Documentation

- [x] Make documentation changes against `release/0.4`

# Finish release candidate (0.4-rc2)
- [x] Merge in remainder of fixes from 0.4-rc1
- [x] Build test debs - @conorsch 
- [x] Stand up test apt server with 0.4-rc2 packages - @conorsch 

# QA (0.4-rc2)

- [x] Test upgrade from 0.3.12 works on hardware w/ test repo debs without running playbooks - @conorsch
- [x] Test upgrade from 0.3.12 works on hardware w/ test repo debs and re-running Ansible playbooks from admin workstation - @conorsch
- [x] Test fresh install (not upgrade) of 0.4 works on hardware w/ test repo debs - @redshiftzero

# Release

- [x] Build final Debian packages for 0.4 - @conorsch
- [x] Release 0.4
- [x] Publish blog post about 0.4 Debian package release and instructions for admins - @redshiftzero

# Post-release

- [ ] Merge release changes into master branch - @redshiftzero
- [ ] Merge release changes into development branch - @redshiftzero

**Comment by redshiftzero** [comment]
## 0.4-rc1: Fresh install on hardware

Trying to be super clear what I did and did not test for posterity, so I'm pasting my testing checklist here. The two things from the plan I have not tested are at the end of the checklist, will update this comment as I go

### 0.4 Specific Testing

- [x] During installation the system rebooted once after security updates and then again at the end (test of reboot strategy in #951)
- [x] No HTTPS cert provided works fine. Source interface displayed without issue.
- [x] Invalid OSSEC GPG fingerprint cannot be provisioned due to validate role
- [x] Invalid app GPG fingerprint cannot be provisioned due to validate role
- [x] No ssh_user in site-specific produces error in `./securedrop-admin install`

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [ ] AppArmor is NOT loaded on mon - this is fine (test plan and docs updated in PR #2013)
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] OSSEC emails contain the string "Ossec server started"

#### Command Line User Generation

- [x] Can successfully add admin user
- [x] User with empty password cannot be created
- [x] User with password < 12 characters cannot be created

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, unicode submissions submitted successfully
- [x] On submit page, 150 paragraph text submitted successfully 
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded - ok this is realllly annoying to test in Tails but I _did_ test this on 0.4-rc1 prod VMs
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download all" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete collection" and the source and docs are deleted
- [x] You can click on a document and succesfully decrypt on SVS

### Not yet tested

- [ ] Backup and restore playbooks
- [ ] Fresh install using HTTPS certs on source interface
