### ISSUE TITLE
Migrate from generalizable ORM to Postgres-only

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2225]
# Feature request

## Description

Currently SecureDrop uses SqlAlchemy as its ORM, and such we make no assumptions about what sort of relation DB is used. It *could* be MySQL, MariaDB, Postgres, or SQLite (not to mention different versions). This adds unnecessary complexity in that we can't optimize for any one database as such optimizations may not translate to another. Likewise, we don't support DB schema migrations, and when we start supporting those, there would have to tests done with realistically simulated data sets *on all databases*. This is again complexity that slows down development.

SecureDrop should only support the latest version of Postgres. It should also take advantage of the security features around users and groups to restrict what the different applications can do.

### Migration Prep

1. Write a one time script that can load a realistic data set (~6 months) into:
  a. Postgres
  b. MariaDB
  c. MySQL
  d. SQLite
2. Create the tables using SqlAlchemy
3. Write a migration script for each database
4. Create the new database using the new ORM and/or scripts
5. Migrate each of the databases
6. Ensure consistency
7. Merge to `develop` for next minor release

### TODO

The loose plan for this could be:

- [ ] Write data-simulation script
- [ ] Write Postgres DDL
- [ ] Write migration scripts for:
  - [ ] MySQL
  - [ ] MariaDB
  - [ ] Postgres (with SqlAlchemy autogenerated DDL)
  - [ ] SQLite
- [ ] Test migrations
- [ ] Add migrations to Debian maintainer scripts (or app code)
- [ ] Update docs
- [ ] Have running instances use `postgres://localhost:5432/securedrop` as a default DB with a *new* field in `config.py` called `POSTGRES_URL` that overrides it
- [ ] Deprecate `POSTGRES_URL`'s default value and force admins to provide a URL  
  - This should be sufficient since migrating the DB from one PG instance to another is trivial

### Research

Someone in a more official position at FPF should reach out to current admins and ask if any of them are using non-default settings. Which DB are they using? Did they set up a DB with a custom DDL that nicely matches up with SqlAlchemy? If so, why? And how would this affect a migration?

## User Stories

As a developer, I want to streamline my code to have a minimal number of paths (e.g., not having to ensure migrations work on 4+ databases).

As security nerd, I want to make it more difficult for the source interface to be able to access the journalist-specific tables.

**Comment by redshiftzero** [comment]
btw - everyone we are aware of in production is using SQLite, and it would require significant work for a securedrop admin to use and maintain another database backend. For future development we can treat non-SQLite databases as unsupported

**Comment by heartsucker** [comment]
> it would require significant work for a securedrop admin to use and maintain another database backend.

There's actually SQLite specific stuff we've done (pragmas), and instances would have broken if the werent' SQLite. I think we can all but guarantee they are SQLite at this point.
