### ISSUE TITLE
Release SecureDrop 0.5.2

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#2937]
This is a tracking issue for the upcoming release of SecureDrop 0.5.2 - tasks may get added or modified. Note that this is a hotfix release and translation updates will not be required. 

_SecureDrop maintainers and testers:_ As you QA 0.5.2, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 0.5.2 milestone for tracking. 

# Prepare first release candidate (0.5.2-rc1)
- [ ] Branch `release/0.5.2` off `master`
- [ ] Cherry pick in changes for the release:
  - [ ] Add new languages to `sdconfig` prompt (#2894)
  - [ ] Replacement of `PyCrypto` (#2903)
  - [ ] Dynamically open firewall during OSSEC registration (#2748)
  - [ ] Force immediate Ansible exits (#2922)
  - [ ] Disabling of pip `safety` check in release branch due to use of Ansible <2.4 (#2928)
  - [ ] Followup to #2922, ensuring Ansible will fail fast for all plays (#2935)
- [ ] Prepare `0.5.2-rc1` tag
- [ ] Build debs and put up `0.5.2-rc1` on test apt server

# QA (0.5.2-rc1)

- [ ] Test upgrade from 0.5.1 works on prod w/ test repo debs
- [ ] Test fresh install (not upgrade) of 0.5.2 works on prod w/ test repo debs

# Prepare final release candidate (0.5.2-rcN)
- [ ] Prepare `0.5.2-rcN` tag
- [ ] Build debs and put up `0.5.2-rcN` on test apt server
- [ ] Test upgrade from 0.5.1 works on w/ test repo debs

# Release

- [ ] Push signed tag
- [ ] Build final Debian packages for 0.5.2
- [ ] Pre-Flight: Test install (not upgrade) of 0.5.2 works on prod w/ test repo debs
- [ ] Put final deb packages up
- [ ] Publish blog post about 0.5.2 Debian package release and instructions for admins

# Post-release

- [ ] Merge release changes into master branch
- [ ] Merge release changes into development branch

**Comment by redshiftzero** [comment]
Here's a proposal for what should be tested during the QA period - let me know if you think items should be added or removed and we can make sure we test them 🐉  

# SecureDrop 0.5.2 Test Plan

## Ensure the dynamic opening of the firewall during OSSEC agent registration works as expected

1. Re-provision prod VMs.
**Expected result:** OSSEC alerts continue to flow.
2. [Deauthorize app server as ossec-agent](https://github.com/freedomofpress/securedrop/issues/2478#issuecomment-351213581).
3. Reprovision. 
**Expected result:** App server is re-registered and OSSEC alerts begin to flow once again.
4. Reprovision once more.
**Expected result:** OSSEC alerts continue to flow.

## All languages appear in `securedrop-admin sdconfig` locale prompt

1. Run `./securedrop-admin sdconfig`
**Expected result:** `"ar, it_IT, tr, zh_Hant"` should all appear in the prompt for locales.

## Documents can be successfully decrypted

1. Submit a document via the source interface.
2. Attempt to decrypt document.
**Expected result:** Document is successfully decrypted.

## Verify Ansible fails fast

1. Provision your prod VMs (i.e. `./securedrop-admin install`)
2. Turn off one of your VMs.
**Expected result:** The entire playbook should halt execution.

**Comment by redshiftzero** [comment]
## Upgrade testing 0.5.2~rc1

- [x] Upgrade to Tor 0.3.2.9-1~trusty+1 and ensure all onion services work
- [x] Ensure the dynamic opening of the firewall during OSSEC agent registration works
- [x] All languages appear in `sdconfig`
- [x] Documents can be successfully decrypted
- [x] Verify Ansible fails fast

**Comment by msheiny** [comment]
# Fresh install testing 0.5.2~rc1

- [x] Upgrade to Tor 0.3.2.9-1~trusty+1 and ensure all onion services work
- [ ] Ensure the dynamic opening of the firewall during OSSEC agent registration works
- [ ] All languages appear in sdconfig
- [ ] Documents can be successfully decrypted
- [ ] Verify Ansible fails fast

**Comment by kushaldas** [comment]
## Upgrade testing 0.5.2~rc1

- [x] Upgrade to Tor 0.3.2.9-1~trusty+1 and ensure all onion services work
- [x] Ensure the dynamic opening of the firewall during OSSEC agent registration works
- [x] All languages appear in `sdconfig`
- [x] Documents can be successfully decrypted
- [x] Verify Ansible fails fast

All UI tests were done using the on going Tor Browser + Selenium :)

**Comment by emkll** [comment]
## Clean install - 0.5.2~rc1 on prod VMs

- [x] Upgrade to Tor 0.3.2.9-1~trusty+1 and ensure all onion services work
- [x] Ensure the dynamic opening of the firewall during OSSEC agent registration works
- [x] All languages appear in `sdconfig`
- [x] Documents can be successfully decrypted
- [x] Verify Ansible fails fast
