### ISSUE TITLE
Release SecureDrop 0.6.0

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3061]
This is a tracking issue for the upcoming release of SecureDrop 0.6 - tasks may get added or modified. 

**Feature freeze:** February 27, 2018
**String freeze:** March 6, 2018
**Release date:** March 13, 2018
 
_SecureDrop maintainers and testers:_ As you QA 0.6, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 0.6 milestone for tracking. 

Test debian packages are posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d).

# Prepare release candidate (0.6~rc2)
- [x] Branch `release/0.6` off `master` - @redshiftzero
- [x] `0.6-rc1` was created but we did not build test debs as we needed to bump the kernels (#3077) 
- [x] Prepare `0.6-rc2` tag - @redshiftzero
- [x] Build debs and put up `0.6~rc2` on test apt server - @conorsch

# QA (0.6~rc2)

- [x] Test upgrade from 0.5.2 works on prod w/ test repo debs
- [x] Test fresh install (not upgrade) of 0.6 works on prod w/ test repo debs

# Prepare next release candidate (0.6~rc3)
- [x] Prepare `0.6-rc3` tag - @redshiftzero
- [x] Build debs and put up `0.6~rc3` on test apt server - @conorsch

# QA (0.6~rc3)

- [x] Test upgrade from 0.5.2 works on prod w/ test repo debs
- [ ] Test fresh install (not upgrade) of 0.6 works on prod w/ test repo debs

# Prepare next release candidate (0.6~rc4)
- [x] Prepare `0.6-rc4` tag - @redshiftzero
- [x] Build debs and put up `0.6~rc4` on test apt server - @conorsch

# QA (0.6~rc4)

- [ ] Test upgrade from 0.5.2 works on prod w/ test repo debs
- [ ] Test fresh install (not upgrade) of 0.6 works on prod w/ test repo debs

# Prepare final release candidate (0.6~rc5)
- [x] Prepare `0.6-rc5` tag - @redshiftzero
- [x] Build debs and put up `0.6~rc5` on test apt server - @conorsch

# Final release

- [x] Push signed tag
- [x] Build final Debian packages for 0.6
- [x] Pre-Flight: Test install (not upgrade) of 0.6 works w/ prod repo debs
- [x] Publish blog post about 0.6 Debian package release and instructions for admins

# Post-release

- [ ] Merge release changes into master branch
- [ ] Merge release changes into development branch

**Comment by dachary** [comment]
It would be great to have detailed Q/A scripts that [volunteers with a lot of good will but experience with SecureDrop](https://forum.securedrop.club/t/call-for-help-q-a-volunteers-for-0-6/440) could run manually. Do we have that already ?

**Comment by redshiftzero** [comment]
For getting setup with prod VMs for testing, [this](https://docs.securedrop.org/en/latest/development/virtual_environments.html#production-vms) is the best documentation we have, and [this post](https://kushaldas.in/posts/setting-up-securedrop-0-5rc2-in-vms-for-qa.html) by @kushaldas is useful (version numbers will need bumping). In terms of QA scripts the most detailed generic (for any release) testing script we have is the following - it covers basic server testing and application acceptance testing:

## A. Tests from the Admin Tails Drive
1. You should be able to access the source and journalist interfaces
* Open up Tor browser and try it out on both interfaces

2. You should be able to SSH into app and mon over Tor
* `ssh app`
* `ssh mon`

3. OSSEC should start up
* **Execution steps:**
  * Check your email 
* **Expected behavior:**
  * Check that OSSEC alerts were received
  * Verify that you can decrypt the message

4. Check that both servers are running grsec kernels

 * **Preconditions:** You SSH into each server.
 * **Execution steps:**
   * Run `uname -a`
 * **Expected output:**
   * `-grsec` is in the kernel name

5. Verify AppArmor is loaded

  * **Preconditions:** You SSH into both servers.
  * **Execution steps:**
     * Run `sudo aa-status`
  * **Expected output:**
    * `apparmor module is loaded` appears in the output

6. Check iptables rules are set up

  * **Preconditions:** You SSH into each server.
  * **Execution steps:**
    * Run `sudo iptables-save`
  * **Expected output:**
    * iptables rules are printed to stdout
    * The iptables output is dozens of lines, _not_ just the default `ACCEPT` chains

## B. Test Cases For Command Line User Creation

1. You can create a administrator from the command line.
* **Precondition:** You are SSHed into app
* **Execution steps** [are described here](https://docs.securedrop.org/en/latest/create_admin_account.html#create-an-admin-account-on-the-journalist-interface). 
* **Expected behavior:** 
   * You are able to login using the account made at the command line
   * Admin panel is available in journalist web interface

## C. Test Cases for Source Interface
 * **Precondition:** You have used Tor Browser to navigate to the source interface.

### Landing Page Base Cases
 1. When the Tor Browser Security slider is at its lowest setting, a purple bar appears along the top of the application indicating that one should turn the security slider to high.
 2.  When the Tor Browser Security slider is at its highest setting, this bar does not appear.

### First Submission Base Cases
 * **Precondition:** You have clicked “Submit Documents” on the home page.

3.   On the generate page, clicking refresh changes the codename. 7 words appear before and after changing the codename.
4. On the submission page, clicking “Submit” with no documents or messages written generates an error message. 
5. On the submission page, typing a message “test” and clicking “Submit” generates a “Success!” flashed message.
6. On the submission page, attempt to upload a file greater than 500 MB. This should not work and a “The Connection Was Reset” page should appear.
7. On the submission page, attempting to upload a file less than 500 MB results in a green success flashed message.

### Returning Source Base Cases

* **Precondition:** You have clicked “Check for a response” on the home page.

8. Entering an empty codename results in a “Sorry that is not a recognized codename” flashed message.
9. Entering a legitimate codename results in a source being able to successfully login.
10. On the submission page, journalist responses appear (one will need to be logged in).

## D. Test Cases for Journalist Interface

* **Precondition:** You have used Tor Browser to navigate to the journalist interface.

### Login Base Cases

1. Username “test1” can successfully log in with their 2FA tokens.
2. If user “test1” uses an incorrect password, they get a “Login failed. Please wait for a new two-factor token before logging in again.” flashed message.
3. If “test1” tries to use an invalid 2FA token, they get a “Login failed. Please wait for a new two-factor token before logging in again.” flashed message.
4. If “test1” tries to use the same 2FA token, they get a “Login failed. Please wait for a new two-factor token before logging in again.” flashed message.

### Index Base Cases

**Precondition:** You have used Tor Browser to navigate to the journalist interface and are logged in.

5. Filter by codename on index successfully filters
6. Click “select all” selects all submissions.
7. Selecting “Download All” results in all submissions being downloaded.
8. Starring a source successfully stars a source.
9. Unstarring a source successfully unstars a source.

### Source Page Base Cases

**Precondition:** You have used Tor Browser to navigate to the journalist interface, logged in, and clicked on a given source.

10. You are able to type “Response” and hit “Submit” and get a “Thanks! Your reply has been stored” flashed message. A new row should appear ending in `-reply.gpg`. 
11. You are able to click a document and download it. You can successfully decrypt the document using the submission private key.
12. You are able to submit an empty response and get a flashed message indicating that text needs to be entered.
13. Clicking “Delete collection” results in all documents being deleted for the given source.

**Comment by redshiftzero** [comment]
In terms of 0.6-specific testing, here's a proposed checklist, focused on `securedrop-admin` given the significant changes there:

- [ ] `./securedrop-admin --help` reports useful feedback
- [ ] `./securedrop-admin setup` works in Tails
- [ ] `./securedrop-admin sdconfig` works in Tails
- [ ] `./securedrop-admin sdconfig` allows empty `sasl_domain`
- [ ] `./securedrop-admin install` proceeds without issue after Ansible version bump
- [ ] `./securedrop-admin tailsconfig` proceeds without issue
- [ ] `./securedrop-admin check_for_updates` reports to the user that an update is available
- [ ] `./securedrop-admin update` reports signature verifies and updates workstation to the latest valid tag `0.5.2`
- [ ] Servers are both running 4.4.115 kernels
- [ ] Journalist interface: source deletion confirmation appears (#2946)
- [ ] Journalist interface: with JS enabled, a user gets a confirmation re: 2FA reset (#2920)
- [ ] `/var/lib/tor/services` is monitored by syscheck (#2960)
- [ ] After manual testing of web applications, no AppArmor issues appear in OSSEC alerts

**Comment by redshiftzero** [comment]
## Fresh install `0.6~rc2` in prod VMs

### 0.6~rc2 specific testing

- [x] `./securedrop-admin --help` reports useful feedback
- [x] `./securedrop-admin setup` works in Tails
- [x] `./securedrop-admin sdconfig` works in Tails
- [x] `./securedrop-admin sdconfig` allows empty `sasl_domain`
- [x] `./securedrop-admin install` proceeds without issue after Ansible version bump
- [x] `./securedrop-admin tailsconfig` proceeds without issue
- [x] `./securedrop-admin check_for_updates` reports to the user that an update is available
- [x] `./securedrop-admin update` reports signature verifies and updates workstation to the latest valid tag `0.5.2`
- [x] Servers are both running 4.4.115 kernels
- [x] Journalist interface: source deletion confirmation appears (#2946)
- [x] Journalist interface: with JS enabled, a user gets a confirmation re: 2FA reset (#2920)
- [x] `/var/lib/tor/services` is monitored by syscheck (#2960)
- [x] After manual testing of web applications, no AppArmor issues appear in OSSEC alerts

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete collection" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

**Comment by dachary** [comment]
There are commits to merge back to develop from yesterday's action.

<pre>
$ git --no-pager  log --oneline --cherry-mark --right-only origin/develop...origin/release/0.6
+ 658088bb SecureDrop 0.6~rc2
+ e29bdd74 Merge pull request #3077 from freedomofpress/bump-grsec-metapackage-to-4.4-kernels
+ ab2a05e0 Updates config tests for new kernel image version
+ eb88a67b Updates docs for new kernel image version
+ a9c9643b Bumps securedrop-grsec metapackage to 4.4.115
+ 898690ed SecureDrop 0.6~rc1
</pre>

Proposed at https://github.com/freedomofpress/securedrop/issues/3061

**Comment by dachary** [comment]
I see we are creating 0.6 packages and tags. Could we please switch to [using 0.6.0 instead](https://forum.securedrop.club/t/proposal-for-a-new-release-cycle-based-on-stable-branches/410)? So we have a uniform naming scheme.

**Comment by msheiny** [comment]
So I thought this was important ... but I just performed an upgrade and confirmed that the old `3.14.79-grsec` kernel was still in the boot menu. This is important so if any instances have issues they can roll back temporarily.

**Comment by msheiny** [comment]
## Upgrade install `0.6~rc2` in prod VMs

### 0.6~rc2 specific testing

- [x] `./securedrop-admin --help` reports useful feedback
- [x] `./securedrop-admin setup` works in Tails
- [x] `./securedrop-admin sdconfig` works in Tails
- [x] `./securedrop-admin sdconfig` allows empty `sasl_domain`
- [ ] `./securedrop-admin install` proceeds without issue after Ansible version bump
- [ ] `./securedrop-admin tailsconfig` proceeds without issue
- [ ] `./securedrop-admin check_for_updates` reports to the user that an update is available
- [ ] `./securedrop-admin update` reports signature verifies and updates workstation to the latest valid tag `0.5.2`
- [x] Servers are both running 4.4.115 kernels
- [x] Journalist interface: source deletion confirmation appears (#2946)
- [x] Journalist interface: with JS enabled, a user gets a confirmation re: 2FA reset (#2920)
- [x]  `/var/lib/tor/services` is monitored by syscheck (#2960)  
- [x] After manual testing of web applications, no AppArmor issues appear in OSSEC alerts

**Comment by emkll** [comment]
## Fresh install `0.6~rc2` in prod VMs

### 0.6~rc2 specific testing

- [x] `./securedrop-admin --help` reports useful feedback
- [x] `./securedrop-admin setup` works in Tails
- [x] `./securedrop-admin sdconfig` works in Tails
- [x] `./securedrop-admin sdconfig` allows empty `sasl_domain`
- [x] `./securedrop-admin install` proceeds without issue after Ansible version bump
- [x] `./securedrop-admin tailsconfig` proceeds without issue
- [x] `./securedrop-admin check_for_updates` reports to the user that an update is available
- [x] `./securedrop-admin update` reports signature verifies and updates workstation to the latest valid tag `0.5.2`
- [x] Servers are both running 4.4.115 kernels
- [] Journalist interface: source deletion confirmation appears (#2946)
- [] Journalist interface: with JS enabled, a user gets a confirmation re: 2FA reset (#2920)
- [] `/var/lib/tor/services` is monitored by syscheck (#2960)
- [] After manual testing of web applications, no AppArmor issues appear in OSSEC alerts

### Basic Server Testing

- [] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [] Can successfully add admin user and login

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [] JS warning bar does not appear when using Security Slider high
- [] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [] On generate page, refreshing codename produces a new 7-word codename
- [] On submit page, empty submissions produce flashed message
- [] On submit page, short message submitted successfully
- [] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [] Nonexistent codename cannot log in
- [] Empty codename cannot log in
- [] Legitimate codename can log in
- [] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [] Can log in with 2FA tokens
- [] incorrect password cannot log in
- [] invalid 2fa token cannot log in
- [] 2fa immediate reuse cannot log in

##### Index base cases
- [] Filter by codename works
- [] Starring and unstarring works
- [] Click select all selects all submissions
- [] Selecting all and clicking "Download" works

##### Individual source page
- [] You can submit a reply and a flashed message and new row appears
- [] You cannot submit an empty reply
- [] Clicking "Delete collection" and the source and docs are deleted
- [] You can click on a document and successfully decrypt using application private key

**Comment by kushaldas** [comment]
## Update from '0.5.2' to  `0.6~rc2` in prod VMs

### 0.6~rc2 specific testing

- [x] `./securedrop-admin --help` reports useful feedback
- [x] `./securedrop-admin setup` works in Tails  (But, I also had to file #3088) 
- [x] `./securedrop-admin sdconfig` works in Tails
- [x] `./securedrop-admin sdconfig` allows empty `sasl_domain`
- [x] `./securedrop-admin install` proceeds without issue after Ansible version bump
- [x] `./securedrop-admin tailsconfig` proceeds without issue
- [x] `./securedrop-admin check_for_updates` reports to the user that an update is available
- [x] `./securedrop-admin update` reports signature verifies and updates workstation to the latest valid tag `0.5.2`
- [x] Servers are both running 4.4.115 kernels
- [x] Journalist interface: source deletion confirmation appears (#2946)
- [x] Journalist interface: with JS enabled, a user gets a confirmation re: 2FA reset (#2920)
- [ ] `/var/lib/tor/services` is monitored by syscheck (#2960) (DId not test)
- [x] After manual testing of web applications, no AppArmor issues appear in OSSEC alerts

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete collection" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

**Comment by dachary** [comment]
Only cherry-picks in the `release/0.6` as shown by the **=** sign which indicates two commits have the same `patch-id`.

<pre>
$ git --no-pager  log  --no-merges --oneline --cherry-mark --right-only origin/develop...origin/release/0.6
= 4ec882bb Monitor only hostname in /var/lib/tor/services
= 1b67299b journalist: kindly ask to check the mail
</pre>

**Comment by emkll** [comment]
## Fresh install `0.6~rc2` in prod VMs

### 0.6~rc2 specific testing

- [x] `./securedrop-admin --help` reports useful feedback
- [x] `./securedrop-admin setup` works in Tails
- [x] `./securedrop-admin sdconfig` works in Tails
- [x] `./securedrop-admin sdconfig` allows empty `sasl_domain`
- [x] `./securedrop-admin install` proceeds without issue after Ansible version bump
- [x] `./securedrop-admin tailsconfig` proceeds without issue
- [x] `./securedrop-admin check_for_updates` reports to the user that an update is available
- [] `./securedrop-admin update` reports signature verifies and updates workstation to the latest valid tag `0.5.2`
- [] Servers are both running 4.4.115 kernels
- [] Journalist interface: source deletion confirmation appears (#2946)
- [] Journalist interface: with JS enabled, a user gets a confirmation re: 2FA reset (#2920)
- [] `/var/lib/tor/services` is monitored by syscheck (#2960)
- [] After manual testing of web applications, no AppArmor issues appear in OSSEC alerts

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [] On generate page, refreshing codename produces a new 7-word codename
- [] On submit page, empty submissions produce flashed message
- [] On submit page, short message submitted successfully
- [] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [] Nonexistent codename cannot log in
- [] Empty codename cannot log in
- [] Legitimate codename can log in
- [] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [] Can log in with 2FA tokens
- [] incorrect password cannot log in
- [] invalid 2fa token cannot log in
- [] 2fa immediate reuse cannot log in

##### Index base cases
- [] Filter by codename works
- [] Starring and unstarring works
- [] Click select all selects all submissions
- [] Selecting all and clicking "Download" works

##### Individual source page
- [] You can submit a reply and a flashed message and new row appears
- [] You cannot submit an empty reply
- [] Clicking "Delete collection" and the source and docs are deleted
- [] You can click on a document and successfully decrypt using application private key

**Comment by redshiftzero** [comment]
# Upgrade 0.5.2 -> `0.6-rc3` in prod VMs

## 0.6~rc3 specific testing

- [x] `./securedrop-admin --help` reports useful feedback
- [x] `./securedrop-admin setup` works in Tails
- [x] `./securedrop-admin sdconfig` works in Tails
- [x] `./securedrop-admin sdconfig` allows empty `sasl_domain`
- [x] `./securedrop-admin install` proceeds without issue after Ansible version bump
- [x] `./securedrop-admin tailsconfig` proceeds without issue
- [x] `./securedrop-admin check_for_updates` reports to the user that an update is available
- [x] `./securedrop-admin update` reports signature verifies and updates workstation to the latest valid tag `0.5.2`
- [x] Servers are both running 4.4.115 kernels
- [x] Journalist interface: source deletion confirmation appears (#2946)
- [x] Journalist interface: with JS enabled, a user gets a confirmation re: 2FA reset (#2920)
- [x] `/var/lib/tor/services` is monitored by syscheck (#2960)
- [x] After manual testing of web applications, no AppArmor issues appear in OSSEC alerts

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete collection" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

**Comment by kushaldas** [comment]
# Upgrade 0.6-rc3 -> `0.6-rc4` in prod VMs

## 0.6~rc4 specific testing

- [x] `./securedrop-admin --help` reports useful feedback
- [x] `./securedrop-admin setup` works in Tails
- [x] `./securedrop-admin sdconfig` works in Tails
- [x] `./securedrop-admin sdconfig` allows empty `sasl_domain`
- [x] `./securedrop-admin install` proceeds without issue after Ansible version bump
- [x] `./securedrop-admin tailsconfig` proceeds without issue
- [x] `./securedrop-admin check_for_updates` reports to the user that an update is available
- [x] `./securedrop-admin update` reports signature verifies and updates workstation to the latest valid tag `0.5.2`
- [x] Servers are both running 4.4.115 kernels
- [x] Journalist interface: source deletion confirmation appears (#2946)
- [x] Journalist interface: with JS enabled, a user gets a confirmation re: 2FA reset (#2920)
- [x] `/var/lib/tor/services` is monitored by syscheck (#2960)
- [x] After manual testing of web applications, no AppArmor issues appear in OSSEC alerts

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete collection" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

**Comment by emkll** [comment]
I have tested the kernel metapackage changes as part of 0.6-rc5

## Classic upgrade scenario (pre-Feb 16) 0.5.2 -> 0.6:
[x] Kernel 3.14 is installed
[x] Kernel 4.4 is installed
[x] Kernel 4.4 boots by default

## Alternate upgrade scenario (SD instance installed after Feb 16) 0.5.2 -> 0.6:
[] Kernel 3.14 is installed
[] Kernel 4.4 is installed
[] Kernel 4.4 boots by default

**Comment by eloquence** [comment]
SecureDrop 0.6 went out as planned on March 13, closing. :)
