### ISSUE TITLE
Add simple GUI updater for Tails journalist workstation

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3076]
In #3026, we added two commands to `securedrop-admin` for checking for updates and updating `~/Persistent/securedrop`. We should have a simple GUI journalist updater that uses these two commands, along with `securedrop-admin tailsconfig` to update the journalist workstation. This would replace the routine use of the CLI for the journalist workstation. This was initially described in [#2976 (comment)](https://github.com/freedomofpress/securedrop/issues/2976#issuecomment-366048451). Also: 

* The sudo password is needed for `tailsconfig` so we'll need to have a prompt appear for that.

* We should have `securedrop-admin check_for_updates` run on boot as part of our network hook.

# Remaining tasks

Tasks have individual issues and are copied here from [this comment](https://github.com/freedomofpress/securedrop/issues/3076#issuecomment-377652781):

- [x] Finish test suite so that we can catch bugs before test users (#3234)
- [x] Fix sluggish window resizing (#3233)
- [x] Related idea: Shrink the logo and add a Tails Installer inspired SecureDrop banner across the top? (#3235)
- [x] Run blocking actions (`securedrop-admin update` and `securedrop-admin tailsconfig`) in a `QThread` (#3228)
- [x] See if we can add a time estimate to the update progress bar as @ei8fdb suggested (#3230)
- [x] Add CI job for running the GUI tests (#3229)
- [x] Add developer docs (#3231)
- [x] Add note about this feature in the admin, journalist guides (#3232)
- [x] Restart failed updates on next reboot (#3264)

I propose we PR into `qt-journalist-updater` to build out this feature. When the feature is complete, then someone will propose the branch for merge into the mainline SecureDrop. This approach will make it easier for us to develop a slightly larger feature without trying to do it all in one hard-to-review massive PR.

# User Stories

As a journalist, I want my SecureDrop workstation to notify me when an update is needed so that I don't need to rely on my (or my administrator's) awareness of the SecureDrop release cycle. 

As a journalist, I want to use a simple GUI to update my journalist workstation so that I do not need to  use the command line. 

As an administrator, I want journalists to be able to update their own workstations to reduce the amount of time I spend maintaining my SecureDrop deployment.

**Comment by ei8fdb** [comment]
@redshiftzero This seems like a really good idea. 

My feeling is the  most realistic user story would be the last you've mentioned above about the admin.

The administrator would want the journalist user to be able to manage the workstation as *the administrator* benefits more directly, than the journalist - the journalist is doing the work, not the administrator.

A couple of questions that might have some impact on the UI 

- how often does the SecureDrop Updater check for updates?

- I guess updates occur at the end of each release cycle? Not more often?

@dachary, @belenbarrospena and I spoke about it last week. The main questions I would see a user asking are:

- How long will this update take?

It is good practice to give the user some indication of how long an action will take.

The update is done via the Tor network - so there is a strong possibility it might take longer than on the clear web?

- If I shutdown while the update is going on, what happens? Can it be resumed? Or do I need to restart it from the beginning?

If you like I can put together a simple wireframe based on your proto in #2976?

**Comment by redshiftzero** [comment]
> How often does the SecureDrop Updater check for updates?

So right now in this `qt-journalist-updater` branch, every time the workstation boots, it will check for updates - this part is transparent to the user. If updates are needed, the GUI pops up. This is also how the Tails updater works. 

> I guess updates occur at the end of each release cycle? Not more often?

Yep, exactly. The time between updates is between 2-8 weeks (on the shorter side if we do a few bugfix releases). 

> How long will this update take?

5 minutes or so, 10 at the outset (even with Tor). 

> It is good practice to give the user some indication of how long an action will take.

Great point, I could add some text that explicitly says this.

> If I shutdown while the update is going on, what happens? Can it be resumed? Or do I need to restart it from the beginning?

Yeah, good point. I'll add some functionality to handle this better. Specifically, right now if we get to the point of checking out the release tag, then `securedrop-admin check_for_updates` considers the workstation updated, even if tailsconfig did not run. This is not ideal. 

A wireframe would be great! I _was_ thinking that the big text box showing detailed output of the update process should not be shown by default (unnecessary technical detail for 95%+ of users).

Here are some screenshots of the latest prototype for reference:

<img width="415" alt="screen shot 2018-03-19 at 10 12 37 am" src="https://user-images.githubusercontent.com/7832803/37614752-cb2bee24-2b68-11e8-89a2-46554b5d574f.png">

and here is what the current dialog boxes look like: 

<img width="225" alt="screen shot 2018-03-19 at 10 11 42 am" src="https://user-images.githubusercontent.com/7832803/37614791-e063ac50-2b68-11e8-828e-70ed36c1ac52.png">

<img width="317" alt="screen shot 2018-03-19 at 10 13 34 am" src="https://user-images.githubusercontent.com/7832803/37614822-f06a1f62-2b68-11e8-9dda-7867b6732824.png">

**Comment by redshiftzero** [comment]
Hey @kushaldas - as discussed on our one on one today, here's the current state of this branch (`qt-journalist-updater`): I'm curious if you have any protips based on your experience with PyQt. For the test suite for this feature, I planned to mock out the subprocess calls but otherwise test the behavior when buttons are clicked. To automate sending input to different elements of the GUI (like button clicks), I planned to use either  `PyQt5.QtTest.QTest` or [`pytest-qt`](https://pytest-qt.readthedocs.io/en/latest/) - that said, this is totally open to change if you are aware of another tool that is better/easier for the task. 

Currently however, when I'm using e.g. `pytest-qt`, the interactive button presses aren't working, so I'm missing something possibly obvious. 

To get set up on this branch, I do:

```
$ cd journalist_gui
$ mkvirtualenv journalist_gui -p python3
$ pip3 install requirements.txt
$ pip3 install test-requirements.txtg
```

Then tests can be executed in that directory via `pytest -v tests/`, and the application can be run via `python3 SecureDropUpdater`. 

An example of functionality that I would want to test using button clicks is the following modification I made based on @ei8fdb's feedback, which hides detailed technical output unless the user is interested:

![shrinkoutput](https://user-images.githubusercontent.com/7832803/37999023-e41dcdf8-31d5-11e8-8dfb-95d0b144be58.gif)

I wrote a test ([see full code here](https://github.com/freedomofpress/securedrop/commit/b9e2ba96940b0beaa32237e1dc2dc79f858f6a6b#diff-2f8568d1fc5e9d8687803b808be99705R22)) to test this specifically:

```
def test_output_text_box_displayed_when_checkbox_toggled(app, window, gui):
    gui.mouseClick(window.groupBox, QtCore.Qt.LeftButton)
    assert window.plainTextEdit.isVisible() == True

    # And clicking again should hide the text box once again
    gui.mouseClick(window.groupBox, QtCore.Qt.LeftButton)
    assert window.plainTextEdit.isVisible() == False
``` 

However, running the test fails, due to the mouseClicks not working yet. Take a peek, I welcome any feedback. If there isn't something obvious, then my next step will be to write some more tests for some toy examples prior to returning to this.

**Comment by kushaldas** [comment]
@redshiftzero You have a `QGroupBox` which is `checkable`. But, we can not test that with mouse click. The suggestion from KDE developers was to use a proper `QCheckBox` instead.  The other suggestion was not to have a widget which disappears/reappears.

I pushed a [new branch](https://github.com/freedomofpress/securedrop/tree/kushal-is-qt/journalist_gui) on top of your work. It was a new ui file (with layouts) and corresponding python code. I also added a commit to use simple Python unittest module to test the application. That way we will not depend on any external module for testing.

**Comment by ei8fdb** [comment]
@redshiftzero this looks really good. Simple, straight forward design. 

As  @eloquence said on the Monday UX call with @dachary and @belenbarrospena this would be a good candidate to test with users.

@redshiftzero What's the most achievable way of me getting this running? If it helps, I have the dev environment setup on my local machine.

Using that we can then do some usability testing with SecureDrop users.

@eloquence to make sure we are able to test, it'd be reall helpful if @belenbarrospena and I could get some assistance on identifying users who we can test it with.

**Comment by redshiftzero** [comment]
> You have a QGroupBox which is checkable. But, we can not test that with mouse click. 

Oh interesting - I did _not_ know this. So for me on your branch `test_output_text_box_displayed_when_checkbox_toggled` in `test_gui.py` is not passing for me:

```
======================================================================
FAIL: test_output_text_box_displayed_when_checkbox_toggled (__main__.WindowTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_gui.py", line 41, in test_output_text_box_displayed_when_checkbox_toggled
    self.assertTrue(self.window.plainTextEdit.isEnabled())
AssertionError: False is not true

----------------------------------------------------------------------
```

Let's discuss and debug together in our one on one tomorrow @kushaldas? 

For now @ei8fdb we still have a little bit of work to do before we do testing. However since you have the development environment set up one can get the UI running from your SecureDrop git repository by doing the following:

```
$ git fetch --all
$ git checkout qt-journalist-updater
$ cd journalist_gui
$ mkvirtualenv journalist_gui -p python3
$ pip3 install requirements.txt
$ python SecureDropUpdater
```

That said, the way to test this during user testing will be in Tails (either a physical Tails stick or just in a virtual machine). When I'm testing the full functionality of this GUI I use Tails to do so. 

In terms of users who can test when this is a _bit_ more mature (i.e. when we have a test suite verifying that everything is working as expected), I think @kvinton and @micahflee would be good people to test it out 😇.

**Comment by kushaldas** [comment]
@redshiftzero Ah, I forgot to push the final changes. Stupid me. Pushed the changes now. Please try again.

**Comment by kushaldas** [comment]
@redshiftzero Btw, I have also received more suggestions on not to test the Qt side, rather focus on the functions/slots (which we wrote) in the testing of the application.

**Comment by redshiftzero** [comment]
This looks great, so I brought all your additions into `qt-journalist-updater` (feel free to commit directly to that if you like), fixed a couple of minor bugs discovered as I cleaned up and added unit tests. The remaining tasks before this is ready to roll (for user feedback):

- [ ] Finish test suite so that we can catch bugs before test users
- [ ] Fix sluggish window resizing
- [ ] Related idea: Shrink the logo and add a Tails Installer (:wink:) inspired SecureDrop banner across the top? 
- [ ] Run blocking actions (`securedrop-admin update` and `securedrop-admin tailsconfig`) in a `QThread`
- [ ] See if we can add a time estimate to the update progress bar as @ei8fdb suggested

Am I missing anything there? Then we can run this past some users and see what their feedback is. Eventually for merge we'll need to do:

- [ ] Add CI job for running the GUI tests
- [ ] Containerize the GUI dev env (we _could_ punt on this as we don't _need_ to but it would be good)
- [ ] Add developer docs
- [ ] Add note about this feature in the admin, journalist guides

**Comment by redshiftzero** [comment]
User testing script: https://lab.securedrop.club/main/ux/wikis/updater-gui-user-testing
