### ISSUE TITLE
Update kernel source offer build docs

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#3185]
# Feature request

## Description

In #2031 we outlined our procedure for managing source requests for our hardened kernels. The nitty-gritty docs on the steps are mostly in https://github.com/freedomofpress/ansible-role-grsecurity/blob/4a1d159a7bfd7b15caecfd7c42934b81c2863e50/docs/build.md That process, however, largely refers to the 3.x rebuild strategy, and under the 4.x kernels released with 0.6, the process has changed somewhat.

To ensure solid documentation around the kernel maintenance and rebuild story, we should:

* [x] Convert the old [grsecurity build repo](https://github.com/freedomofpress/ansible-role-grsecurity/) to docs focus on the SecureDrop rebuild story. More modern build logic lives in a [separate repo](https://github.com/freedomofpress/ansible-role-grsecurity-build/), and can be imported via scripts to preserve a convenient workflow. https://github.com/freedomofpress/ansible-role-grsecurity/issues/111
* [x] Write new docs for 4.x rebuild story; preserve docs for 3.x kernel story going forward. https://github.com/freedomofpress/ansible-role-grsecurity/issues/112
* [x] Document internal procedure for responding to source offers, so multiple staff members can facilitate responding to requests.
* [x] Update the existing SecureDrop-focused documentation with accurate contact information and URLs.

## User Stories

As a developer, I want to understand what's under the hood in any project I work on. If certain aspects of the project are not immediately discoverable in the prominent code base, then the procedure for gaining access to other related code should be obvious.

As a maintainer, I want to ensure that our management processes around our custom kernels is transparent to the community, with special attention paid to stipulations in the free software licenses in play (e.g. GPL/AGPL).

**Comment by eloquence** [comment]
@conorsch Can you clarify the current status of this issue as you see it, in particular:

> Update the existing SecureDrop-focused documentation with accurate contact information and URLs.

The docs in https://docs.securedrop.org/en/stable/install.html and https://docs.securedrop.org/en/stable/development/apt_repo.html explicitly reference https://github.com/freedomofpress/securedrop/blob/develop/SOURCE_OFFER, which contains up-to-date contact info. As far as you can tell, are there any places where we are publishing inaccurate contact information or URLs?

**Comment by conorsch** [comment]
Looks great to my eye. There was one additional option we discussed, which was supporting `apt source `securedrop-grsec`, which would be a nice convenience, but the request/offer setup we've got now satisfies the same concerns, albeit with a bit more overhead on our part. No immediate need to refine that workflow further, based on volume of requests, so, satisfied with closing.
