### ISSUE TITLE
Remove 2FA for TTY logins

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3247]
# Epic

## Description

As discussed in #1283, 2FA for TTY logins (keyboard attached to App or Mon server) does not buy us additional security; the user at this point can skip 2FA via single user mode.

We should phase out 2FA for TTY logins for all installs to avoid configuration drift. Since this is a change to existing security configuration of the server, clear communication, up to and including a manual confirmation step for existing installs, is essential. 

## Tasks

- [x] Announce that we are phasing out 2FA for TTY logins - #3248
- [ ] Remove 2FA for TTY logins for all installs (must show clear message, potentially confirmation step, for existing installs).
- [ ] If appropriate, create docs for 0.8.0 update (e.g., instruct admins to run `securedrop-admin install`)

**Comment by KwadroNaut** [comment]
I'd like to hear a reasoning for confirmation? If Ida want to keep it, she wants a setup that's different from default. When she wants things to be up-to-date, she should *not* be asked anything while upgrading, otherwise her instance will be outdated?

**Comment by msheiny** [comment]
Yeah im with @KwadroNaut here... i dont understand why we need a confirmation. We want all securedrops to be uniform in their settings.

**Comment by emkll** [comment]
I agree, no confirmation will avoid any potential edge cases. Since this upcoming behavior was well documented and communicated in the release notes, and there were no objections, let's move forward without a confirmation step.
