### ISSUE TITLE
Release SecureDrop 0.7.1

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3443]
This is a tracking issue for the upcoming release of SecureDrop 0.7.1 - tasks may get added or modified.

This is a patch-level release to distribute a kernel update, from version 4.4.115 to 4.4.123. We do not currently anticipate that we will ship any other changes on top of 0.7.0 as part of this release. 

**Pre-release announcement:** Tuesday, May 29, 2018, pending successful QA

**Release:** Tuesday, June 5, 2018

- [ ] Port and review changes to kernel build settings - https://github.com/freedomofpress/ansible-role-grsecurity-build/issues/33
- [ ] Build 4.4.132 packages with above changes and publish on apt-test - #3444 
- [x] Create QA test plan. This needs to include testing on hardware instances on older kernels, to ensure the upgrade goes smoothly. Test plan should be added to #3445.
- [ ] QA the new kernel: #3445
- [ ] Write and disseminate pre-release announcement -  #3446
- [ ] Cut the final release, including signed release tag, GitHub release object + distribution via apt.freedom.press
- [ ] Write and disseminate release announcement - #3447

**Comment by eloquence** [comment]
Release was canceled in favor of rolling these changes into 0.8.0, closing.
