### ISSUE TITLE
Release SecureDrop 0.8.0

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3512]
This is a tracking issue for the upcoming release of SecureDrop 0.8.0 - tasks may get added or modified. 

**Feature freeze:** June 12, 2018
**String freeze:** June 19, 2018
**Pre-release announcement:** June 19, 2018
**Release date:** June 26, 2018
 
_SecureDrop maintainers and testers:_ As you QA 0.8.0, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 0.8 milestone for tracking. 

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d).

# Prepare release candidate (0.8.0~rc1)
- [x] Prepare 0.8.0 release changelog - @emkll and @redshiftzero
- [x] Write and send pre-release announcement (#3513) - @eloquence 
- [x] Check for Tor stable release (`0.3.3.7` is currently on apt-test)
- [x] Prepare test plan for 0.8.0~rc1 - @emkll and @redshiftzero
- [x] Branch `release/0.8` off `develop` - @redshiftzero
- [x] Build debs and put up `0.8.0~rc1` on test apt server - @emkll 

# **[QA Matrix for SecureDrop 0.8.0](https://docs.google.com/spreadsheets/d/1Ga7QZ6GWbjLoQNjNSYj7nMqBj_grZMaQRNNYK_gVY2Y/edit#gid=652784916)**

After each test, please update the QA matrix and post details for Basic Server Testing, Application Acceptance Testing and 0.8.0-specific testing below.

# Final release
- [x] Merge final translations
- [x] Push signed tag
- [x] Build final Debian packages for 0.8.0
- [x] Upload Debian packages (including `linux-image`, `linux-firmware`, and `tor`)
- [x] Pre-Flight: Test install (not upgrade) of 0.8.0 works w/ prod repo debs
- [x] Publish blog post about 0.8.0 Debian package release and instructions for admins

**Comment by emkll** [comment]
Please report your QA results in the comments below, including the following information:
* Fresh install or upgrade
* Whether or not the source interface is using HTTPS
* Type of hardware (or VM) used. 

# Checklist 

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report.

### Basic Server Testing

- [ ] I can access both the source and journalist interfaces
- [ ] I can SSH into both machines over Tor
- [ ] AppArmor is loaded on app
- [ ] AppArmor is loaded on mon
- [ ] Both servers are running grsec kernels
- [ ] iptables rules loaded
- [ ] OSSEC emails begin to flow after install
- [ ] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [ ] Can successfully add admin user and login

#### Administration

- [ ] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [ ] JS warning bar does not appear when using Security Slider high
- [ ] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [ ] On generate page, refreshing codename produces a new 7-word codename
- [ ] On submit page, empty submissions produce flashed message
- [ ] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [ ] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in

##### Index base cases
- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download all" works

##### Individual source page
- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete collection" and the source and docs are deleted
- [ ] You can click on a document and successfully decrypt using application private key

### 0.8.0 specific testing

When reporting the results, please specify:
Hardware
Whether or not HTTPS is used for the Source interface.

#### 4.4.135 Kernel Testing (#3494)
- [ ] Kernel test plan https://github.com/freedomofpress/securedrop/pull/3494, please update as required, specifically for harware compatibility
- [ ] `uname -r` returns 4.4.135-grsec
- [ ] All three kernels are installed.`sudo apt list --installed | grep linux-image` returns 3.14.79, 4.4.115, 4.4.135.
- [ ] Follow the new troubleshooting docs (https://docs.securedrop.org/en/latest/kernel_troubleshooting.html) to downgrade the kernel to 3.14.79
- [ ] Upgrade testing with 3.14.79 kernels. Set 3.14.79 as the `GRUB_DEFAULT` per the instructions in https://docs.securedrop.org/en/latest/kernel_troubleshooting.html . Upgrade to 0.8.0 and validate that 3.14.79 kernels boot by default.
- [ ] If using prod vms, apt-test.freedom.press is not in `/etc/apt/sources.list.d/apt_test_freedom_press.list`



#### Alembic testing

##### If you are doing an upgrade test

- [ ] When running 0.7.0, backup the instance (https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [ ] Create an account on the journalist interface and ensure you can log in.
- [ ] Submit a document as a source.
- [ ] Upgrade the VMs.
- [ ] Ensure you can still log in and see the source’s document in the journalist interface.
- [ ] Ensure the database backup is removed: /var/lib/securedrop/backups/ is empty
- [ ] Finally, try restoring the backup  (https://docs.securedrop.org/en/latest/backup_and_restore.html)


##### If you are doing a clean install test

- [ ] Install fresh and ensure you can submit a document as a source. 
- [ ] Backup and restore on 0.8.0 (https://docs.securedrop.org/en/latest/backup_and_restore.html)


#### Other 0.8.0 functionality

- [ ] A TOTP token is no longer required to connect to the console (#3507)
- [ ] Journalist notifications are properly sent every 24h (#3479)
- [ ] `tor --version` returns 0.3.3.7 and all tor hidden services work properly (#3518)

**Comment by emkll** [comment]
# 0.7.0 w/ 3.14.79 -> 0.8.0 upgrade, Mac mini with HTTPS on source interface (In progress)

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in

##### Index base cases
- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download all" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [ ] Clicking "Delete collection" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### 0.8.0 specific testing

When reporting the results, please specify:
Hardware
Whether or not HTTPS is used for the Source interface.

#### 4.4.135 Kernel Testing (#3494)
- [x] Kernel test plan https://github.com/freedomofpress/securedrop/pull/3494, please update as required, specifically for harware compatibility
- [x] `uname -r` returns 4.4.135-grsec
- [x] All three kernels are installed.`sudo apt list --installed | grep linux-image` returns 3.14.79, 4.4.115, 4.4.135.
- [x] Follow the new troubleshooting docs (https://docs.securedrop.org/en/latest/kernel_troubleshooting.html) to downgrade the kernel to 3.14.79
- [x] Upgrade testing with 3.14.79 kernels. Set 3.14.79 as the `GRUB_DEFAULT` per the instructions in https://docs.securedrop.org/en/latest/kernel_troubleshooting.html . Upgrade to 0.8.0 and validate that 3.14.79 kernels boot by default.
- [x] If using prod vms, apt-test.freedom.press is not in `/etc/apt/sources.list.d/apt_test_freedom_press.list`



#### Alembic testing

##### If you are doing an upgrade test

- [ ] When running 0.7.0, backup the instance (https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [ ] Create an account on the journalist interface and ensure you can log in.
- [ ] Submit a document as a source.
- [ ] Upgrade the VMs.
- [ ] Ensure you can still log in and see the source’s document in the journalist interface.
- [ ] Ensure the database backup is removed: /var/lib/securedrop/backups/ is empty
- [ ] Finally, try restoring the backup  (https://docs.securedrop.org/en/latest/backup_and_restore.html)


##### If you are doing a clean install test

- [ ] Install fresh and ensure you can submit a document as a source. 
- [ ] Backup and restore on 0.8.0 (https://docs.securedrop.org/en/latest/backup_and_restore.html)


#### Other 0.8.0 functionality

- [x] A TOTP token is no longer required to connect to the console (#3507)
- [ ] Journalist notifications are properly sent every 24h (#3479)
- [x] `tor --version` returns 0.3.3.7 and all tor hidden services work properly (#3518)

**Comment by redshiftzero** [comment]
#  0.8.0~rc1 fresh install in VMs

**Hardware:** VMs
**Whether or not HTTPS is used for the Source interface:** No HTTPS

## Basic Server Testing

 - [x] I can access both the source and journalist interfaces
 - [x] I can SSH into both machines over Tor
 - [x] AppArmor is loaded on app
 - [x] AppArmor is loaded on mon
 - [x] Both servers are running grsec kernels 
 - [x] iptables rules loaded on both servers
 - [x] OSSEC emails begin to flow after install
 - [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

## Command Line User Generation

- [x] Can successfully add admin user and login

## Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html

# 0.8.0 specific testing

## 4.4.135 Kernel Testing (#3494)

 - [x] uname -r returns 4.4.135-grsec
 - [x] All three kernels are installed.sudo apt list --installed | grep linux-image returns 3.14.79, 4.4.115, 4.4.135.
 - [ ] Follow the new troubleshooting docs (https://docs.securedrop.org/en/latest/kernel_troubleshooting.html) to downgrade the kernel to 3.14.79 - did not test
 - [ ]  If using prod vms, apt-test.freedom.press is not in /etc/apt/sources.list.d/apt_test_freedom_press.list - I manually overrode this due to force of habit

## Alembic testing

 - [x] Install fresh and ensure you can submit a document as a source.
 - [x] Backup and restore on 0.8.0 (https://docs.securedrop.org/en/latest/backup_and_restore.html)

## Other 0.8.0 functionality

 - [x] A TOTP token is no longer required to connect to the console (#3507)
 - [ ] Journalist notifications are properly sent every 24h (#3479) - will test this on my hardware instance due to needing to keep a long running server up
 - [x] tor --version returns 0.3.3.7 and all tor hidden services work properly (#3518)

**Comment by conorsch** [comment]
#  0.8.0~rc1 fresh install on Gigabyte Brix

Credit goes to @edenemmanuel for the meticulous setup here, I'm just stepping in to run through the checklist. Skipping the application acceptance testing, since the focus was to validate hardware support, particularly with the kernel version bump. 

**Hardware:** Gigabyte Brix
**Whether or not HTTPS is used for the Source interface:** No HTTPS

## Basic Server Testing

 - [x] I can access both the source and journalist interfaces
 - [x] I can SSH into both machines over Tor
 - [x] AppArmor is loaded on app
 - [x] AppArmor is loaded on mon
 - [x] Both servers are running grsec kernels 
 - [x] iptables rules loaded on both servers
 - [x] OSSEC emails begin to flow after install
 - [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

## Command Line User Generation

- [x] Can successfully add admin user and login

## Administration

- [ ] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
 * did not test, will make sure to do so on next hardware install, for rolled-back instances

# 0.8.0 specific testing

## 4.4.135 Kernel Testing (#3494)

 - [x] uname -r returns 4.4.135-grsec
 - [x] All three kernels are installed.sudo apt list --installed | grep linux-image returns 3.14.79, 4.4.115, 4.4.135.
 - [ ] Follow the new troubleshooting docs (https://docs.securedrop.org/en/latest/kernel_troubleshooting.html) to downgrade the kernel to 3.14.79
   * did not test, will do so on other hardware as part of rollback kernel testing
 - [ ]  If using prod vms, apt-test.freedom.press is not in /etc/apt/sources.list.d/apt_test_freedom_press.list
   * N/A, since this was a pre-release QA testing, so installed 0.8.0~rc1 from apt-test

## Alembic testing

 - [x] Install fresh and ensure you can submit a document as a source.
 - [ ] Backup and restore on 0.8.0 (https://docs.securedrop.org/en/latest/backup_and_restore.html)
   * did not test, will make sure to do so on next hardware install, for rolled-back instances

## Other 0.8.0 functionality

 - [x] A TOTP token is no longer required to connect to the console (#3507)
 - [ ] Journalist notifications are properly sent every 24h (#3479)
   * did not test, will make sure to do so on next hardware install, for rolled-back instances
 - [x] tor --version returns 0.3.3.7 and all tor hidden services work properly (#3518)

**Comment by msheiny** [comment]
#  0.8.0~rc2 upgrade testing with 3.14 kernel hold-back on HW

**Hardware:** NUCs
**Whether or not HTTPS is used for the Source interface:** No HTTPS

#### 4.4.135 Kernel Testing (#3494)
- [ ] Kernel test plan https://github.com/freedomofpress/securedrop/pull/3494, please update as required, specifically for harware compatibility
- [ ] `uname -r` returns 4.4.135-grsec
- [x] All three kernels are installed.`sudo apt list --installed | grep linux-image` returns 3.14.79, 4.4.115, 4.4.135.
- [x] Follow the new troubleshooting docs (https://docs.securedrop.org/en/latest/kernel_troubleshooting.html) to downgrade the kernel to 3.14.79
- [x] Upgrade testing with 3.14.79 kernels. Set 3.14.79 as the `GRUB_DEFAULT` per the instructions in https://docs.securedrop.org/en/latest/kernel_troubleshooting.html . Upgrade to 0.8.0 and validate that 3.14.79 kernels boot by default.
- [x] If using prod vms, apt-test.freedom.press is not in `/etc/apt/sources.list.d/apt_test_freedom_press.list`

#### Alembic testing

##### If you are doing an upgrade test

- [ ] When running 0.7.0, backup the instance (https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [ ] Run the QA data loader: https://docs.securedrop.org/en/latest/development/database_migrations.html#release-testing-migrations
- [ ] Create an account on the journalist interface and ensure you can log in.
- [ ] Submit a document as a source.
- [ ] Upgrade the VMs.
- [ ] Ensure you can still log in and see the source’s document in the journalist interface.
- [ ] Ensure the database backup is removed: /var/lib/securedrop/backups/ is empty
- [ ] Finally, try restoring the backup  (https://docs.securedrop.org/en/latest/backup_and_restore.html)

#### Other 0.8.0 functionality

- [ ] A TOTP token is no longer required to connect to the console (#3507)
- [ ] Journalist notifications are properly sent every 24h (#3479)
- [x] `tor --version` returns 0.3.3.7 and all tor hidden services work properly (#3518)

**Comment by conorsch** [comment]
#  0.8.0~rc2 rolled back upgrade test on 1U servers

**Hardware:** HP Proliant DL385 G7 & PowerEdge R620
**Whether or not HTTPS is used for the Source interface:** No HTTPS

## Basic Server Testing

 - [x] I can access both the source and journalist interfaces
 - [x] I can SSH into both machines over Tor
 - [x] AppArmor is loaded on app
 - [x] AppArmor is loaded on mon
 - [x] Both servers are running grsec kernels 
 - [x] iptables rules loaded on both servers
 - [x] OSSEC emails begin to flow after install
 - [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

## Command Line User Generation

- [x] Can successfully add admin user and login

## Administration

- [ ] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
 * did not test, will make sure to do so on next hardware install, for rolled-back instances

# 0.8.0 specific testing

## 4.4.135 Kernel Testing (#3494)

 - [x] uname -r returns 4.4.135-grsec
 - [x] All three kernels are installed.sudo apt list --installed | grep linux-image returns 3.14.79, 4.4.115, 4.4.135.
 - [x] Follow the new troubleshooting docs (https://docs.securedrop.org/en/latest/kernel_troubleshooting.html) to downgrade the kernel to 3.14.79
 - [ ]  If using prod vms, apt-test.freedom.press is not in /etc/apt/sources.list.d/apt_test_freedom_press.list
   * N/A, since this was a pre-release QA testing, so installed 0.8.0~rc2 from apt-test

## Alembic testing

 - [x] Install fresh and ensure you can submit a document as a source.
 - [ ] Backup and restore on 0.8.0 (https://docs.securedrop.org/en/latest/backup_and_restore.html)
   * did not test, leaving that for fresh install on same hardware

## Other 0.8.0 functionality

 - [x] A TOTP token is no longer required to connect to the console (#3507)
 - [ ] Journalist notifications are properly sent every 24h (#3479)
   * did not test, leaving for fresh install test on same hardware
 - [x] tor --version returns 0.3.3.7 and all tor hidden services work properly (#3518)

**Comment by redshiftzero** [comment]
# 0.7.0 w/ 4.4.115 kernel-> 0.8.0~rc2 upgrade

**Hardware:** Mac minis
**HTTPS is used for the Source interface:** Yes, self-signed cert (and verified successful submission of document

## Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

## Command Line User Generation

- [x] Can successfully add admin user and login

## Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html (done on 0.7.0->0.8.0)

## 0.8.0 specific testing

### 4.4.135 Kernel Testing (#3494)

- [x] uname -r returns 4.4.135-grsec
- [x] All three kernels are installed.sudo apt list --installed | grep linux-image returns 3.14.79, 4.4.115, 4.4.135.

### Alembic testing

- [x] When running 0.7.0, backup the instance (https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] Create an account on the journalist interface and ensure you can log in.
- [x] Submit a document as a source.
- [x] Upgrade the VMs.
- [x] Ensure you can still log in and see the source’s document in the journalist interface.
- [x] Ensure the database backup is removed: /var/lib/securedrop/backups/ is empty
- [x] Finally, try restoring the backup (https://docs.securedrop.org/en/latest/backup_and_restore.html)

### Other 0.8.0 functionality

- [ ] A TOTP token is no longer required to connect to the console (#3507) - TO DO
- [ ] Journalist notifications are properly sent every 24h (#3479) - TO DO
- [x] tor --version returns 0.3.3.7 and all tor hidden services work properly (#3518)

**Comment by conorsch** [comment]
See notes in the [testing matrix](https://docs.google.com/spreadsheets/d/1Ga7QZ6GWbjLoQNjNSYj7nMqBj_grZMaQRNNYK_gVY2Y/edit#gid=652784916), related to the rolled back upgrade test above. Notably the PowerEdge was still showing Spectre problems. I assume that a BIOS update would resolve, but have not tried this to confirm. The new kernel was stable, so I don't view this as a release blocker, but something we should keep an eye on.

**Comment by emkll** [comment]
@conorsch the current 4.4.135 rc kernel should be not vulnerable to the following:
* CVE-2017-5373 (Spectre v1): 
* CVE-2017-5715 (Spectre v2)
* CVE-2017-5754 (Meltdown/Spectre v3)

Mitigations for the following should not yet be present:
* CVE 2018-3640 (Spectre v3a)
* CVE 2018-3639 (Spectre v4)

Given incomplete upstream mitigations and lack of QA time, I suggest we wait until the next release to address these (noting that an attacker would need code execution on the machine to exploit these)
* Spectre v3a requires firmware update or setting the `spec_store_bypass_disable` option.
* Spectre v4 requires firmware update and Kernel SSBD support has not yet been backported to 4.4. However, our kernel hardening configuration (`GRKERNSEC_BPF_HARDEN=y`) should provide mitigations against this attack.

**Comment by kushaldas** [comment]
#  0.8.0~rc3 update in VMs

**Hardware:** VMs
**Whether or not HTTPS is used for the Source interface:** No HTTPS

## Basic Server Testing

 - [x] I can access both the source and journalist interfaces
 - [x] I can SSH into both machines over Tor
 - [x] AppArmor is loaded on app
 - [x] AppArmor is loaded on mon
 - [x] Both servers are running grsec kernels 
 - [x] iptables rules loaded on both servers
 - [x] OSSEC emails begin to flow after install
 - [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download all" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete collection" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key



# 0.8.0 specific testing

## 4.4.135 Kernel Testing (#3494)

 - [x] uname -r returns 4.4.135-grsec
 - [x] All three kernels are installed.sudo apt list --installed | grep linux-image returns 3.14.79, 4.4.115, 4.4.135.
 - [ ] Follow the new troubleshooting docs (https://docs.securedrop.org/en/latest/kernel_troubleshooting.html) to downgrade the kernel to 3.14.79 - did not test
 - [x]  If using prod vms, apt-test.freedom.press is not in /etc/apt/sources.list.d/apt_test_freedom_press.list 

## Alembic testing

 - [x] Install fresh and ensure you can submit a document as a source.
 - [x] Backup and restore on 0.8.0 (https://docs.securedrop.org/en/latest/backup_and_restore.html)

## Other 0.8.0 functionality

 - [x] A TOTP token is no longer required to connect to the console (#3507)
 - [ ] Journalist notifications are properly sent every 24h (#3479) - will take 24 hours :D 
 - [x] tor --version returns 0.3.3.7 and all tor hidden services work properly (#3518)

**Comment by eloquence** [comment]
Done: https://securedrop.org/news/securedrop-080-released/
