### ISSUE TITLE
Review and update hardware recommendations

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#3826]
We provide [hardware recommendations](https://docs.securedrop.org/en/stable/hardware.html#specific-hardware-recommendations) in our docs. There are a couple of problems with the current docs, plus likely more nor yet identified:

- The recommended Gigabyte BRIX (BXi5-5575) is out of stock with most retailers.
- The Intel NUC5i5MYHE is also starting to get long in the tooth; the most current models are 8th gen.
- We don't yet provide a 1U recommendation that would make sense for some larger news organizations with standard server management and procurement practices.

We should carefully review and update these recommendations. This breaks down into a few sub-tasks, e.g.:

- [x] Test 7th generation NUC and attempt to remediate any issues, e.g., with our grsec kernel
- [x] Add warning regarding latest generation Mac Minis (which don't work with Ubuntu without major effort)
- [x] Remove Gigabyte BRIX from recommendations. There's no compelling reason to continue to recommend this model as we already have a small form factor recommendation.
- [ ] Update docs to 7th generation NUCs as our standard recommendation
- [ ] Update docs to include instructions for disabling wireless in the BIOS
- [ ] Procure any desired 1U models to test against, in addition to the ones we already use during QA
- [ ] Based on common hardware choices, internal testing and product lifecycle, add a 1U recommendation

**Comment by eloquence** [comment]
For the 11/28-12/12 sprint period, @zenmonkeykstop will tackle the first items in this list: testing the 7th gen NUC and adding a warning regarding the latest Mac Minis.

**Comment by zenmonkeykstop** [comment]
Progress today:
- acquired Intel nuc7i5bnh, 8GB RAM, 250 GB SSD
- disassembled, confirmed wifi is soldered on motherboard, reassembled with antennae disconnected
- updated BIOS, attempted 14.04.5 install. Install fails when trying to detect network devices
- dropped to shell, confirmed no sign of ethernet controller
- attempted 14.04.5 install with generic USB Ethernet dongle. Installation proceeded without issues
- reviewed instructions for installing Intel's e1000e driver after OS installation.

**Comment by eloquence** [comment]
For the 12/12-12/21 sprint, @zenmonkeykstop has committed to do additional testing of the nuc7i5bnh to determine whether it will install cleanly on 14.04 with the e1000e driver. 

If it does, building a custom 14.04 kernel with this driver included may be the next step.

**Comment by zenmonkeykstop** [comment]
Confirmed that building the latest version (3.4.2.1) of the e1000e driver on 14.04.5 post-install gives a working module (modulo a warning about tainted kernels in dmesg).

**Comment by eloquence** [comment]
For the 1/9-1/23 sprint, we've committed to removing the BRIC from the recommendations; Kev and Mickael will also do more time-boxed work towards getting the e1000e driver into the next kernel (#4024).

**Comment by eloquence** [comment]
Just a note that now that we support the 7th gen NUCs, we should update this section in the docs:

> Later NUC revisions (the NUC7 and NUC8 series) typically include onboard WiFi and Bluetooth, and may use an Ethernet chipset not supported by SecureDrop’s custom kernel. We are investigating workarounds for both issues. If you are having trouble sourcing the NUC5i5MYHE, please contact us for more information on how to safely configure and use more recent NUCs.

**Comment by eloquence** [comment]
Pulling docs update to 7th gen NUCs into the current sprint, so it'll make it into 0.13.0 branch of the docs.
