### ISSUE TITLE
Release SecureDrop 0.10.0

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3849]
This is a tracking issue for the upcoming release of SecureDrop 0.10.0 - tasks may get added or modified. 

**Feature freeze:** October 9, 2018
**String freeze:** October 16, 2018
**Pre-release announcement:** October 16, 2018
**Release date:** October 23, 2018
 
_SecureDrop maintainers and testers:_ As you QA 0.10.0, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 0.10.0 milestone for tracking (or ask a maintainer to do so). 

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d).

# Prepare release candidate (0.10.0~rc1)
- [x] Prepare 0.10.0-rc1 release changelog - @redshiftzero 
- [x] Branch off 0.10.0~rc1 into release/0.10.0 - @redshiftzero
- [skipped] Build debs (including new Tor package) and put up `0.10.0~rc1` on test apt server

We merged in two important fixes prior to building debs for `rc1` so stopped here 

# Prepare release candidate (0.10.0~rc2)
- [x] Prepare 0.10.0-rc2 release changelog - @redshiftzero 
- [x] Prepare test plan for 0.10.0~rc2 - @zenmonkeykstop and @redshiftzero
- [x] Push 0.10.0-rc2 tag - @redshiftzero
- [x] Build debs (including new Tor package) and put up `0.10.0~rc2` on test apt server - @emkll

# Prepare release candidate (0.10.0~rc3)
- [x] Prepare 0.10.0-rc3 release changelog - @redshiftzero 
- [x] Prepare test plan for 0.10.0~rc3 - @emkll 
- [x] Push 0.10.0-rc3 tag - @redshiftzero
- [x] Build debs and put up `0.10.0~rc3` on test apt server - @emkll

# Prepare release candidate (0.10.0~rc4)
- [x] Prepare 0.10.0-rc4 release changelog - @redshiftzero 
- [x] Prepare test plan for 0.10.0~rc4 @zenmonkeykstop @emkll 
- [x] Push 0.10.0-rc4 tag - @redshiftzero
- [x] Build debs and put up `0.10.0~rc4` on test apt server - @emkll

[we will add checklists for rc5 release candidates and later as we proceed through the release process]

Test plan to be posted during business hours Pacific time on Wednesday, October 10th.

# [QA Matrix for 0.10.0](https://docs.google.com/spreadsheets/d/1IdW1DITWBvacU-eNp2IlJJdosEuYr4XTWiplQeJu-Lw/edit#gid=0)

# [Test Plan for 0.10.0](https://github.com/freedomofpress/securedrop/wiki/0.10.0-Test-Plan)

After each test, please update the QA matrix and post details for Basic Server Testing, Application Acceptance Testing and 0.10.0-specific testing below in comments to this ticket.

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image - @emkll or @msheiny 
- [x] Merge final translations - @kushaldas 
- [x] Push signed tag - @redshiftzero 
- [x] Build final Debian packages for 0.10.0 - @conorsch 
- [x] Upload Debian packages (including new `linux-image`, `linux-firmware`, and `tor` packages) to apt test - @conorsch 
- [x] Pre-Flight: Test install and upgrade of 0.10.0 works w/ prod repo debs, test updater logic in Tails - @zenmonkeykstop 
- [x] Write and send release announcement - @eloquence 
- [x] Publish blog post about 0.10.0 Debian package release and instructions for admins - @eloquence 

# Post release

- [ ] Merge changelog (i.e. rc commits) back to `develop` - @redshiftzero 
- [ ] Bump version on `develop` in prep for 0.11.0 release - @redshiftzero

**Comment by zenmonkeykstop** [comment]
Note to self (and others wishing to test upgrade path on HW) - ansible playbook to set instance up to use apt-test. instead of apt. is here: 
https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d

**Comment by zenmonkeykstop** [comment]
## 0.10.0 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.10.0 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.10.0-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: prod VMs
- Tails version: 3.9.1
- Test Scenario: Clean install
- SSH over Tor: enabled
- Release candidate: 0.10.0~rc2  

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app 
- [x] AppArmor is loaded on mon 
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [ ] OSSEC emails begin to flow after install **NOT TESTED**
- [ ] OSSEC emails are decrypted to correct key and I am able to decrypt them **NOT TESTED**

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [ ] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html **FAILED**
- [ ] If doing upgrade testing, make a backup on 0.9.x and restore this backup on 0.10.0. Confirm that  no further action is necessary and that (#3737) worked correctly. **N/A**

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download all" works *There is no Download all*

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete collection" and the source and docs are deleted *it's Delete Source And Submissions*
- [ ] You can click on a document and successfully decrypt using application private key **NOT TESTED**`

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot **FAILED** *~/Persistent/securedrop not mounted on boot in Tails VM* 
- [ ] Updating occurs without issue **FAILED**

### 0.10.0-specific changes

- [x] OSSEC agent and server is 3.0.0 (#3701)
    - [ ] Upgrade test: ensure that OSSEC alerts continue to flow after upgrade
    - [ ] Fresh install: ensure that OSSEC alerts flow without issue
- [ ] Tor is running 0.3.4.8 (#3813) **FAILED**
- [ ] \(Upgrade only\) Latest kernel version is selected for boot on a previously downgraded instance (#3857)

## Preflight

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.10.0
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.10.0
- [ ] After reboot, updater GUI no longer appears

**Comment by zenmonkeykstop** [comment]
## 0.10.0 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.10.0 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.10.0-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: 2014 Mac Mini
- Tails version: 3.9.1
- Test Scenario: clean install
- SSH over Tor: enabled
- Release candidate: 0.10.0-rc2
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [ ] If doing upgrade testing, make a backup on 0.9.x and restore this backup on 0.10.0. Confirm that  no further action is necessary and that (#3737) worked correctly.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot
- [x] Updating occurs without issue *after ensuring there were no staged changes*

### 0.10.0-specific changes

- [x] OSSEC agent and server is 3.0.0 (#3701)
    - [ ] Upgrade test: ensure that OSSEC alerts continue to flow after upgrade
    - [x] Fresh install: ensure that OSSEC alerts flow without issue
- [ ] \(Upgrade only\) Latest kernel version is selected for boot on a previously downgraded instance (#3857)

## Preflight

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.10.0
- [ ] A message can be successfully submitted

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.10.0
- [ ] After reboot, updater GUI no longer appears

**Comment by emkll** [comment]
## 0.10.0 QA Checklist

### Environment

- Install target: Intel NUC5PYH
- Tails version: 3.9
- Test Scenario: clean install
- SSH over Tor: disabled
- Release candidate: 0.10.0-rc2

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [ ] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [ ] If doing upgrade testing, make a backup on 0.9.x and restore this backup on 0.10.0. Confirm that  no further action is necessary and that (#3737) worked correctly.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot
- [ ] Updating occurs without issue *after ensuring there were no staged changes*

### 0.10.0-specific changes

- [x] OSSEC agent and server is 3.0.0 (#3701)
    - [ ] Upgrade test: ensure that OSSEC alerts continue to flow after upgrade
    - [x] Fresh install: ensure that OSSEC alerts flow without issue
- [ ] \(Upgrade only\) Latest kernel version is selected for boot on a previously downgraded instance (#3857)

**Comment by robzim** [comment]
Guys, I’m thinking this is an indication that SecureDrop 0.10 will ship soon.
Rob

**Comment by zenmonkeykstop** [comment]
@robzim :crossed_fingers:

**Comment by zenmonkeykstop** [comment]
## 0.10.0 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.10.0 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.10.0-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: 2014 Mac Minis
- Tails version: 3.9.1
- Test Scenario: 0.9.1->0.10.0 upgrade
- SSH over Tor: enabled
- Release candidate: 0.10.0~rc2
- General notes: app and mon downgraded to 3.14.79 before upgrade

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [x] If doing upgrade testing, make a backup on 0.9.x and restore this backup on 0.10.0. Confirm that  no further action is necessary and that (#3737) worked correctly.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot
- [x] Updating occurs without issue

### 0.10.0-specific changes

- [x] OSSEC agent and server is 3.0.0 (#3701)
    - [x] Upgrade test: ensure that OSSEC alerts continue to flow after upgrade
    - [ ] Fresh install: ensure that OSSEC alerts flow without issue
- [x] \(Upgrade only\) Latest kernel version is selected for boot on a previously downgraded instance (#3857)

## Preflight

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.10.0
- [ ] A message can be successfully submitted

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.10.0
- [ ] After reboot, updater GUI no longer appears

**Comment by zenmonkeykstop** [comment]
## 0.10.0 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.10.0 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.10.0-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: Intel NUCs
- Tails version: 3.9.1
- Test Scenario: upgrade from 0.9.1
- SSH over Tor: enabled
- Release candidate: 0.10.0~rc3
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [x] If doing upgrade testing, make a backup on 0.9.x and restore this backup on 0.10.0. Confirm that  no further action is necessary and that (#3737) worked correctly.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot 
- [x] Updating occurs without issue

### 0.10.0-specific changes

- [x] OSSEC agent and server is 3.0.0 (#3701)
    - [x] Upgrade test: ensure that OSSEC alerts continue to flow after upgrade
    - [ ] Fresh install: ensure that OSSEC alerts flow without issue
- [x] \(Upgrade only\) Latest kernel version is selected for boot on a previously downgraded instance (#3857)

#### 0.10.0-rc3-specific changes

- [x] OSSEC emails do not contain alert type (see https://github.com/freedomofpress/securedrop/issues/3882)

## Preflight

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.10.0
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.10.0
- [ ] After reboot, updater GUI no longer appears

**Comment by emkll** [comment]
## 0.10.0-rc4 (In Progress)
### Environment

- Install target: NUC 5PYH
- Tails version: 3.9
- Test Scenario: Upgrade from 0.9.1
- SSH over Tor: Yes
- Release candidate: rc4
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [ ] Can successfully add admin user and login

#### Administration

- [ ] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [ ] If doing upgrade testing, make a backup on 0.9.x and restore this backup on 0.10.0. Confirm that  no further action is necessary and that (#3737) worked correctly.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [ ] JS warning bar does not appear when using Security Slider high
- [ ] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [ ] On generate page, refreshing codename produces a new 7-word codename
- [ ] On submit page, empty submissions produce flashed message
- [ ] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [ ] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in

##### Index base cases
- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download" works

##### Individual source page
- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [ ] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot 
- [ ] Updating occurs without issue

### 0.10.0-specific changes

- [ ] OSSEC agent and server is 3.0.0 (#3701)
    - [ ] Upgrade test: ensure that OSSEC alerts continue to flow after upgrade
    - [ ] Fresh install: ensure that OSSEC alerts flow without issue
- [ ] \(Upgrade only\) Latest kernel version is selected for boot on a previously downgraded instance (#3857)

#### 0.10.0-rc3-specific changes

- [ ] OSSEC emails do not contain alert type (see https://github.com/freedomofpress/securedrop/issues/3882)

#### 0.10.0-rc4-specific changes

- [ ] Ensure a source cannot delete a journalist reply for which they are not authorized (see https://github.com/freedomofpress/securedrop/pull/3893)
## Preflight

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.10.0
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.10.0
- [ ] After reboot, updater GUI no longer appears

**Comment by zenmonkeykstop** [comment]
## 0.10.0 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.10.0 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.10.0-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: 2014 Mac Mini
- Tails version: 3.9.1
- Test Scenario: upgrade from 0.9.1
- SSH over Tor: enabled
- Release candidate: 0.10.0-rc4
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
- [x] AppArmor is loaded on mon
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [x] If doing upgrade testing, make a backup on 0.9.x and restore this backup on 0.10.0. Confirm that  no further action is necessary and that (#3737) worked correctly.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot 
- [x] Updating occurs without issue

### 0.10.0-specific changes

- [x] OSSEC agent and server is 3.0.0 (#3701)
    - [x] Upgrade test: ensure that OSSEC alerts continue to flow after upgrade
    - [ ] Fresh install: ensure that OSSEC alerts flow without issue
- [x] \(Upgrade only\) Latest kernel version is selected for boot on a previously downgraded instance (#3857)

#### 0.10.0-rc3-specific changes

- [x] OSSEC emails do not contain alert type (see https://github.com/freedomofpress/securedrop/issues/3882)

#### 0.10.0-rc4-specific changes

- [x] Ensure a source cannot delete a journalist reply for which they are not authorized (see https://github.com/freedomofpress/securedrop/pull/3893)
## Preflight

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.10.0
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.10.0
- [ ] After reboot, updater GUI no longer appears
