### ISSUE TITLE
Make Xenial development/CI environments the default

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4155]
## Description

New installs beginning with 0.12.0 will be done on Xenial. Xenial will become the primary base OS for SecureDrop, and we will deprecate support for Trusty when it EOLs in April. We should thus:

- [x] Make the default CI staging job that is run per-PR xenial (#4158)
- [x] Make the trusty CI staging job run nightly (#4158)
- [x] Rename the makefile targets that are `staging-xenial` and `test-xenial` just `staging` and `test` (renaming the existing `staging` to `staging-trusty` so that we keep them around to ensure we don't break anything for installs that have yet to migrate) (#4224)
- [x] Make `BASE_OS` default be `xenial` instead of `trusty` in the securedrop application Makefile (#4213)
- [x] Update and test Qubes staging setup docs on Xenial base OS (dev only)
- [x] Update Vagrantfile to use Xenial instead of Trusty (probably only used for Prod VMs at this point) (#4213)
- [x] Port "upgrade" scenario to Xenial, so VM upgrade testing can be performed on Xenial by default (#4237)
- [x] Update default staging target to Xenial (#4310)

**Comment by redshiftzero** [comment]
everything here was done, anything we forgot should get a new dedicated issue
