### ISSUE TITLE
Release SecureDrop 0.12.1

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#4260]
This is a tracking issue for the upcoming release of SecureDrop 0.12.1 - tasks may get added or modified. 

**Feature freeze:** EOD Pacific time, Thursday, March 14
**String freeze:** N/A -  no string changes this release
**Pre-release announcement:** N/A - point releases will not have pre-release announcements
**Release date:** EOD Pacific time, Tuesday, March 19

**Release manager:** @heartsucker
**Deputy release manager:** @zenmonkeykstop 
 
_SecureDrop maintainers and testers:_ As you QA 0.12.0, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 0.12.0 milestone for tracking (or ask a maintainer to do so). 

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d).

# Prepare release candidate (0.12.1~rc1)
- [x] Prepare 0.12.1-rc1 release changelog - @heartsucker 
- [x] Branch off release/0.12.0 into release/0.12.1 - @heartsucker 
- [x] Build debs (including new Tor package) and put up `0.12.1~rc1` on test apt server - @zenmonkeykstop 

# [QA Matrix for 0.12.1](https://docs.google.com/spreadsheets/d/1DyY-3vWk56x1NNdHHSyn1UcSGLhd1-5pvrJ8lP7PyTA/edit#gid=0)

# [Test Plan for 0.12.1](https://github.com/freedomofpress/securedrop/wiki/0.12.1-Test-Plan)

After each test, please update the QA matrix and post details for Basic Server Testing, Application Acceptance Testing and 0.12.0-specific testing below in comments to this ticket.

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image - @emkll
- [x] Push signed tag - @redshiftzero 
- [x] Build final Debian packages for 0.12.1 (including Tor packages) - @conorsch 
- [x] Upload Debian packages to apt-qa - @conorsch 
- [x] Pre-Flight: Test install and upgrade (both cron-apt on Trusty, and Ansible on Xenial) of 0.12.1 works w/ prod repo debs - @zenmonkeykstop, @emkll 
- [x] Prepare and distribute release messaging - @eloquence - #4273 

# Post release

- [x] Merge changelog back to `develop` - @emkll https://github.com/freedomofpress/securedrop/pull/4285
- [x] Update upgrade testing boxes - @conorsch https://github.com/freedomofpress/securedrop/pull/4291
- [x] Update roadmap wiki page -

**Comment by zenmonkeykstop** [comment]
# QA plan
- NUCs
- Mac Minis
- 1U servers in SF

## 0.12.1 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.12.1 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.12.1-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: 2014 Mac Mini
- Tails version: 3.12.1
- Test scenario: cron-apt upgrade against Xenial install
- Server locale setting: Norwegian
- SSH over Tor: enabled
- Release candidate: 0.12.1-rc1
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1G475HDi8dCEXL4YUma4jT8h1-6P9-6jRT56DfDye4u4/edit#gid=0) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [x] If doing upgrade testing, make a backup on 0.12.0 and restore this backup on 0.12.1

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [ ] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot 
- [x] ([#4100](https://github.com/freedomofpress/securedrop/issues/4100)) Updating occurs without issue

### 0.12.1-specific changes

- [x] ([#4170](https://github.com/freedomofpress/securedrop/issues/4170)) Tor version is 0.3.4.11 on Trusty or 0.3.5.8 on Xenial
- [x] ([#4219](https://github.com/freedomofpress/securedrop/issues/4219)) If non-English locale set during OS install, `./securedrop-admin install` completes successfully
- [x] ([#4221](https://github.com/freedomofpress/securedrop/issues/4221))
  - [x] `tmux` session is started/reconnected after SSH to `app` and `mon`.
  - [ ] If testing Xenial upgrade-in-place, `tmux` session reconnects successfully after tor and sshd restarts
- [x] ([#4163](https://github.com/freedomofpress/securedrop/issues/4163)) The following packages are not installed on app or mon: `libiw30`, `wpasupplicant`, `wirelesstools`.
- [x] ([#4208](https://github.com/freedomofpress/securedrop/issues/4208)) The NoScript info page on the Source Interface includes a link back to the submissions page.


### Preflight 

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.12.1
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.12.1
- [ ] After reboot, updater GUI no longer appears

**Comment by kushaldas** [comment]
### Environment

- Install target: vm
- Tails version: 3.12.1
- Test scenario:
- Server locale setting: (choose non-English to test #4219)
- SSH over Tor: No
- Release candidate: rc1
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1DyY-3vWk56x1NNdHHSyn1UcSGLhd1-5pvrJ8lP7PyTA/edit#gid=0) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [ ] If doing upgrade testing, make a backup on 0.12.0 and restore this backup on 0.12.1

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot 
- [ ] ([#4100](https://github.com/freedomofpress/securedrop/issues/4100)) Updating occurs without issue

### 0.12.1-specific changes

- [x] ([#4170](https://github.com/freedomofpress/securedrop/issues/4170)) Tor version is 0.3.4.11 on Trusty or 0.3.5.8 on Xenial
- [ ] ([#4219](https://github.com/freedomofpress/securedrop/issues/4219)) If non-English locale set during OS install, `./securedrop-admin install` completes successfully
- [ ] ([#4221](https://github.com/freedomofpress/securedrop/issues/4221))
  - [ ] `tmux` session is started/reconnected after SSH to `app` and `mon`.
  - [ ] If testing Xenial upgrade-in-place, `tmux` session reconnects successfully after tor and sshd restarts
- [ ] :fire:  :fire:  ([#4163](https://github.com/freedomofpress/securedrop/issues/4163)) The following packages are not installed on app or mon: `libiw30`, `wpasupplicant`, `wirelesstools`.
- [x] ([#4208](https://github.com/freedomofpress/securedrop/issues/4208)) The NoScript info page on the Source Interface includes a link back to the submissions page.

```
vagrant@app-prod:~$ dpkg -l | grep wpasupplicant
ii  wpasupplicant                      2.4-0ubuntu6.3                                       amd64        client support for WPA and WPA2 (IEEE 802.11i)
vagrant@app-prod:~$ dpkg -l | grep libiw30
ii  libiw30:amd64                      30~pre9-8ubuntu1                                     amd64        Wireless tools - library
```

**Comment by kushaldas** [comment]
### Environment

- Install target: NUC upgraded from Trusty
- Tails version: 3.12.1
- Test scenario:
- Server locale setting: fr_FR.UTF-8
- SSH over Tor: No
- Release candidate: rc1
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1DyY-3vWk56x1NNdHHSyn1UcSGLhd1-5pvrJ8lP7PyTA/edit#gid=0) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [x] If doing upgrade testing, make a backup on 0.12.0 and restore this backup on 0.12.1

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot 
- [ ] ([#4100](https://github.com/freedomofpress/securedrop/issues/4100)) Updating occurs without issue

### 0.12.1-specific changes

- [x] ([#4170](https://github.com/freedomofpress/securedrop/issues/4170)) Tor version is 0.3.4.11 on Trusty or 0.3.5.8 on Xenial
- [x] ([#4219](https://github.com/freedomofpress/securedrop/issues/4219)) If non-English locale set during OS install, `./securedrop-admin install` completes successfully
- [ ] ([#4221](https://github.com/freedomofpress/securedrop/issues/4221))
  - [ ] `tmux` session is started/reconnected after SSH to `app` and `mon`.
  - [ ] If testing Xenial upgrade-in-place, `tmux` session reconnects successfully after tor and sshd restarts
- [ ] :fire:  :fire:  ([#4163](https://github.com/freedomofpress/securedrop/issues/4163)) The following packages are not installed on app or mon: `libiw30`, `wpasupplicant`, `wirelesstools`.
- [x] ([#4208](https://github.com/freedomofpress/securedrop/issues/4208)) The NoScript info page on the Source Interface includes a link back to the submissions page.

```
vagrant@app-prod:~$ dpkg -l | grep wpasupplicant
ii  wpasupplicant                      2.4-0ubuntu6.3                                       amd64        client support for WPA and WPA2 (IEEE 802.11i)
vagrant@app-prod:~$ dpkg -l | grep libiw30
ii  libiw30:amd64                      30~pre9-8ubuntu1                                     amd64        Wireless tools - library
```

**Comment by emkll** [comment]
## 0.12.1 QA Checklist

### Environment

- Install target: Trusty VMs
- Tails version: 3.12.1
- Test scenario: Trusty 0.12.1 clean install
- Server locale setting: `fr_FR`
- SSH over Tor: Yes
- Release candidate: 1 
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [ ] [QA Matrix](https://docs.google.com/spreadsheets/d/1G475HDi8dCEXL4YUma4jT8h1-6P9-6jRT56DfDye4u4/edit#gid=0) checks pass

#### Command Line User Generation

- [ ] Can successfully add admin user and login

#### Administration

- [ ] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [ ] If doing upgrade testing, make a backup on 0.12.0 and restore this backup on 0.12.1

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [ ] JS warning bar does not appear when using Security Slider high
- [ ] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [ ] On generate page, refreshing codename produces a new 7-word codename
- [ ] On submit page, empty submissions produce flashed message
- [ ] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [ ] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in

##### Index base cases
- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download" works

##### Individual source page
- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [ ] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot 
- [ ] ([#4100](https://github.com/freedomofpress/securedrop/issues/4100)) Updating occurs without issue

### 0.12.1-specific changes

- [ ] ([#4170](https://github.com/freedomofpress/securedrop/issues/4170)) Tor version is 0.3.4.11 on Trusty or 0.3.5.8 on Xenial
- [ ] ([#4219](https://github.com/freedomofpress/securedrop/issues/4219)) If non-English locale set during OS install, `./securedrop-admin install` completes successfully
- [ ] ([#4221](https://github.com/freedomofpress/securedrop/issues/4221))
  - [ ] `tmux` session is started/reconnected after SSH to `app` and `mon`.
  - [ ] If testing Xenial upgrade-in-place, `tmux` session reconnects successfully after tor and sshd restarts
- [ ] ([#4163](https://github.com/freedomofpress/securedrop/issues/4163)) The following packages are not installed on app or mon: `libiw30`, `wpasupplicant`, `wirelesstools`.
- [ ] ([#4208](https://github.com/freedomofpress/securedrop/issues/4208)) The NoScript info page on the Source Interface includes a link back to the submissions page.


### Preflight 

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.12.1
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.12.1
- [ ] After reboot, updater GUI no longer appears

**Comment by zenmonkeykstop** [comment]
# QA plan
- NUCs
- Mac Minis
- 1U servers in SF

## 0.12.1 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.12.1 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.12.1-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: 2014 Mac Mini
- Tails version: 3.12.1
- Test scenario: upgrade in place
- Server locale setting: (choose non-English to test #4219): Norsk
- SSH over Tor: enabled 
- Release candidate: 3.12.1-rc1
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1G475HDi8dCEXL4YUma4jT8h1-6P9-6jRT56DfDye4u4/edit#gid=0) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [x] If doing upgrade testing, make a backup on 0.12.0 and restore this backup on 0.12.1

### Application Acceptance Testing - SKIPPED

#### Source Interface

##### Landing page base cases
- [ ] JS warning bar does not appear when using Security Slider high
- [ ] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [ ] On generate page, refreshing codename produces a new 7-word codename
- [ ] On submit page, empty submissions produce flashed message
- [ ] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [ ] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in

##### Index base cases
- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download" works

##### Individual source page
- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot 
- [x] ([#4100](https://github.com/freedomofpress/securedrop/issues/4100)) Updating occurs without issue

### 0.12.1-specific changes

- [ ] ([#4170](https://github.com/freedomofpress/securedrop/issues/4170)) Tor version is 0.3.4.11 on Trusty or 0.3.5.8 on Xenial **0.3.4.9 initially, 0.3.5.8 after first cron-apt run**
- [x] ([#4219](https://github.com/freedomofpress/securedrop/issues/4219)) If non-English locale set during OS install, `./securedrop-admin install` completes successfully
- [x] ([#4221](https://github.com/freedomofpress/securedrop/issues/4221))
  - [x] `tmux` session is started/reconnected after SSH to `app` and `mon`.
  - [x] If testing Xenial upgrade-in-place, `tmux` session reconnects successfully after tor and sshd restarts
- [x] ([#4163](https://github.com/freedomofpress/securedrop/issues/4163)) The following packages are not installed on app or mon: `libiw30`, `wpasupplicant`, `wireless-tools`.
- [x] ([#4208](https://github.com/freedomofpress/securedrop/issues/4208)) The NoScript info page on the Source Interface includes a link back to the submissions page.


### Preflight 

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.12.1
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.12.1
- [ ] After reboot, updater GUI no longer appears

**Comment by zenmonkeykstop** [comment]
# QA plan
- NUCs
- Mac Minis
- 1U servers in SF

## 0.12.1 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.12.1 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.12.1-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: 2014 Mac Mini
- Tails version: 3.12.1
- Test scenario: fresh install
- Server locale setting: (choose non-English to test #4219) Irish (Gaelige)
- SSH over Tor: enabled
- Release candidate: 0.12.1-rc1
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1G475HDi8dCEXL4YUma4jT8h1-6P9-6jRT56DfDye4u4/edit#gid=0) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration - SKIPPED

- [ ] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [ ] If doing upgrade testing, make a backup on 0.12.0 and restore this backup on 0.12.1

### Application Acceptance Testing - SKIPPED

#### Source Interface 

##### Landing page base cases
- [ ] JS warning bar does not appear when using Security Slider high
- [ ] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [ ] On generate page, refreshing codename produces a new 7-word codename
- [ ] On submit page, empty submissions produce flashed message
- [ ] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [ ] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in

##### Index base cases
- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download" works

##### Individual source page
- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot 
- [ ] ([#4100](https://github.com/freedomofpress/securedrop/issues/4100)) Updating occurs without issue

### 0.12.1-specific changes

- [x] ([#4170](https://github.com/freedomofpress/securedrop/issues/4170)) Tor version is 0.3.4.11 on Trusty or 0.3.5.8 on Xenial
- [x] ([#4219](https://github.com/freedomofpress/securedrop/issues/4219)) If non-English locale set during OS install, `./securedrop-admin install` completes successfully
- [x] ([#4221](https://github.com/freedomofpress/securedrop/issues/4221))
  - [x] `tmux` session is started/reconnected after SSH to `app` and `mon`.
  - [ ] If testing Xenial upgrade-in-place, `tmux` session reconnects successfully after tor and sshd restarts **not tested**
- [x] ([#4163](https://github.com/freedomofpress/securedrop/issues/4163)) The following packages are not installed on app or mon: `libiw30`, `wpasupplicant`, `wirelesstools`.
- [x] ([#4208](https://github.com/freedomofpress/securedrop/issues/4208)) The NoScript info page on the Source Interface includes a link back to the submissions page.


### Preflight 

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.12.1
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.12.1
- [ ] After reboot, updater GUI no longer appears

**Comment by conorsch** [comment]
I'm happy to take the upgrade box version bump tomorrow in order in support of closing out here. Previously we'd discussed delegating that task to e.g. @rmol, to broaden understanding of the procedures in the team, but I believe that's blocked on AWS API access. Let's discuss at engineering meeting tomorrow to make sure we've covered any potential blockers.

**Comment by emkll** [comment]
The final item on the checklist has been merged in https://github.com/freedomofpress/securedrop/pull/4291, closing!
