### ISSUE TITLE
Source UI design updates: color!

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#4500]
## Design Epic 
Design updates to the Source UI (w/in the existing experience) are being explored in [UX-repo issue #42](https://github.com/freedomofpress/securedrop-ux/issues/42). Within these updates, a new color palette is being used. The goal of the color updates are make the product reflect the SecureDrop brand, as it's presented on the website. They also make the product snazzier.

**This issue has been drafted to implement only the items that pertain to color, from the design epic in the aforementioned GH Issue.**

As such, div background colors, border colors, font colors, and hr styles comprise the majority of the below to-do list. A few stretch-goal items here and there, but they are purely aspirational in nature and not required to close the issue.

In a few places there might be a placed PNG that keeps to the old color schema. Thus far, we have identified the bulleted items as closely related issues that should be addressed in follow-up PRs. If we’ve missed anything, please comment below, and we’ll update the below list accordingly! :)
- Default logo the product ships with #4503
- Update icons placed on Submit/Cancel buttons in Source Interface #4501
- Favicon #4502 
 
## This Issue
Update core styles in the Source UI to reflect the below spec’d values. If time permits, a few identified stretch-goals would be extra special. 

### Global
See _Submit_ page mockup:  [static](https://scene.zeplin.io/project/5cb7d4d1f93bd116d7b25561)
Note: Pay no mind to font size, family, or text-decoration stylings in this mockup. Nina's Tor browser fonts load wackily. Likewise, the mockup does not show hyperlink underlines styled w/ CSS.
- [x] Change `H1`, `H2`, and `H3` to all be `#2a319d`
- [x] Put headlines for "Submit files" and "Read replies" on same level (both should be H2)
- [x] Change static hyperlink color to be  <s>`#0075F7`</s> `#0065db` (previous color was seen as too bright), and `#2a319d` on hover
  - [x] Stretch goal: re-style hyperlinks to use bottom-border attribute, with 40% alpha when static and 100% alpha on hover
     - Using CSS to style hyperlink underlines enables subtle things to enhance legibility of text, by nudging the underline a pixel lower than it usually is and by reducing the static alpha value of the border. By doing both, underlines visually interfere with letterform descenders (g, p, y, j each have _descenders_ in lower-case form) less, and legibility is enhanced w/o interfering with link discovery.
- [x] Change total-UI container box outline (the 1px grey box that encloses everything other than the newsroom logo, footer, and languages widget) to be `#e1e1e1` (currently #c3c3c3)
  - The goal is for this to eventually go away, with some other tweaks; but for now, it should be de-emphasized.

### Index Page
See mockups: [static](https://scene.zeplin.io/project/5cb7d4d1f93bd116d7b25561/screen/5ccc9771c60ef46833e628f4) · [button hover](https://scene.zeplin.io/project/5cb7d4d1f93bd116d7b25561/screen/5cf5c209cee3f113e9e06614)

_Note:_ Pay no mind to font size, family, or text-decoration stylings in this mockup. Nina's Tor browser fonts load wackily. Likewise, the mockup does not show hyperlink underlines styled w/ CSS.
- [x] Both `hr`s: change styling from `dashed` to `dotted`
- [x] Stretch goal: move the languages widget beneath the logo, as it is on all the other pages
#### “Submit for the first time” box
- [x] Box fill: `background-image: linear-gradient(140deg, #0096dc, #005db7);`
- [x] `hr`, text, button text color, and `button border`: `white`
- [x] Button on hover: Keep white icon, border=0, button bg   `background-image: linear-gradient(72deg, #2a319d, #2d3273);`
#### “Already submitted something?” box
- [x] Outline:  `border-width: 1.5px; border-image-source: linear-gradient(145deg, #0096dc, #005db7); border-image-slice: 1;`
- [x] Text & `hr`: `#0A7CDC`
- [x] Button color: `background-image: linear-gradient(111deg, #0082d9, #126ec8);` 
- [x] Button on hover: Keep white icon, border=0, button bg   `background-image: linear-gradient(72deg, #2a319d, #2d3273);`
    
### Submit Page
See mockup:  [static](https://scene.zeplin.io/project/5cb7d4d1f93bd116d7b25561)
_Note:_ Button icons to be done in a separate PR. Pay no mind to font size, family, or text-decoration stylings in this mockup. Nina's Tor browser fonts load wackily. Likewise, the mockup does not show hyperlink underlines styled w/ CSS.
#### Upload/Message Box
- [x] Grey box behind cloud icon and “Browse” bar: update background to:  `background-image: linear-gradient(115deg, #f8fbff, #eaf1f8);`
- [ ] Cloud icon to 20% alpha
#### Buttons
_The button icons are tracked in #4501_
- [x] Primary bg color: <s>`#0075F7`</s> `#0065db` (previous color was seen as too bright); on hover, `#2a319d`
- [x] Cancel border color & text:  <s>`#0075F7`</s> `#0065db` (previous color was seen as too bright); on hover, `#2a319d`

**Comment by eloquence** [comment]
(I'm ticking the boxes above as I make these changes locally and after Nina has reviewed them visually purely for tracking purposes; this does not indicate final review or completion.)

**Comment by eloquence** [comment]
(I've removed the active state for the "Submit" button even as a stretch goal as this will either require JS or some clever CSS magic, and should be handled outside the scope of this refresh.)

**Comment by eloquence** [comment]
Per discussion today we agreed to add a new "Button Blue", `#045fb4`, which mirrors the color used on the SecureDrop website for buttons, such as the "Back" button here:

https://securedrop.org/directory/al-jazeera/

This slightly darker blue works well across Source and Journalist UI for the primary buttons. Links will remain the brighter "SecureDrop Blue" color.

**Comment by ninavizz** [comment]
New colors + PNG artifacts documented: https://github.com/freedomofpress/securedrop-ux/issues/65
