### ISSUE TITLE
Release SecureDrop 0.13.1

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4524]
This is a tracking issue for the upcoming release of SecureDrop 0.13.1 - tasks may get added or modified. 

**Feature freeze:** EOD Pacific time, Friday, June 14
**Release date:** Tuesday, June 18
 
_SecureDrop maintainers and testers:_ As you QA 0.13.1, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 0.13.1 milestone for tracking (or ask a maintainer to do so). 

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d).

# Prepare release candidate (0.13.1~rc1)
- [x] Prepare 0.13.1-rc1 release changelog - @emkll 
- [x] Branch off 0.13.1~rc1 into release/0.13.1 - @emkll
- [x] Build debs and put up `0.13.1~rc1` on test apt server @emkll 

### Test plan

https://github.com/freedomofpress/securedrop/wiki/0.13.1-Test-plan
### QA matrix

https://docs.google.com/spreadsheets/d/19L1zj4otg2IoTxSKw5ZLaNjgUm7uZETvc37LkX6IQ1E/edit#gid=0

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image @zenmonkeykstop @emkll 
- [x] Push signed tag @redshiftzero 
- [x] Build final Debian packages for 0.13.1 - @conorsch 
- [x] Upload Debian packages to apt test - @conorsch 
- [x] Pre-Flight: Test install and upgrade (both cron-apt on Trusty, and Ansible on Xenial) of 0.13.1 works w/ prod repo debs, test updater logic in Tails
- [x] Prepare and distribute release messaging

# Post release

- [x] Merge changelog back to `develop` #4537 
- [x] Update upgrade testing boxes
- [x] Update roadmap wiki page

**Comment by rmol** [comment]
### Environment

- Install target: NUC7i5BNH
- Tails version: 3.14
- Test Scenario: cron-apt upgrade of 0.13.0 to 0.13.1
- SSH over Tor: yes
- Release candidate: 0.13.1~rc1
- General notes: I skipped the backup before upgrade. The updater GUI isn't popping up because of the `rc` tag. But the `journalist-key` endpoint is working.

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1SFGDrsMAw6X-I4v6ZC7ZkmHl3eS9peh5xfuP-JtPOB8/edit#gid=0) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [ ] If doing upgrade testing, make a backup on 0.13.0 and restore this backup on 0.13.1
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low ([#4211](https://github.com/freedomofpress/securedrop/pull/4211))

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot
- [ ] Updating occurs without issue

### 0.13.1-specific changes

- [x] `/journalist-key` endpoint on Source Interface returns the Journalist Submission public RSA key (see https://github.com/freedomofpress/securedrop/pull/4523)

**Comment by eloquence** [comment]
Draft release messaging for SecureDrop 0.13.1:
https://docs.google.com/document/d/1kqWbFywGGB1E4V7aLMFCFjLWHxqj-pYp0X4mFZ9wem8/edit#

**Comment by zenmonkeykstop** [comment]
# QA plan

- NUC5s
   OR 
- NUC7s
   OR 
- Mac Minis
   OR 
- 1U servers in SF


## 0.13.1 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.13.1 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.13.1-specific changes as well as changes since the previous release candidate.

**Note:** if you are testing an upgrade scenario, you should create several sources and submit a large number of files of varying sizes up to the 500MB limit before performing the upgrade. A large dataset is required in order to test the long-running database migration task implemented in [#4134](https://github.com/freedomofpress/securedrop/pull/4314).

### Environment

- Install target:NUC5s
- Tails version: 3.14 
- Test Scenario: fresh
- SSH over Tor: yes
- Release candidate: rc1
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1SFGDrsMAw6X-I4v6ZC7ZkmHl3eS9peh5xfuP-JtPOB8/edit#gid=0) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [x] If doing upgrade testing, make a backup on 0.13.0 and restore this backup on 0.13.1 -**n/a**
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent. 

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high **(this passes in 3.14/8.5 but fails in 3.13.1/8.0)**
- [x] JS warning bar does appear when using Security Slider Low ([#4211](https://github.com/freedomofpress/securedrop/pull/4211))

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot 
- [x] Updating occurs without issue

### 0.13.1-specific changes

- [x] `/journalist-key` endpoint on Source Interface returns the Journalist Submission public RSA key (see https://github.com/freedomofpress/securedrop/pull/4523)
### Preflight 

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.13.1
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.13.1
- [ ] After reboot, updater GUI no longer appears

**Comment by eloquence** [comment]
All release comms completed.
- [Tweet](https://twitter.com/SecureDrop/status/1141092843634606080)
- [Blog post](https://securedrop.org/news/securedrop-0131-released/)
- Bulk announcements to admins can be found in the support portal

**Comment by emkll** [comment]
Final box was checked via https://github.com/freedomofpress/securedrop/pull/4545, closing.
