### ISSUE TITLE
Release SecureDrop 0.14.0

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4550]
This is a tracking issue for the upcoming release of SecureDrop 0.14.0 - tasks may get added or modified. 

**Feature freeze:** EOD Pacific time, Tuesday, June 25
**String freeze:** EOD Pacific time, Tuesday, June 25
**Pre-release announcement:** Tuesday, July 2 
**Release date:** Tuesday, July 9

**Release manager:** @redshiftzero 
**Deputy release manager:** @creviera
**Localization manager:** @rmol
**Deputy localization manager:** @kushaldas 
 
_SecureDrop maintainers and testers:_ As you QA 0.14.0, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 0.14.0 milestone for tracking (or ask a maintainer to do so). 

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/conorsch/e7556624df59b2a0f8b81f7c0c4f9b7d).

# [QA Matrix for 0.14.0](https://docs.google.com/spreadsheets/d/1nPGpQWEZLf3hOuo9IyIfjn5cBaREPMJjcZF5IJSviKU/edit)

# [Test Plan for 0.14.0](https://github.com/freedomofpress/securedrop/wiki/0.14.0-Test-Plan)

# Prepare release candidate (0.14.0~rc1)
- [x] Prepare 0.14.0-rc1 release changelog - @redshiftzero    
- [x] Branch off release/0.14.0 - @redshiftzero  
- [x] Prepare 0.14.0~rc1 - @redshiftzero
- [x] Build debs and put up `0.14.0~rc1` on test apt server - @redshiftzero

# Other pre-release tasks

- [x] Prepare and distribute pre-release messaging - @eloquence 

# Prepare release candidate (0.14.0~rc2)
- [x] Prepare 0.14.0-rc2 release changelog - @creviera    
- [x] Prepare 0.14.0~rc2 - @creviera & @redshiftzero
- [x] Build debs and put up `0.14.0~rc2` on test apt server - @redshiftzero 

After each test, please update the QA matrix and post details for Basic Server Testing, Application Acceptance Testing and 0.14.0-specific testing below in comments to this ticket.

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image - @emkll
- [x] Merge final translations - @rmol, @kushaldas 
- [x] Push signed tag - @redshiftzero
- [x] Build final Debian packages for 0.14.0
- [x] Upload Debian packages to apt test
- [x] Pre-Flight: Test install and upgrade (both cron-apt on Trusty, and Ansible on Xenial) of 0.14.0 works w/ prod repo debs, test updater logic in Tails
- [x] Prepare and distribute release messaging - @eloquence 

# Post release

- [x] Merge changelog back to `develop` @redshiftzero #4616 
- [x] Bump version on `develop` in prep for 1.0.0 release (0.14.0 is the last regular SecureDrop release in the 0.x.y series - note there may be small 0.14.x bug fix releases) @redshiftzero #4616 
- [x] Update upgrade testing boxes @emkll #4617
- [x] Update roadmap wiki page @emkll

**Comment by zenmonkeykstop** [comment]
# QA plan

- NUC5s
- NUC7s
- Mac Minis
- 1U servers in SF

## 0.14.0 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.14.0 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.14.0-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: NUC5
- Tails version: 3.14
- Test Scenario: fresh install
- SSH over Tor: yes
- Release candidate: rc1
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1nPGpQWEZLf3hOuo9IyIfjn5cBaREPMJjcZF5IJSviKU/edit) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [ ] If doing upgrade testing, make a backup on 0.13.1 and restore this backup on 0.14.0 **n/a**
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high **It's not a slider anymore but yup**
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot 
- [x] Updating occurs without issue

### 0.14.0-specific changes

- [x] Ensure there are no Font Awesome CSS assets loaded on the source interface (#4464)
- [x] Ensure that the supported locales are exposed in the source interface metadata API (for a case with only supported en_US locale, and a case where multiple locales are supported) (#4467).
- [x] Run through source interface Tor Browser 8.5 security settings - ensure instructions are accurate (#4462,  #4494)
- [x] Ensure you can set a journalist first name and last name via the CLI (#4425)
- [x]  Ensure you can successfully add a new account as an admin from the journalist interface(#4425) 
- [x]  Ensure you can successfully change the name of an account that is not yours as an admin from the admin page (#4425)
- [x]  Ensure you can successfully change your own name as a non-admin from the account page (#4425)
- [x] Ensure you can successfully change your own name to empty strings as a  non-admin from the accounts page (#4425)
- [x] Ensure you can export a tarball containing logs via `securedrop-admin logs` (#4497)
- [x] Ensure that intel-microcode is installed (#4543).
- [x] Ensure that grsec kernels version 4.4.182 are installed (#4543).
- [x] Follow STR in https://github.com/freedomofpress/securedrop/issues/4490 to verify sessions expiring on /generate do not cause errors (#4496).

### Preflight 

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.14.0
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.14.0
- [ ] After reboot, updater GUI no longer appears

**Comment by eloquence** [comment]
Pre-release messaging WIP (still need to do an editing pass, but first comments welcome): https://docs.google.com/document/d/1Ek7HX6Lgt-vImL8b11mFk8zYUmOuyC2YKZg81McAYWM/edit#heading=h.9no1ej3j0v0j

**Comment by eloquence** [comment]
Pre-release messaging done:
- https://securedrop.org/news/securedrop-0140-pre-release-announcement/
- https://twitter.com/SecureDrop/status/1146204775203008513
- Bulk announce run completed.

**Comment by emkll** [comment]
## 0.13.1->0.14.0-rc2 in VMs (WIP)

### Environment

- Install target: VMs
- Tails version: 3.14.2
- Test Scenario: 0.13.1->0.14.0-rc2 Upgrade (via cron-apt)
- SSH over Tor: No
- Release candidate: RC2
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [ ] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [ ] [QA Matrix](https://docs.google.com/spreadsheets/d/1nPGpQWEZLf3hOuo9IyIfjn5cBaREPMJjcZF5IJSviKU/edit) checks pass

#### Command Line User Generation

- [ ] Can successfully add admin user and login

#### Administration

- [ ] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [ ] If doing upgrade testing, make a backup on 0.13.1 and restore this backup on 0.14.0
- [ ] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [ ] JS warning bar does not appear when using Security Slider high
- [ ] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [ ] On generate page, refreshing codename produces a new 7-word codename
- [ ] On submit page, empty submissions produce flashed message
- [ ] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [ ] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in

##### Index base cases
- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download" works

##### Individual source page
- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [ ] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot 
- [ ] Updating occurs without issue

### 0.14.0-specific changes

- [ ] Ensure there are no Font Awesome CSS assets loaded on the source interface (#4464)
- [ ] Ensure that the supported locales are exposed in the source interface metadata API (for a case with only supported en_US locale, and a case where multiple locales are supported) (#4467).
- [ ] Run through source interface Tor Browser 8.5 security settings - ensure instructions are accurate (#4462,  #4494)
- [ ] Ensure you can set a journalist first name and last name via the CLI (#4425)
- [ ]  Ensure you can successfully add a new account as an admin from the journalist interface(#4425)
- [ ]  Ensure you can successfully change the name of an account that is not yours as an admin from the admin page (#4425)
- [ ]  Ensure you can successfully change your own name as a non-admin from the account page (#4425)
- [ ] Ensure you can successfully change your own name to empty strings as a  non-admin from the accounts page (#4425)
- [ ] Ensure you can export a tarball containing logs via `securedrop-admin logs` (#4497)
- [ ] Ensure that intel-microcode is installed (#4543).
- [ ] Ensure that grsec kernels version 4.4.182 are installed (#4543).
- [ ] Follow STR in https://github.com/freedomofpress/securedrop/issues/4490 to verify sessions expiring on /generate do not cause errors (#4496).

### 0.14.0-rc2 specific changes

- [ ] Installed version of `securedrop-keyring` should be `0.1.3`
- [ ] `securedrop-admin logs` completes without issue in Tails
- [ ] Verify that the update process works when a release key is already in the GPG keychain in Tails, using the following commands in a terminal:

```
cd ~/Persistent/securedrop
gpg --recv-key "22245C81E3BAEB4138B36061310F561200F4AD77"   # use Tails' default keyserver
git checkout 0.14.0-rc2
./securedrop-admin update
git status    # should now be on 0.13.1 tag
```

- [ ] Verify that the update process works when a release key is already in the GPG keychain in Tails, using the following commands in a terminal:

```
gpg --delete-keys "22245C81E3BAEB4138B36061310F561200F4AD77"
git checkout 0.14.0-rc2
./securedrop-admin update
git status    # should now be on 0.13.1 tag
```

### Preflight 

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.14.0
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.14.0
- [ ] After reboot, updater GUI no longer appears

**Comment by zenmonkeykstop** [comment]
# QA plan

- NUC5s
- NUC7s
- Mac Minis
- 1U servers in SF

## 0.14.0 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.

If you have submitted a QA report already for a 0.14.0 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 0.14.0-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: 2014 Mac Mini
- Tails version: 3.14.2
- Test Scenario: upgrade from 0.13.1
- SSH over Tor: yes	
- Release candidate: 0.14.0-rc2
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [ x I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1nPGpQWEZLf3hOuo9IyIfjn5cBaREPMJjcZF5IJSviKU/edit) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following the documentation here: https://docs.securedrop.org/en/latest/backup_and_restore.html
- [x] If doing upgrade testing, make a backup on 0.13.1 and restore this backup on 0.14.0
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent.

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in

##### Index base cases
- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page
- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

#### Updater GUI

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot 
- [x] Updating occurs without issue

### 0.14.0-specific changes

- [x] Ensure there are no Font Awesome CSS assets loaded on the source interface (#4464)
- [x] Ensure that the supported locales are exposed in the source interface metadata API (for a case with only supported en_US locale, and a case where multiple locales are supported) (#4467).
- [x] Run through source interface Tor Browser 8.5 security settings - ensure instructions are accurate (#4462,  #4494) 
- [x] Ensure you can set a journalist first name and last name via the CLI (#4425)
- [x]  Ensure you can successfully add a new account as an admin from the journalist interface(#4425)
- [x]  Ensure you can successfully change the name of an account that is not yours as an admin from the admin page (#4425)
- [x]  Ensure you can successfully change your own name as a non-admin from the account page (#4425)
- [x] Ensure you can successfully change your own name to empty strings as a  non-admin from the accounts page (#4425)
- [x] Ensure you can export a tarball containing logs via `securedrop-admin logs` (#4497)
- [x] Ensure that intel-microcode is installed (#4543).
- [x] Ensure that grsec kernels version 4.4.182 are installed (#4543).
- [x] Follow STR in https://github.com/freedomofpress/securedrop/issues/4490 to verify sessions expiring on /generate do not cause errors (#4496).

### 0.14.0-rc2 specific changes

- [x] Installed version of `securedrop-keyring` should be `0.1.3`
- [x] `securedrop-admin logs` completes without issue in Tails
- [x] Verify that the update process works when a release key is already in the GPG keychain in Tails, using the following commands in a terminal:

```
cd ~/Persistent/securedrop
gpg --recv-key "22245C81E3BAEB4138B36061310F561200F4AD77"   # use Tails' default keyserver
git checkout 0.14.0-rc2
./securedrop-admin update
git status    # should now be on 0.13.1 tag
```

- [x] Verify that the update process works when a release key is *not* already in the GPG keychain in Tails, using the following commands in a terminal:

```
gpg --delete-keys "22245C81E3BAEB4138B36061310F561200F4AD77"
git checkout 0.14.0-rc2
./securedrop-admin update
git status    # should now be on 0.13.1 tag
```

### Preflight 

- [ ] Ensure the builder image is up-to-date on release day

These tests should be performed the day of release prior to live debian packages on apt.freedom.press

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 0.14.0
- [ ] A message can be successfully submitted 

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 0.14.0
- [ ] After reboot, updater GUI no longer appears

**Comment by eloquence** [comment]
Draft release messaging, with new content highlighted:
https://docs.google.com/document/d/1hkvnRcN8q3SDXidNDfsISogupm-l7JPuioPJSUMR1MA/edit

**Comment by eloquence** [comment]
Release comms completed:
- Release notes: https://securedrop.org/news/securedrop-0140-released/
- Tweet: https://twitter.com/SecureDrop/status/1149056353421316096
- Bulk announcement sent.

**Comment by emkll** [comment]
Last post-release tasks (upgrade boxes and roadmap update) have been completed, closing!
