### ISSUE TITLE
[docs] Add org logo into instal checklist + page capitalization

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop#4619]
## Problem

Not sure how orgs are supposed to know they should update the default logo on their SecureDrop install, if it's not explicitly called-out to them in the installation checklist—which today, it is not. #whompwhomp

This may be mentioned in best-practices pointers, and in the Admin Guide, but it cannot be assumed orgs will read either (carefully) and naturally identify the logo task as a must-do to-do, given how resource-constrained most orgs are... and how time-constrained most of the IT and Admin resources are. 

<soapbox> Much as FPF may desire prioritizing customer-centricity towards instance hosts, FPF also has a responsibility to steward org practices as they may impact Source choices. Sources may be risking their personal safety, their lives, or their careers, by sharing sensitive information. There is an ethical imperative to force instance-org hands to at a minimum, be clear in identifying who they are to Sources—or, to be clear in their choice to obfuscate their identity. Both can be done, and should be done, with clear guidance. </soapbox>

### Edit the ["Configure The Installation"](https://docs.securedrop.org/en/release-0.14.0/install.html#configure-the-installation) page, accordingly:
- Capitalize all letters that begin sentences on the bulleted items at top of page (nit!)
- Add bullet before creating users, regarding org logo
  - Recommended text: `The logo .png identifying your organization to Source users (see the <a>Create Logo Image Guide</a>)`
- Create `Create Logo Image Guide` page.
  - Page will be minimal to start, and will offer basic co-branding guidance to orgs.
    - Nina has written many such pages, and will be happy to compose text that Erik/Kev can then refine
    - Note: this is not a "SecureDrop Logo/Trademark Use Guidelines" page; rather purely an instructional page to guide on best practices for orgs to slap their own logo into the PNG we provide—and to then save that PNG as a PNG-24. It may additionally guide Admins in the rather obvious workflow of updating that logo.
  - Page will evolve to outline self-identification and logo use governance.
### Add stand-alone page to Add Logo Image
- Step should happen immediately after [Create Users](https://docs.securedrop.org/en/release-0.14.0/create_admin_account.html) page.
  - Currently [this is buried](https://docs.securedrop.org/en/release-0.14.0/admin.html#updating-logo-image) in the steps-to-go-live flow. Badly. Too badly.
  - Using 2 images of the SecureDrop logo is waaaay confusing. Please use FPF logo as an example logo to customize to.

![image](https://user-images.githubusercontent.com/8262612/61190614-fede7900-a653-11e9-8dc4-02934fab24b7.png)

## User Stories
1. As a _Source_, it is very important to me to know where I am submitting information to...
2. As a newsroom _Admin_, I probably need it included in the checklist of setup instructions, to customize my org's logo. Additionally, some guidance on how to do this, would be very nice.

**Comment by ninavizz** [comment]
Discussed w/ @eloquence... TL;DR, docs be complicated. Action item(s) agreed to = make existing text more emphatic, and add a coupla screenshots. So of course, I'm also recommending we create a whole other page and make a few more text edits. 

Everything below, overrides everything above.

- [ ] Text towards the end of [this page](https://docs.securedrop.org/en/release-0.14.0/overview.html) wrt landing pages; re-frame as directive. "Best Practices" is too jargon-y, and feels too optional.
- [ ] Mention in [Before You Begin](https://docs.securedrop.org/en/release-0.14.0/before_you_begin.html) page
- [ ] Remove "note" blue box thingy at [bottom of this page](https://docs.securedrop.org/en/release-0.14.0/create_admin_account.html)
- [ ] Create new page titled `Brand Your Instance` and position it as a step between `Create an Admin Account on the Journalist Interface` and `Test the Installation`. 
   - On said new page, outline governance rules for customizing the `logo-img` 
   - No SD/Me mashups, should include your name written-out, should save as PNG-24 at 4x, and some "Do This" and "Don't Do This" examples.
   - Create page content and distribute to existing instance owners via RedMine BEFORE adding into RTD, to solicit feedback to consider before adding content into RTD.
