### ISSUE TITLE
Release SecureDrop 1.2.2

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5156]
This is a tracking issue for the release of [SecureDrop 1.2.2](https://github.com/freedomofpress/securedrop/milestone/61). 

The 1.2.2 release will contain no new strings requiring translation.

**Feature freeze:** 2020-03-13 (1000 PST) 
**Release date:**  TBD, 2020-03-13

**Release manager:** @zenmonkeykstop  
**Deputy release manager:** @emkll  
 
_SecureDrop maintainers and testers:_ As you QA 1.2.2, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the 1.2.2 milestone for tracking (or ask a maintainer to do so). 

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/rmol/eb605e28e290e90f45347f3a2f1ad43e).

# [QA Matrix for 1.2.2](https://docs.google.com/spreadsheets/d/1df9Q5flh9fDwppIgefgqGwrU-5df9NcPUmN69Hpxv5k/edit?usp=sharing)

# [Test Plan for 1.2.2](https://github.com/freedomofpress/securedrop/wiki/1.2.2-Test-Plan)

# Prepare release candidate (1.2.2~rc1)
- [x] Prepare 1.2.2~rc1 release changelog 
- [x] Branch off release/1.2.2 from release/1.2.2
- [x] Prepare 1.2.2~rc1
- [x] Build debs and put up `1.2.2~rc1` on test apt server (this is now done via a PR into [this repository](https://github.com/freedomofpress/securedrop-dev-packages-lfs)) 
- [x] Commit build logs to https://github.com/freedomofpress/build-logs 

After each test, please update the QA matrix and post details for Basic Server Testing, Application Acceptance Testing and 1.2.2-specific testing below in comments to this ticket.

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image
- [x] Push signed tag 
- [x] Build final Debian packages for 1.2.2 (and preserve build logs)
- [x] Commit package build logs to https://github.com/freedomofpress/build-logs
- [x] Upload Debian packages to apt QA server 
- [x] Pre-Flight: Test install and upgrade (both cron-apt on Xenial, and Ansible on Xenial) of 1.2.2 works w/ prod repo debs, test updater logic in Tails
- [x] Prepare and distribute release messaging 

# Post release
- [x] Create GitHub release object
- [x] Merge changelog back to `develop`
- [ ] Update upgrade testing boxes
- [x] Update roadmap wiki page

**Comment by emkll** [comment]
## 1.2.1 -> 1.2.2 Upgrade testing (In progress)
### Environment
 
- Install target: Mac mini (app), Nuc5 (mon)
- Tails version: 4.4
- Test Scenario: Upgrade
- SSH over Tor: Yes
- Onion service version: v3
- Release candidate: rc1
- General notes: I had to check out 1.2.2 to run `./securedrop-admin setup`. Reverted to 1.2.1 to `./securedrop-admin install`

### Basic Server Testing
 
- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [ ] [QA Matrix](https://docs.google.com/spreadsheets/d/1_7oBsCYkt_CAMLpui5x0blCCFZYRgokackRPMjjwPJA/edit#gid=0) checks pass
 
#### Command Line User Generation
 
- [ ] Can successfully add admin user and login
 
#### Administration
 
- [ ] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [ ] If doing upgrade testing, make a backup on 1.2.0 and restore this backup on 1.2.1
- [ ] If doing upgrade testing, verify that document submission via the Source Interface is enabled after the upgrade is complete
- [ ] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] Can successfully add journalist account with HOTP authentication 
 
### Application Acceptance Testing
 
#### Source Interface
 
##### Landing page base cases
- [ ] JS warning bar does not appear when using Security Slider high
- [ ] JS warning bar does appear when using Security Slider Low
 
##### First submission base cases
- [ ] On generate page, refreshing codename produces a new 7-word codename
- [ ] On submit page, empty submissions produce flashed message
- [ ] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [ ] On submit page, file less than 500 MB submitted successfully
 
##### Returning source base cases
 
- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test
 
#### Journalist Interface
 
##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in
- [ ] Journalist account with HOTP can log in
 
##### Index base cases

- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download" works
 
##### Individual source page

- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [ ] You can click on a document and successfully decrypt using application private key
 
### Basic Tails Testing
 
#### Updater GUI
 
After updating to this release candidate and running `securedrop-admin tailsconfig`
 
- [ ] The Updater GUI appears on boot
- [ ] Updating fails in set up phase (setup phase will fail until preflight and availability of 1.2.2 tag)

### 1.2.2-specific changes
- [ ] Confirm that `./securedrop-admin` setup works on Tails 4.4 (see https://github.com/freedomofpress/securedrop/issues/5155)
- [ ] Confirm that psutil is updated to 5.7.0

 
### Preflight 
 
- [ ] Ensure the builder image is up-to-date on release day
 
These tests should be performed the day of release prior to live Debian packages on apt.freedom.press
 
#### Basic testing
 
- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 1.2.1
- [ ] A message can be successfully submitted 
 
#### Tails
 
- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 1.2.1
- [ ] After reboot, updater GUI no longer appears

**Comment by emkll** [comment]
## 1.2.2 clean install (in progress)
### Environment
 
- Install target: Mac mini (app), Nuc5 (mon)
- Tails version: 4.4
- Test Scenario: Upgrade
- SSH over Tor: Yes
- Onion service version: v3
- Release candidate: rc1
- General notes: I had to check out 1.2.2 to run `./securedrop-admin setup`. Reverted to 1.2.1 to `./securedrop-admin install`

### Basic Server Testing
 
- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1_7oBsCYkt_CAMLpui5x0blCCFZYRgokackRPMjjwPJA/edit#gid=0) checks pass
 
#### Command Line User Generation
 
- [x] Can successfully add admin user and login
 
#### Administration
 
- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] If doing upgrade testing, make a backup on 1.2.0 and restore this backup on 1.2.1
- [x] If doing upgrade testing, verify that document submission via the Source Interface is enabled after the upgrade is complete
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] Can successfully add journalist account with HOTP authentication (don't have a test YK)
 
### Application Acceptance Testing
 
#### Source Interface
 
##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low
 
##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully
 
##### Returning source base cases
 
- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test
 
#### Journalist Interface
 
##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in
- [ ] Journalist account with HOTP can log in
 
##### Index base cases

- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download" works
 
##### Individual source page

- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [ ] You can click on a document and successfully decrypt using application private key
 
### Basic Tails Testing
 
#### Updater GUI
 
After updating to this release candidate and running `securedrop-admin tailsconfig`
 
- [x] The Updater GUI appears on boot
- [ ] Updating fails in set up phase (setup phase will fail until preflight and availability of 1.2.2 tag)

### 1.2.2-specific changes
- [x] Confirm that `./securedrop-admin` setup works on Tails 4.4 (see https://github.com/freedomofpress/securedrop/issues/5155)
- [x] Confirm that psutil is updated to 5.7.0

**Comment by zenmonkeykstop** [comment]
# 1.2.2 QA plan

As 1.2.2 includes no kernel or admin changes, we're testing on a subset of supported hardware:

- NUC7s
- Mac Minis
 
## 1.2.2 QA Checklist
 
For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report. Feel free to edit this message to update the plan as appropriate.
 
If you have submitted a QA report already for a 1.2.2 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 1.2.2-specific changes as well as changes since the previous release candidate.
 
### Environment
 
- Install target: VMs
- Tails version: 4.4
- Test Scenario: install
- SSH over Tor: yes
- Onion service version: v3
- Release candidate: rc1
- General notes:

### Basic Server Testing
 
- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [ ] OSSEC emails begin to flow after install **not tested**
- [ ] OSSEC emails are decrypted to correct key and I am able to decrypt them **not tested**
- [X] [QA Matrix](https://docs.google.com/spreadsheets/d/1_7oBsCYkt_CAMLpui5x0blCCFZYRgokackRPMjjwPJA/edit#gid=0) checks pass
 
#### Command Line User Generation
 
- [x] Can successfully add admin user and login
 
#### Administration
 
- [ ] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [ ] If doing upgrade testing, make a backup on 1.2.0 and restore this backup on 1.2.1
- [ ] If doing upgrade testing, verify that document submission via the Source Interface is enabled after the upgrade is complete
- [ ] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] Can successfully add journalist account with HOTP authentication 
 
### Application Acceptance Testing
 
#### Source Interface
 
##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low
 
##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully
 
##### Returning source base cases
 
- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test
 
#### Journalist Interface
 
##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in
- [x] Journalist account with HOTP can log in
 
##### Index base cases

- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works
 
##### Individual source page

- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source And Submissions" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key
 
### Basic Tails Testing
 
#### Updater GUI
 
After updating to this release candidate and running `securedrop-admin tailsconfig`
 
- [x] The Updater GUI appears on boot
- [ ] Updating fails in set up phase (setup phase will fail until preflight and availability of 1.2.2 tag)

### 1.2.2-specific changes
- [x] Confirm that `./securedrop-admin` setup works on Tails 4.4 (see https://github.com/freedomofpress/securedrop/issues/5155)
- [x] Confirm that psutil is updated to 5.7.0

 
### Preflight 
 
- [ ] Ensure the builder image is up-to-date on release day
 
These tests should be performed the day of release prior to live Debian packages on apt.freedom.press
 
#### Basic testing
 
- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 1.2.1
- [ ] A message can be successfully submitted 
 
#### Tails
 
- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 1.2.1
- [ ] After reboot, updater GUI no longer appears
