### ISSUE TITLE
make staging-focal for a Focal based staging environment

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5468]
## Description

We need `make staging-focal` to create a Ubuntu Focal based staging environment which can use the locally built packages. 

This is part of #4768

### Progress
- [x] Create a barebones staging environment for iterating - #5486
- [x] Focal staging environment installs completely with no errors - #5518
- [x] Support multiple VM drivers (e.g. libvirt, qubes) #5585

**Comment by conorsch** [comment]
@kushaldas Do you have any unpushed WIP branches for Focal staging support? I checked the recent branches on the remote, didn't see anything, so pushed: https://github.com/freedomofpress/securedrop/tree/5468-libvirt-staging-focal That's enough to get the VMs up and running, but they fail when configuring the apt-test repo, since we don't have any packages in the Focal channel on apt-test yet. As soon as https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/60 is merged, I'd expect the initial repo setup to work, but we shall see. 

Feel free to append to that branch or point me somewhere else to peek at ongoing work.

**Comment by conorsch** [comment]
Opened a draft PR documenting what progress we've made so far: https://github.com/freedomofpress/securedrop/pull/5486 @kushaldas has some pre-existing work in the `on_focal` branch, some of which may need to be pulled in. 

Major problems encountered so far:

* Custom kernel installation doesn't work. Ostensibly this is merely due to lack of a `securedrop-grsec` metapackage for focal on apt-test, see https://github.com/freedomofpress/securedrop-dev-packages-lfs/issues/59#issuecomment-686833618
* The PaX flags supported by the grub binaries have changed header formats. We can work around this with distro-specific logic, but I'm inclined to switch to paxctld, which we're already using in the Workstation (https://github.com/freedomofpress/securedrop-debian-packaging/blob/3f33993e4cadc6e3ff713944e1d9f3df54ccea7a/securedrop-workstation-grsec/debian/control#L15), see #4134
* The app-code deb package fails to install due to a missing wsgi call in postinst; possibly related to "Upgrade (and review) mod_wsgi dependency" in #4768

**Comment by eloquence** [comment]
(Closing this out, we do have `make staging-focal`, tasks that were remaining are already tracked separately).
