### ISSUE TITLE
Release SecureDrop 1.8.1

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#5891]
This is a tracking issue for the release of SecureDrop 1.8.1. This minor release will provide improvements to the restore functionality, and update OSSEC rules to support the transition to Ubuntu 20.04 Focal.

Tentatively scheduled as follows:

**String and feature freeze:** 2021-04-07
**Pre-release announcement:** 2021-04-08
**Release date:** 2021-04-14

**Release manager:** @kushaldas  
**Deputy release manager:** @emkll 
**Communications manager:**: @eloquence / @emkll 

_SecureDrop maintainers and testers:_ As you QA 1.8.1, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the [1.8.1 milestone](https://github.com/freedomofpress/securedrop/milestone/71) for tracking (or ask a maintainer to do so).

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/rmol/eb605e28e290e90f45347f3a2f1ad43e).

# [QA Matrix for 1.8.1](https://docs.google.com/spreadsheets/d/1JZZ6kozgfFSkMV2XWjajWoLDmABjnzUsmbMCOhUaAAg/edit?usp=sharing)
# [Test Plan for 1.8.1](https://github.com/freedomofpress/securedrop/wiki/1.8.1-Test-Plan)

# Prepare release candidate (1.8.1~rc1)
- [x] Cherry-pick changes to release/1.8.0 branch @zenmonkeykstop  https://github.com/freedomofpress/securedrop/pull/5890
- [ ] Link to latest version of Tails, including release candidates, to test against during QA
- [x] Prepare 1.8.1~rc1 release changelog
- [x] Prepare 1.8.1~rc1 Tag https://github.com/freedomofpress/securedrop/tree/1.8.1-rc1
- [x] Build debs and put up `1.8.1~rc1` on test apt server: https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/102
- [x] Commit build logs to https://github.com/freedomofpress/build-logs/commit/639b9f5d2c0aea1b03415ee1724d1f602ac017ed

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image
- [x] Push signed tag https://github.com/freedomofpress/securedrop/releases/tag/1.8.1
- [x] Pre-Flight: Test updater logic in Tails (apt-qa tracks the `release` branch in the LFS repo)
- [x] Build final Debian packages for 1.8.0 (and preserve build logs)
- [x] Commit package build logs to https://github.com/freedomofpress/build-logs/commit/03a90fa69bbb8256cbb034675b09ddd60e17f25c
- [x] Upload Debian packages to apt-qa server 
- [x] Pre-Flight: Test that install and upgrade from 1.8.0 to 1.8.1 works w/ prod repo debs (apt-qa.freedom.press polls the `release` branch in the LFS repo for the debs)
- [x] Flip apt QA server to prod status (merge to `main` in the LFS repo)
- [x] Merge Docs branch changes to ``main`` and verify new docs build in securedrop-docs repo
- [x] Prepare release messaging

# Post release
- [x] Create GitHub release object https://github.com/freedomofpress/securedrop/releases/tag/1.8.0
- [x] Once release object is created, update versions in `securedrop-docs` and Wagtail
- [x] Build readthedocs and verify new docs show up on https://docs.securedrop.org
- [x] Publish announcements
- [ ] Merge changelog, https://github.com/freedomofpress/securedrop/pull/5899, and https://github.com/freedomofpress/securedrop/pull/5894/ back to `develop`
- [ ] Update upgrade testing boxes (might not be possible due to https://github.com/freedomofpress/securedrop/issues/5883)
- [x] Update roadmap wiki page: https://github.com/freedomofpress/securedrop/wiki/Development-Roadmap

**Comment by kushaldas** [comment]
## 1.8.1 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report.

If you have submitted a QA report already for a 1.8.0 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 1.8.0-specific changes as well as changes since the previous release candidate.

There are OS-specific sections in the test plan - make sure you complete the appropriate section based on the server OS in your chosen test scenario.

### Environment

- Install target: 1.8.1-rc1
- Server OS: Xenial
- Tails version: 4.16
- Test Scenario:v2+v3 update
- SSH over Tor: Yes
- Onion service version: v2+v3
- Release candidate: rc1
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1i1sW4lfiUC_lS5qmB-kyjjgyx0rOjf_vJao5hOGmS78/) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] If doing upgrade testing, make a backup on 1.7.1 and restore this backup on this release candidate
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [x] Can successfully add journalist account with HOTP authentication

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in
- [x] Journalist account with HOTP can log in

##### Index base cases

- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page

- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source Account" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot
- [ ] Updating occurs without issue

### 1.8.1 release-specific changes (common)

- [x] Correct backup location of custom logo [#5880](https://github.com/freedomofpress/securedrop/issues/5880)
- [x] Exclude SSH tor config from server restores [#5833](https://github.com/freedomofpress/securedrop/issues/5833)

### 1.8.1 release-specific changes (Focal only)

- [ ] No `fwupd` related OSSEC alert emails on hardware install on Focal [#5835](https://github.com/freedomofpress/securedrop/issues/5835). The following two lines contains the error message as examples.
  - `Mar  1 13:22:53 app fwupd[133921]: 13:22:53:0576 FuEngine             Failed to load SMBIOS: invalid DMI data size, got 2527 bytes, expected 2745`
  - `Mar  1 13:22:53 app fwupd[133921]: 13:22:53:0883 FuPluginUefi         Error opening directory â€œ/sys/firmware/efi/esrt/entriesâ€�: No such file or directory`
  


### Preflight testing

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 1.8.0
- [ ] A message can be successfully submitted

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 1.8.0
- [ ] After reboot, updater GUI no longer appears

**Comment by emkll** [comment]
## Install-and-restore on Mac Minis (in progress)
### Environment

- Install target: Mac Mini
- Server OS: Ubuntu 20.04
- Tails version: 4.17
- Test Scenario: Clean install (and restore)
- SSH over Tor: yes
- Onion service version: V3 only (v2+v3 backup)
- Release candidate: rc1 (with admin workstation on https://github.com/freedomofpress/securedrop/commit/372952c71aa7fd75de297185e9eb0bb135cd89f8 )
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1i1sW4lfiUC_lS5qmB-kyjjgyx0rOjf_vJao5hOGmS78/) checks pass

#### Command Line User Generation

- [ ] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] If doing upgrade testing, make a backup on 1.7.1 and restore this backup on this release candidate
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] Can successfully add journalist account with HOTP authentication DID NOT TEST

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [X] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [X] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in
- [x] Journalist account with HOTP can log in

##### Index base cases

- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page

- [x]  You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source Account" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [ ] The Updater GUI appears on boot
- [ ] Updating occurs without issue

### 1.8.1 release-specific changes (common)

- [x] Correct backup location of custom logo [#5880](https://github.com/freedomofpress/securedrop/issues/5880)
- [x] Exclude SSH tor config from server restores [#5833](https://github.com/freedomofpress/securedrop/issues/5833)

### 1.8.1 release-specific changes (Focal only)

- [x] No `fwupd` related OSSEC alert emails on hardware install on Focal [#5835](https://github.com/freedomofpress/securedrop/issues/5835). The following two lines contains the error message as examples.
  - `Mar  1 13:22:53 app fwupd[133921]: 13:22:53:0576 FuEngine             Failed to load SMBIOS: invalid DMI data size, got 2527 bytes, expected 2745`
  - `Mar  1 13:22:53 app fwupd[133921]: 13:22:53:0883 FuPluginUefi         Error opening directory â€œ/sys/firmware/efi/esrt/entriesâ€�: No such file or directory`

**Comment by zenmonkeykstop** [comment]
## 1.8.1 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report.

If you have submitted a QA report already for a 1.8.0 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 1.8.0-specific changes as well as changes since the previous release candidate.

There are OS-specific sections in the test plan - make sure you complete the appropriate section based on the server OS in your chosen test scenario.

### Environment

- Install target: Nuc10/Nuc8
- Server OS: Focal
- Tails version: 4.14
- Test Scenario: fresh
- SSH over Tor: yes
- Onion service version: v3
- Release candidate: rc2 (release/1.8.1 coz not tagged)
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup` **SOME EXPECTED FAILURES NOTHING THE GOD OF CYBERNETICS WOULDNT LET YOU INTO HEAVEN FOR**
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1i1sW4lfiUC_lS5qmB-kyjjgyx0rOjf_vJao5hOGmS78/) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] If doing upgrade testing, make a backup on 1.7.1 and restore this backup on this release candidate
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] Can successfully add journalist account with HOTP authentication **NOT TESTED**

### Application Acceptance Testing **SKIPPED BECAUSE RC2**

#### Source Interface

##### Landing page base cases
- [ ] JS warning bar does not appear when using Security Slider high
- [ ] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [ ] On generate page, refreshing codename produces a new 7-word codename
- [ ] On submit page, empty submissions produce flashed message
- [ ] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [ ] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in
- [ ] Journalist account with HOTP can log in

##### Index base cases

- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download" works

##### Individual source page

- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete Source Account" and the source and docs are deleted
- [ ] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot
- [x] Updating occurs without issue

### 1.8.1 release-specific changes (common)

- [x] Correct backup location of custom logo [#5880](https://github.com/freedomofpress/securedrop/issues/5880)
- [x] Exclude SSH tor config from server restores [#5833](https://github.com/freedomofpress/securedrop/issues/5833)

### 1.8.1 release-specific changes (Focal only)

- [x] No `fwupd` related OSSEC alert emails on hardware install on Focal [#5835](https://github.com/freedomofpress/securedrop/issues/5835). The following two lines contains the error message as examples.
  - `Mar  1 13:22:53 app fwupd[133921]: 13:22:53:0576 FuEngine             Failed to load SMBIOS: invalid DMI data size, got 2527 bytes, expected 2745`
  - `Mar  1 13:22:53 app fwupd[133921]: 13:22:53:0883 FuPluginUefi         Error opening directory â€œ/sys/firmware/efi/esrt/entriesâ€�: No such file or directory`
  


### Preflight testing

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 1.8.0
- [ ] A message can be successfully submitted

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 1.8.0
- [ ] After reboot, updater GUI no longer appears
