### ISSUE TITLE
Release SecureDrop 1.8.2

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5929]
This is a tracking issue for the release of SecureDrop 1.8.2. This minor release will include a keyring update and several bugfixes. It will only be issued for Ubuntu 20.04 (Focal).

Tentatively scheduled as follows:

**Release date:** 2021-05-13

**Release manager:** @zenmonkeykstop 
**Deputy release manager:** @emkll 
**Communications manager:**: @eloquence / @emkll 

_SecureDrop maintainers and testers:_ As you QA 1.8.2, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the [1.8.2 milestone](https://github.com/freedomofpress/securedrop/milestone/73) for tracking (or ask a maintainer to do so).

Tails 4.18 is the current stable version - a new Tails version is in beta including changes to Tor configuration options and is available here for those who wish to test with it: https://tails.boum.org/news/test_4.19-beta1/

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://gist.github.com/rmol/eb605e28e290e90f45347f3a2f1ad43e).

# [QA Matrix for 1.8.2](https://docs.google.com/spreadsheets/d/1s8V0MZH6O3isjS_7p9wS8lzuO5YYaiNI2x7eHrNhYJE/edit#gid=373736950)
# [Test Plan for 1.8.2](https://github.com/freedomofpress/securedrop/wiki/1.8.2-Test-Plan)

# Prepare release candidate (1.8.2~rc1)
- [x] Cherry-pick changes for this release (new branch should be based on `release/1.8.1`)
- [x] Link to latest version of Tails, including release candidates, to test against during QA
- [x] Prepare 1.8.2~rc1 release changelog
- [x] Prepare 1.8.2~rc1 tag
- [x]  Build debs and put up `1.8.2~rc1` on test apt server: https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/104
- [x] Commit build logs to https://github.com/freedomofpress/build-logs

# Prepare release candidate (1.8.2~rc2)
- [x] Cherry-pick changes for this release 
- [x] Prepare 1.8.2~rc2 release changelog
- [x] Prepare 1.8.2~rc2 tag
- [x]  Build debs and put up `1.8.2~rc2` on test apt server: https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/105
- [x] Commit build logs to https://github.com/freedomofpress/build-logs

# Prepare release candidate (1.8.2~rc3)
- [x] Cherry-pick changes for this release 
- [x] Prepare 1.8.2~rc3 release changelog
- [x] Prepare 1.8.2~rc3 tag
- [x]  Build debs and put up `1.8.2~rc3` on test apt server: https://github.com/freedomofpress/securedrop-dev-packages-lfs/pull/106
- [x] Commit build logs to https://github.com/freedomofpress/build-logs

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image
- [x] Push signed tag https://github.com/freedomofpress/securedrop/releases/tag/1.8.2
- [x] Pre-Flight: Test updater logic in Tails (apt-qa tracks the `release` branch in the LFS repo)
- [x] Build final Debian packages for 1.8.2 (and preserve build logs)
- [x] Commit package build logs to https://github.com/freedomofpress/build-logs
- [x] Upload Debian packages to apt-qa server 
- [x] Pre-Flight: Test that install and upgrade from 1.8.1 to 1.8.2 works w/ prod repo debs (apt-qa.freedom.press polls the `release` branch in the LFS repo for the debs)
- [x] Flip apt QA server to prod status (merge to `main` in the LFS repo)
- [x] Merge Docs branch changes to ``main`` and verify new docs build in securedrop-docs repo
- [x] Prepare release messaging

# Post release
- [x] Create GitHub release object https://github.com/freedomofpress/securedrop/releases/tag/1.8.2
- [x] Once release object is created, update versions in `securedrop-docs` and Wagtail
- [x] Build docs and verify new docs show up on https://docs.securedrop.org
- [x] Publish announcements
- [ ] Merge changelog back to `develop`
- [x] Update roadmap wiki page: https://github.com/freedomofpress/securedrop/wiki/Development-Roadmap

**Comment by eloquence** [comment]
Just a note that the Ubuntu 16.04 EOL broke many tests and we'll almost certainly have to power-merge changes for this release to bypass failing CI,  unless we want to backport the Xenial removal & dependency updates.

**Comment by zenmonkeykstop** [comment]
## 1.8.2 QA Checklist - NUC8(mon)+NUC10(app)

### Environment

- Install target: Nuc10+Nuc8
- Server OS: Focal
- Tails version: 4.19beta
- Test Scenario: upgrade
- SSH over Tor: yes
- Onion service version: v3...
- Release candidate: rc2
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while) **SOME EXPECTED FAILURES DUE TO QA**
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1s8V0MZH6O3isjS_7p9wS8lzuO5YYaiNI2x7eHrNhYJE/edit#gid=373736950) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] If doing upgrade testing, make a backup on 1.8.1 and restore this backup on this release candidate
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] Can successfully add journalist account with HOTP authentication **NOT TESTED**

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in
- [ ] Journalist account with HOTP can log in **NOT TESTED**

##### Index base cases

- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all submissions
- [x] Selecting all and clicking "Download" works

##### Individual source page

- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source Account" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot
- [x] Updating occurs without issue

### 1.8.2 release-specific changes
- [x] Use actual hostname in Postfix `generic` db [#5924](https://github.com/freedomofpress/securedrop/pull/5924)
  - [x] on `mon`, the `myhostname` variable in `/etc/postfix/main.cf` is set to
    the server hostname
  - [x] on `mon`, `/etc/postfix/generic` contains a line matching the address `ossec@mon`
    (or `ossec@<non-standard hostname>`) with the SMTP address used to deliver OSSEC
    messages
  - [x] OSSEC mail alerts are being sent successfully.
- [x] Backup file not copied locally during restore [#5919](https://github.com/freedomofpress/securedrop/pull/5919)
  - On the Admin Workstation, create a large backup file using an existing backup file (`sd-backup.tar.gz` using the following commands:
    ```
    cd ~/Persistent/securedrop/install_files/ansible-base
    dd if=/dev/urandom of=bigfile.rnd bs=1M count=1500  # this will take some time
    gzip -d sd-backup.tar.gz
    tar rvf sd-backup.tar bigfile.rnd
    gzip sd-backup.tar
    ```
    then, use `sd-backup.tar.gz` to perform a restore, while monitoring diskspace usage in another terminal with `watch -n 1 df -h`
    - [x] diskspace usage does not increase significantly during the `Extract Tor configuration from backup` task.
- [x] Add new pubkey for future securedrop release key rotation [#5930](https://github.com/freedomofpress/securedrop/pull/5930)
  - [x] After install/upgrade, the command `ssh app sudo apt-key list` lists entries for both the existing release key with fingerprint `22245C81E3BAEB4138B36061310F561200F4AD77` and the replacement key with fingerprint `2359E6538C0613E652955E6C188EDD3B7B22E6A3`
  - [x] The command `ssh app sudo apt-get update` completes without error
  - [x] the GUI updater completes without error, and the command `gpg --list-keys` list both keys with fingerprints as above

### Preflight testing

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 1.8.2
- [ ] A message can be successfully submitted

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 1.8.2
- [ ] After reboot, updater GUI no longer appears

**Comment by zenmonkeykstop** [comment]
## 1.8.2 QA Checklist

For both upgrades and fresh installs, here is a list of functionality that requires testing. You can use this for copy/pasting into your QA report.

If you have submitted a QA report already for a 1.8.2 release candidate with successful basic server testing and application acceptance testing sections, then you can skip these sections in subsequent reports, unless otherwise indicated by the Release Manager. This is to ensure that you focus your QA effort on the 1.8.2-specific changes as well as changes since the previous release candidate.

### Environment

- Install target: Nuc8/Nuc10
- Server OS: focal
- Tails version: Tails 4.19rc1
- Test Scenario: upgrade
- SSH over Tor: yes
- Onion service version: v3
- Release candidate: rc3
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1s8V0MZH6O3isjS_7p9wS8lzuO5YYaiNI2x7eHrNhYJE/edit#gid=373736950) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [ ] If doing upgrade testing, make a backup on 1.8.1 and restore this backup on this release candidate **skipped**
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] Can successfully add journalist account with HOTP authentication **skipped**

### Application Acceptance Testing **skipped**

#### Source Interface

##### Landing page base cases
- [ ] JS warning bar does not appear when using Security Slider high
- [ ] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [ ] On generate page, refreshing codename produces a new 7-word codename
- [ ] On submit page, empty submissions produce flashed message
- [ ] On submit page, short message submitted successfully
- [ ] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [ ] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [ ] Nonexistent codename cannot log in
- [ ] Empty codename cannot log in
- [ ] Legitimate codename can log in
- [ ] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [ ] Can log in with 2FA tokens
- [ ] incorrect password cannot log in
- [ ] invalid 2fa token cannot log in
- [ ] 2fa immediate reuse cannot log in
- [ ] Journalist account with HOTP can log in

##### Index base cases

- [ ] Filter by codename works
- [ ] Starring and unstarring works
- [ ] Click select all selects all submissions
- [ ] Selecting all and clicking "Download" works

##### Individual source page

- [ ] You can submit a reply and a flashed message and new row appears
- [ ] You cannot submit an empty reply
- [ ] Clicking "Delete Source Account" and the source and docs are deleted
- [ ] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot
- [x] Updating occurs without issue

### 1.8.2 release-specific changes
- [x] Use actual hostname in Postfix `generic` db [#5924](https://github.com/freedomofpress/securedrop/pull/5924)
  - [x] on `mon`, the `myhostname` variable in `/etc/postfix/main.cf` is set to
    the server hostname
  - [x] on `mon`, the `smtp_generic_maps` variable in `/etc/postfix/main.cf` is set to `hash:/etc/postfix/generic`
  - [x] on `mon`, `/etc/postfix/generic` exists and contains a line matching the address `ossec@mon`
    (or `ossec@<non-standard hostname>`) with the SMTP address used to deliver OSSEC
    messages
  - [x] OSSEC mail alerts are being sent successfully.
- [x] Backup file not copied locally during restore [#5919](https://github.com/freedomofpress/securedrop/pull/5919)
  - On the Admin Workstation, create a large backup file using an existing backup file (`sd-backup.tar.gz` using the following commands:
    ```
    cd ~/Persistent/securedrop/install_files/ansible-base
    dd if=/dev/urandom of=bigfile.rnd bs=1M count=1500  # this will take some time
    gzip -d sd-backup.tar.gz
    tar rvf sd-backup.tar bigfile.rnd
    gzip sd-backup.tar
    ```
    then, use `sd-backup.tar.gz` to perform a restore, while monitoring diskspace usage in another terminal with `watch -n 1 df -h`
    - [x] diskspace usage does not increase significantly during the `Extract Tor configuration from backup` task.
- [x] Add new pubkey for future securedrop release key rotation [#5930](https://github.com/freedomofpress/securedrop/pull/5930)
  - [x] After install/upgrade, the command `ssh app sudo apt-key list` lists entries for both the existing release key with fingerprint `22245C81E3BAEB4138B36061310F561200F4AD77` and the replacement key with fingerprint `2359E6538C0613E652955E6C188EDD3B7B22E6A3`
  - [x] The command `ssh app sudo apt-get update` completes without error
  - [x] the GUI updater completes without error, and the command `gpg --list-keys` list both keys with fingerprints as above
- [x] POST method is used for JI /ossec-test-alert method [#5947](https://github.com/freedomofpress/securedrop/pull/5947)
  - Log in to the JI as an admin and navigate to **Admin > Instance config**, then click **SEND TEST OSSEC ALERT**
    - [x] Verify that the flash message indicates a test OSSEC alert was sent
  - Log in to the JI as an admin and visit the URL `http://<JI address>/admin/ossec-test`
    - [x] Verify that a 405 error page is displayed
  - Create a file with the content below, subbing in the JI address, and open it in the same browser session as your logged-in JI session, then click **SUBMIT**:
    ```
    <html>
    <body>
      <script>history.pushState('', '', '/')</script>
        <form method="post" action="http://<JI address>/admin/ossec-test">
          <input type="submit" value="Submit request" />
        </form>
      </body>
    </html>
    ```
    - [x] Verify that you are logged out from the JI
    - [x] Verify that an error is logged in the JI error log containing the text `The CSRF token is invalid.`

### Preflight testing

#### Basic testing

- [ ] Install or upgrade occurs without error
- [ ] Source interface is available and version string indicates it is 1.8.2
- [ ] A message can be successfully submitted

#### Tails

- [ ] The updater GUI appears on boot
- [ ] The update successfully occurs to 1.8.2
- [ ] After reboot, updater GUI no longer appears

**Comment by emkll** [comment]
## 1.8.2-rc3 upgrade from 1.8.1 in VMs In progress
### Environment

- Install target: Vagrant Prod VMs
- Server OS: 20.04
- Tails version: 4.18
- Test Scenario: Upgrade
- SSH over Tor: Yes
- Onion service version: V3-only
- Release candidate: rc3
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1s8V0MZH6O3isjS_7p9wS8lzuO5YYaiNI2x7eHrNhYJE/edit#gid=373736950) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] If doing upgrade testing, make a backup on 1.8.1 and restore this backup on this release candidate
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [ ] Can successfully add journalist account with HOTP authentication DID NOT TEST

### Application Acceptance Testing (SKIPPED)

### Basic Tails Testing SKIPPED
### 1.8.2 release-specific changes
- [x] Use actual hostname in Postfix `generic` db [#5924](https://github.com/freedomofpress/securedrop/pull/5924)
  - [x] on `mon`, the `myhostname` variable in `/etc/postfix/main.cf` is set to
    the server hostname
  - [x] on `mon`, the `smtp_generic_maps` variable in `/etc/postfix/main.cf` is set to `hash:/etc/postfix/generic`
  - [x] on `mon`, `/etc/postfix/generic` exists and contains a line matching the address `ossec@mon`
    (or `ossec@<non-standard hostname>`) with the SMTP address used to deliver OSSEC
    messages
  - [x] OSSEC mail alerts are being sent successfully.
- [x] Backup file not copied locally during restore [#5919](https://github.com/freedomofpress/securedrop/pull/5919)
  - On the Admin Workstation, create a large backup file using an existing backup file (`sd-backup.tar.gz` using the following commands:
    ```
    cd ~/Persistent/securedrop/install_files/ansible-base
    dd if=/dev/urandom of=bigfile.rnd bs=1M count=1500  # this will take some time
    gzip -d sd-backup.tar.gz
    tar rvf sd-backup.tar bigfile.rnd
    gzip sd-backup.tar
    ```
    then, use `sd-backup.tar.gz` to perform a restore, while monitoring diskspace usage in another terminal with `watch -n 1 df -h`
    - [ ] diskspace usage does not increase significantly during the `Extract Tor configuration from backup` task.
- [ ] Add new pubkey for future securedrop release key rotation [#5930](https://github.com/freedomofpress/securedrop/pull/5930)
  - After install/upgrade, the command `ssh app sudo apt-key list` lists entries for both the existing release key with fingerprint `22245C81E3BAEB4138B36061310F561200F4AD77` and the replacement key with fingerprint `2359E6538C0613E652955E6C188EDD3B7B22E6A3`
  - The command `ssh app sudo apt-get update` completes without error
  - the GUI updater completes without error, and the command `gpg --list-keys` list both keys with fingerprints as above
- [x] POST method is used for JI /ossec-test-alert method [#5947](https://github.com/freedomofpress/securedrop/pull/5947)
  - Log in to the JI as an admin and navigate to **Admin > Instance config**, then click **SEND TEST OSSEC ALERT**
    - [x] Verify that the flash message indicates a test OSSEC alert was sent
  - Log in to the JI as an admin and visit the URL `http://<JI address>/ossec-test`
    - [x] Verify that a 405 error page is displayed
  - Create a file with the content below, subbing in the JI address, and open it in the same browser session as your logged-in JI session, then click **SUBMIT**:
    ```
    <html>
    <body>
      <script>history.pushState('', '', '/')</script>
        <form method="post" action="http://<JI address>/admin/ossec-test">
          <input type="submit" value="Submit request" />
        </form>
      </body>
    </html>
    ```
    - [x] Verify that you are logged out from the JI
    - [x] Verify that and error is logged in the JI error log containing the text `The CSRF token is invalid.`

**Comment by rmol** [comment]
### Environment

- Install target: NUC7i5BNH
- Server OS: Ubuntu 20.04
- Tails version: 4.18
- Test Scenario: clean install, Postfix `From:` header matches auth
- SSH over Tor: yes
- Onion service version: 3
- Release candidate: rc3
- General notes:

### Basic Server Testing

- [x] I can access both the source and journalist interfaces
- [x] I can SSH into both machines over Tor
- [x] AppArmor is loaded on app
    - [x] 0 processes are running unconfined
- [x] AppArmor is loaded on mon
    - [x] 0 processes are running unconfined
- [x] Both servers are running grsec kernels
- [x] iptables rules loaded
- [x] OSSEC emails begin to flow after install
- [x] OSSEC emails are decrypted to correct key and I am able to decrypt them
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1s8V0MZH6O3isjS_7p9wS8lzuO5YYaiNI2x7eHrNhYJE/edit#gid=373736950) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [ ] If doing upgrade testing, make a backup on 1.8.1 and restore this backup on this release candidate
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [x] Can successfully add journalist account with HOTP authentication

### ~Application Acceptance Testing~ SKIPPED
### ~Basic Tails Testing~ SKIPPED

### 1.8.2 release-specific changes
- [x] Use actual hostname in Postfix `generic` db [#5924](https://github.com/freedomofpress/securedrop/pull/5924)
  - [x] on `mon`, the `myhostname` variable in `/etc/postfix/main.cf` is set to
    the server hostname
  - [x] on `mon`, the `smtp_generic_maps` variable in `/etc/postfix/main.cf` is set to `hash:/etc/postfix/generic`
  - [x] on `mon`, `/etc/postfix/generic` exists and contains a line matching the address `ossec@mon`
    (or `ossec@<non-standard hostname>`) with the SMTP address used to deliver OSSEC
    messages
  - [x] OSSEC mail alerts are being sent successfully.
- [x] Backup file not copied locally during restore [#5919](https://github.com/freedomofpress/securedrop/pull/5919)
  - On the Admin Workstation, create a large backup file using an existing backup file (`sd-backup.tar.gz` using the following commands:
    ```
    cd ~/Persistent/securedrop/install_files/ansible-base
    dd if=/dev/urandom of=bigfile.rnd bs=1M count=1500  # this will take some time
    gzip -d sd-backup.tar.gz
    tar rvf sd-backup.tar bigfile.rnd
    gzip sd-backup.tar
    ```
    then, use `sd-backup.tar.gz` to perform a restore, while monitoring diskspace usage in another terminal with `watch -n 1 df -h`
    - [x] diskspace usage does not increase significantly during the `Extract Tor configuration from backup` task.
- [x] Add new pubkey for future securedrop release key rotation [#5930](https://github.com/freedomofpress/securedrop/pull/5930)
  - After install/upgrade, the command `ssh app sudo apt-key list` lists entries for both the existing release key with fingerprint `22245C81E3BAEB4138B36061310F561200F4AD77` and the replacement key with fingerprint `2359E6538C0613E652955E6C188EDD3B7B22E6A3`
  - The command `ssh app sudo apt-get update` completes without error
  - the GUI updater completes without error, and the command `gpg --list-keys` list both keys with fingerprints as above
- [ ] POST method is used for JI /ossec-test-alert method [#5947](https://github.com/freedomofpress/securedrop/pull/5947)
  - Log in to the JI as an admin and navigate to **Admin > Instance config**, then click **SEND TEST OSSEC ALERT**
    - [x] Verify that the flash message indicates a test OSSEC alert was sent
  - Log in to the JI as an admin and visit the URL `http://<JI address>/admin/ossec-test`
    - [x] Verify that a 405 error page is displayed
  - Create a file with the content below, subbing in the JI address, and open it in the same browser session as your logged-in JI session, then click **SUBMIT**:
    ```
    <html>
    <body>
      <script>history.pushState('', '', '/')</script>
        <form method="post" action="http://<JI address>/admin/ossec-test">
          <input type="submit" value="Submit request" />
        </form>
      </body>
    </html>
    ```
    - [x] Verify that you are logged out from the JI
    - [x] Verify that and error is logged in the JI error log containing the text `The CSRF token is invalid.`
