### ISSUE TITLE
Release SecureDrop 2.0.1

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6034]
This is a tracking issue for the release of SecureDrop 2.0.1. This point release is purely for the purpose of creating a new release tag signed with the updated signing key. No application or server provisioning changes will be included, though recent admin and 
development dependencies will be backported. There are no string changes in this release, so localization/translation is not required.

Tentatively scheduled as follows:

**Pre-release announcement:** 2021-07-07
**Release date:** ~2021-07-08

**Release manager:** @zenmonkeykstop 
**Deputy release manager:** TBD
**Communications manager:**: @rocodes

_SecureDrop maintainers and testers:_ As you QA 2.0.1, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the [2.0.1 milestone](https://github.com/freedomofpress/securedrop/milestone/69) for tracking (or ask a maintainer to do so).

Test debian packages will be posted on https://apt-test.freedom.press signed with [the test key](https://gist.githubusercontent.com/conorsch/ec4008b111bc3142fca522693f3cce7e/raw/2968621e8ad92db4505a31fcc5776422d7d26729/apt-test%2520apt%2520pubkey). An Ansible playbook testing the upgrade path is [here](https://TK/).

# [QA Matrix for 2.0.1](https://docs.google.com/spreadsheets/d/1Vtx9sOgv7MwL0tmsSzbZjGYOxWDSeRfPs4mBfmlI--0/edit#gid=1698153040)
# [Test Plan for 2.0.1](https://github.com/freedomofpress/securedrop/wiki/2.0.1-Test-Plan)

# Prepare release candidate (2.0.1~rc1)
- [x] Link to latest version of Tails, including release candidates, to test against during QA
- [x] Prepare 2.0.1~rc1 release changelog
- [x] Branch off release/2.0.1 from release/2.0.0 
- [x] Prepare 2.0.1~rc1
- [x] Build debs, preserving build log, and put up `2.0.1~rc1` on test apt server
- [x] Commit build log.

After each test, please update the QA matrix and post details for Basic Server Testing, Application Acceptance Testing and release-specific testing below in comments to this ticket.

# Final release
- [x] Ensure builder in release branch is updated and/or update builder image
- [x] Push signed tag 
- [x] Pre-Flight: Test updater logic in Tails (apt-qa tracks the `release` branch in the LFS repo)
- [x] Build final Debian packages for 2.0.1 (and preserve build log)
- [x] Commit package build log to https://github.com/freedomofpress/build-logs
- [x] Upload Debian packages to apt-qa server
- [x] Pre-Flight: Test that install and upgrade from 2.0.0 to 2.0.1 works w/ prod repo debs (apt-qa.freedom.press polls the `release` branch in the LFS repo for the debs)
- [x] Flip apt QA server to prod status (merge to `main` in the LFS repo)
- [x] Merge Docs branch changes to ``main`` and verify new docs build in securedrop-docs repo
- [x] Prepare release messaging

# Post release
- [x] Create GitHub release object 
- [x] Once release object is created, update versions in `securedrop-docs` and Wagtail
- [x] Build readthedocs and verify new docs show up on https://docs.securedrop.org
- [x] Publish announcements
- [ ] Merge changelog back to `develop`
- [x] Update roadmap wiki page: https://github.com/freedomofpress/securedrop/wiki/Development-Roadmap

**Comment by rmol** [comment]
### Environment

- Install target: NUC7i5BNH
- Tails version: 4.19
- Test Scenario: upgrade
- SSH over Tor: yes
- Release candidate: rc1
- General notes:

### Basic Server Testing
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [x] [QA Matrix](https://docs.google.com/spreadsheets/d/1Vtx9sOgv7MwL0tmsSzbZjGYOxWDSeRfPs4mBfmlI--0/edit#gid=1698153040) checks pass

#### Command Line User Generation

- [x] Can successfully add admin user and login

#### Administration

- [x] I have backed up and successfully restored the app server following [the backup documentation](https://docs.securedrop.org/en/latest/backup_and_restore.html)
- [x] If doing upgrade testing, make a backup on 2.0.0 and restore this backup on this release candidate
- [x] "Send Test OSSEC Alert" button in the journalist triggers an OSSEC alert and an email is sent
- [x] Can successfully add journalist account with HOTP authentication

### Application Acceptance Testing

#### Source Interface

##### Landing page base cases
- [x] JS warning bar does not appear when using Security Slider high
- [x] JS warning bar does appear when using Security Slider Low

##### First submission base cases
- [x] On generate page, refreshing codename produces a new 7-word codename
- [x] On submit page, empty submissions produce flashed message
- [x] On submit page, short message submitted successfully
- [x] On submit page, file greater than 500 MB produces "The connection was reset" in Tor Browser _quickly_ before the entire file is uploaded
- [x] On submit page, file less than 500 MB submitted successfully

##### Returning source base cases

- [x] Nonexistent codename cannot log in
- [x] Empty codename cannot log in
- [x] Legitimate codename can log in
- [x] Returning user can view journalist replies - need to log into journalist interface to test

#### Journalist Interface

##### Login base cases
- [x] Can log in with 2FA tokens
- [x] incorrect password cannot log in
- [x] invalid 2fa token cannot log in
- [x] 2fa immediate reuse cannot log in
- [x] Journalist account with HOTP can log in

##### Index base cases

- [x] Filter by codename works
- [x] Starring and unstarring works
- [x] Click select all selects all sources
- [x] Selecting all and clicking "Download" works

##### Individual source page

- [x] You can submit a reply and a flashed message and new row appears
- [x] You cannot submit an empty reply
- [x] Clicking "Delete Source Account" and the source and docs are deleted
- [x] You can click on a document and successfully decrypt using application private key

### Basic Tails Testing

After updating to this release candidate and running `securedrop-admin tailsconfig`

- [x] The Updater GUI appears on boot
- [x] Updating to 2.0.0 fails with a signature validation error

### 2.0.1 release-specific changes

- [x] Cryptography and cffi dependencies have been updated [#6030](https://github.com/freedomofpress/securedrop/pull/6030)
  - if performing a fresh install, after running `./securedrop-admin setup`, activate the admin virtualenv with `source admin/.venv3/bin/activate` and check dependencies witth `pip list`
    - [x] `cryptography` is updated to version 3.4.7, cffi to 1.14.5
  - Deactivate the virtualenv with `deactivate` and proceed with the rest of the installation
    - [x] All `securedrop-admin` commands complete successfully
  - move the existing `tor_v3_keys.json` file out of the way and generate a fresh one with `./securedrop-admin generate_v3_keys`
    - [x] a new valid `tor_v3_keys.json` file is generated
  - restore the previous `tor_v3_keys.json` file (to restore access to the JI and ssh services)

- [x] Testinfra has been updated to pass all tests in production [#6032](https://github.com/freedomofpress/securedrop/pull/6032)
  - [x] During the basic testing phase, `./securedrop-admin --force verify` completed successfully

**Comment by rmol** [comment]
### Environment

- Install target: NUC7i5BNH
- Tails version: 4.19
- Test Scenario: clean install
- SSH over Tor: yes
- Release candidate: rc1
- General notes: skipped anything not release-specific, tested earlier

### Basic Server Testing
- [x] After installing the testinfra dependencies, all tests in `./securedrop-admin verify` are passing:
  - Install dependencies on Admin Workstation with `cd ~/Persistent/securedrop && ./securedrop-admin setup -t`
  - Run tests with `./securedrop-admin verify` (this will take a while)
  - Remove test dependencies: `rm -rf admin/.venv3/ && ./securedrop-admin setup`
- [ ] [QA Matrix](https://docs.google.com/spreadsheets/d/1Vtx9sOgv7MwL0tmsSzbZjGYOxWDSeRfPs4mBfmlI--0/edit#gid=1698153040) checks pass

### 2.0.1 release-specific changes

- [x] Cryptography and cffi dependencies have been updated [#6030](https://github.com/freedomofpress/securedrop/pull/6030)
  - if performing a fresh install, after running `./securedrop-admin setup`, activate the admin virtualenv with `source admin/.venv3/bin/activate` and check dependencies witth `pip list`
    - [x] `cryptography` is updated to version 3.4.7, cffi to 1.14.5
  - Deactivate the virtualenv with `deactivate` and proceed with the rest of the installation
    - [x] All `securedrop-admin` commands complete successfully
  - move the existing `tor_v3_keys.json` file out of the way and generate a fresh one with `./securedrop-admin generate_v3_keys`
    - [x] a new valid `tor_v3_keys.json` file is generated
  - restore the previous `tor_v3_keys.json` file (to restore access to the JI and ssh services)

- [x] Testinfra has been updated to pass all tests in production [#6032](https://github.com/freedomofpress/securedrop/pull/6032)
  - [x] During the basic testing phase, `./securedrop-admin --force verify` completed successfully

**Comment by eloquence** [comment]
Graphical updater run from 2.0.0->2.0.1 on Tails 4.19 completed without issues. `cryptography` and `cffi` updated to expected versions. Graphical updater output sans playbook portion: https://gist.github.com/eloquence/24f519df7e149f7a39969403a6810aed
