### ISSUE TITLE
adopt continuous localization

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6232]
## Description

0. [x] comms per freedomofpress/engineering#30
1. [x] #6916
    - [ ] freedomofpress/securedrop-dev-docs#86
3. [x] #6917
4. [x] comms per freedomofpress/engineering#30
5. [x] Test these in a feature branch in `securedrop-i18n-sandbox` against
   `weblate-sandbox.securedrop.org`, with `i18n_tool.py` removed
6. [x] PR review, including a mock release from `securedrop-i18n-sandbox` during which a Release and Localization Manager verify that the new tooling behaves as expected
7. [x] Keep Localization Lab posted re: merge date and v2.7 release deadline
    - [x] Draft announcement of `securedrop/securedrop`'s new continuous configuration
8. [x] Merge; replicate Weblate configuration to `freedomofpress/securedrop` and `weblate.securedrop.org`
    - [x] Look into notifications to translators and reviewers

## User Research Evidence

- freedomofpress/securedrop-client#239
- https://github.com/freedomofpress/securedrop-client/wiki/Internationalization

## User Stories

**See also:**  https://github.com/freedomofpress/securedrop-client/wiki/Internationalization#overview

As a volunteer translator...
- I want the [SecureDrop demo](https://demo.securedrop.org) to reflect the latest source and translated strings.  (https://github.com/freedomofpress/securedrop/wiki/Tech-Meeting-Notes-2021-01-14)
- I don't want to have to scramble to complete translations during the pre-release translation and QA period.

As a member of the Localization Lab team...
- I want translation priorities to be informed by language-use statistics from `freedomofpress/i18n_scan`.  (hat tip: @eaon)

As a SecureDrop contributor...
- I want the [project's instructions to keep source strings in sync](https://developers.securedrop.org/en/latest/i18n.html#update-strings-to-be-translated) to be meaningful.

As a SecureDrop maintainer...
- I want to be able to assess translation labor incrementally, as the source strings change.
- I want to be able to merge new translations incrementally.

**Comment by cfm** [comment]
Per the November 8 Server hangout, for v2.7.0 I will:
1. [x] update freedomofpress/securedrop-client#239; and
2. [x] bring a formal proposal for adopting an equivalent continuous-localization workflow here, including comparing features with the current `i18n_tool.py`.

**Comment by cfm** [comment]
Reopening to track the work outlined in freedomofpress/securedrop-engineering#30, from which tickets are incoming.

**Comment by cfm** [comment]
<https://github.com/freedomofpress/securedrop/issues/6232#issue-1108711426> is updated based on @nathandyer's and my meeting with Localization Lab today:

> 7. [ ] **Keep Localization Lab posted re: merge date and v2.7 release deadline**
>     - [ ] **Draft announcement of `securedrop/securedrop`'s new continuous configuration**
> 8. [ ] Merge; replicate Weblate configuration to `freedomofpress/securedrop` and `weblate.securedrop.org`
>     - [ ] **Look into notifications to translators and reviewers**

**Comment by cfm** [comment]
v2.7.0 went out into the world using this process, and freedomofpress/securedrop-dev-docs#86 documents it.
