### ISSUE TITLE
Update the release pubkey to version with expiry date of 2023-07-04

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6449]
The securedrop release key expiry needs to be bumped before 2022-07-04. The pubkey is used in the following areas:

- verifying apt repo Release signatures (via the usual Ubuntu and Debian apt tools in servers and the Qubes Debian sd-* VMs)
- verifying git tags for Tails code updates (via gpg and git in the CLI and GUI updaters)
- verifying RPM package signatures (via dnf on Qubes dom0 and sys-firewall VMs)
- verifying updates to the HTTPSEverywhere onion names channel (in Tor Browser)

Note that:
- no HTTPSEverywhere logic needs to change, as the PEM-format key used there doesn't include an expiry date (feel free to correct me!) 
- packages or Release files should not need to be re-signed, as the private key is not being rotated.
- external documentation updates should not be necessary as the key fingerprint doesn't change and documentation referencing the pubkey doesn't mention the expiry date.

Tasks to update the pubkey for the areas above are summarized below:
# TBD ASAP 
- [x] generate new pubkey with expiry date of July 4 2023
- [x] confirm that maintainers have verified new pubkey 
- [x] Update pubkey in Focal securedrop-keyring package: #6448 
- [x] update pubkey in securedrop-workstation repo
- [x] update pubkey in Buster/Bullseye securedrop-keyring package: https://github.com/freedomofpress/securedrop-debian-packaging/pull/323
- [x] Release new Buster/Bullseye securedrop-keyring package
- [x] build Workstation base template RPM with updated securedrop-keyring package
- [x] sanity-check new template RPM by installing manually
- [x] test RPM via yum-test and staging env
 
## Required before 2022-07-04: 
- [x] release new Focal securedrop-keyring package
- [x] release workstation base template RPM
- [x] update key on keys.openpgp.org
- [x] update key on securedrop.org
- [x] update key in WKD setup on freedom.press

**Comment by sssoleileraaa** [comment]
@zenmonkeykstop, I did the following checks:
- [x] verify expiration date of new key is 2023-07-04 (I can see an advantage to having this on a US holiday since we'll be more likely to plan ahead even more so to make sure there's coverage etc)
- [x] verify existing signature (I did this on a prod-signed tag) 
- [x] `echo hello > test.txt && gpg --armor --detach-sign test.txt && gpg --verify test.txt{.asc,}` looks good

**Comment by eloquence** [comment]
I've updated the redirect https://securedrop.org/securedrop-release-key.asc which was still pointing to the old version (we are tracking this in Icinga and it was alerting about the upcoming expiry); I've also started a draft PR for the RPM keyring update in the `securedrop-workstation` repo:
 https://github.com/freedomofpress/securedrop-workstation/pull/786

**Comment by zenmonkeykstop** [comment]
I could have sworn I updated that - is it a redirect or something to the actual file?

**Comment by eloquence** [comment]
This is a redirect that should always point to the canonical version. 

When you uploaded the file in Wagtail, it created a new version under a different URL: https://media.securedrop.org/media/documents/securedrop-release-key-2021-1.asc

**Comment by legoktm** [comment]
I assume everything is done now since the world didn't end on July 4th?

**Comment by eloquence** [comment]
Yep, this is done. :)
