### ISSUE TITLE
Complete release-specific testing for 2.5.0~rc3

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#6599]

**Comment by cfm** [comment]
### Environment

- Install target:  NUC11s
- Tails version:  5.2
- Test Scenario:  upgrade
- SSH over Tor:  yes
- Release candidate:  RC3
- General notes:

### 2.5.0 release-specific changes

- [x] [#6403 Unified Redis-backed sessions](https://github.com/freedomofpress/securedrop/pull/6403)

#### Upgrade-only
  - [x] Upgrade completed successfully from 2.4.2
  - [x] `revoked_tokens` table is no longer present in database

```sh-session
sdadmin@app:~$ sudo -u www-data sqlite3 /var/lib/securedrop/db.sqlite ".schema revoked_tokens"
sdadmin@app:~$ 
```

#### Login
  * Log in to the JI
  - [x] Confirm that  you are logged in as the expected user
  * Edit the `js` cookie signature in Tor Browser and try to continue browsing the JI
  - [x] Confirm that you are logged out
  - Login to the JI
  * note your session id (in an app-server ssh session, use `redis-cli` and `KEYS js_session:*` to check it)
  *  Log out, then log back in again
  - [x] check your session id again and confirm that you received a new random-looking
      session id, and that your previous session id is no longer present

#### Sessions of multiple users are separate
  * Login to the JI as user X in browser A
  * Login to the JI as user Y in browser B
  - [x] Confirm that you are logged in as the expected user in each session

#### Sessions are renewed in accordance with the new expiration/renewal policy
  * Login to the JI
  * in an app server ssh session use `redis-cli`, `KEYS *`, and `EXPIRE <key id> 10` to
  expire the session
  - [x] Try to continue browsing, and confirm that you are logged out automatically

      -  **With expected repetition in the case where** https://github.com/freedomofpress/securedrop/blob/c23140ca14d9c10a1d96809336f702f5303db517/securedrop/journalist_app/sessions.py#L194-L197

  - [x] Confirm that a "logged out due to inactivity" message is displayed on the login screen
  * Login to the JI
  * use `KEYS *` and `EXPIRE <key> 1799` to set the key expiry time to less than 30min
  - [x] check the key value with `GET <key>` and verify that the `renew-count` value is 5
  * continue browsing in the JI
  - [x] Check the key TTL with `TTL <key>` and verify that it has had an additional 2hrs added
  - [x] check the key value with `GET <key>` and verify that the `renew-count` value is 4
  * repeat the expiry/renewal process 4 more times, verifying that `renew-count` decreases each time
  - [x] once `renew-count` is 0, verify that the TTL is no longer renewed by browsing the JI

#### Logout works

  * Login to the JI as user X in browser A
  * Login to the JI as user Y in browser B
  * Logout from user X in browser A
  - [x] Confirm that user X is logged out
  - [x] Confirm that user Y is still logged in

#### Deleting a user destroy all sessions of the user

  * Login to the JI as admin X in browser A
  * Login to the JI as admin/user Y in browser B
  * From admin X in browser A, delete user Y
  - [x] Confirm that user Y in browser B is logged out

#### Changing a user password destroy all sessions of the user

  * Login to the JI as admin X in browser A
  * Login to the JI as admin/user Y in browser B
  * From admin X in browser A, change password of user Y
  - [x] Confirm that user Y in browser B is logged out

  * Login to the JI as admin X
  * Change admin X password
  - [x] Confirm that admin X is logged out on password change

#### API and securedrop-client
  **Note:** use SecureDrop Workstation, configured to connect to your QA instance
  * Login to securedrop-client
  - [x] Confirm that the login is succesful
  - [x] on the app server, confirm that a session id was created
  - [x] confirm that basic authenticated operations (syncing sources, downloading docs, replies) work in the client
  - [x] Log out in the client (keeping the client session open in offline mode
  - [ ] on the app server, confirm that the session id was destroyed
  - [ ] Confirm that basic authenticated operations are no longer available in the client
  
**On this [very loaded Server](https://wiki.freedom.press/wiki/User:Cory/SecureDrop_instance#Journalist_Interface), the logout request unfortunately never succeeds.**  But this is a Client-side not a Server-side problem.
  
---

- [x] [#6557, #6475 - locale changes](https://github.com/freedomofpress/securedrop/pull/6557)
  - [x] Run `./securedrop_admin sdconfig` on the Admin Workstation, and confirm that
  the list of available languages matches those in the file`securedrop/i18n.json`
  - [x] (install only) set up both Portugese locales during installation, and confirm that they are available in the locale widget in the SI and JI, listed including the locale country name.
  
Yes, after a manual `ssh app sudo systemctl restart apache2`.
  
---

- [x] [#6550 - double-escaped org names](https://github.com/freedomofpress/securedrop/pull/6550)
  * In the Admin Interface, update the organization name to a string including an ampersand
  - [x] verify that the ampersand is rendered correctly in the SI and JI
---

- [x] [#6543 - consistent terminology](https://github.com/freedomofpress/securedrop/pull/6543)
  - [x] there are no references to `documents` when using the SI, only `files`, `messages`, and `submissions`
---

- [x] [#6425 - removal of minification](https://github.com/freedomofpress/securedrop/pull/6425)
  - [x] in the SI index page source, there is no reference to `static/gen/source.js`, with the file included from `static/js/source.js` instead.
  - [x] on the JI all sources page, there is no reference to `static/gen/journalist.js`, with the file included from `static/js/journalist.js` instead.
  - [x] on the JI all sources page, with JS enabled, source filtering works correctly.

**Comment by nathandyer** [comment]
### Environment

Install target: NUC11s
Tails version: 5.2
Test Scenario: Clean Install
SSH over Tor: Not during install, but post-install
Release candidate: RC3
General notes:

### 2.5.0 release-specific changes

- [x] [#6403 Unified Redis-backed sessions](https://github.com/freedomofpress/securedrop/pull/6403)

  **Note:** session info is now stored server-side using Redis. Some useful `redis-cli` commands for testing include:
  * `KEYS <pattern>` - lists all keys matching a given pattern
  * `GET <key>` - returns the given key's value
  * `TTL <key>` - returns the time-to-live for a given key
  * `EXPIRE <key> <sec>` - sets a given key's expiry to the `<sec>` value in seconds

  `redis-cli` should be run in an app server terminal as the instance redis server is
  only available locally.

#### Login
  * Log in to the JI
  - [x] Confirm that  you are logged in as the expected user
  * Edit the `js` cookie signature in Tor Browser and try to continue browsing the JI
  - [x] Confirm that you are logged out
  - Login to the JI
  * note your session id (in an app-server ssh session, use `redis-cli` and `KEYS js_session:*` to check it)
  *  Log out, then log back in again
  - [x] check your session id again and confirm that you received a new random-looking
      session id, and that your previous session id is no longer present

#### Sessions of multiple users are separate
  * Login to the JI as user X in browser A
  * Login to the JI as user Y in browser B
  - [x] Confirm that you are logged in as the expected user in each session

#### Sessions are renewed in accordance with the new expiration/renewal policy
  * Login to the JI
  * in an app server ssh session use `redis-cli`, `KEYS *`, and `EXPIRE <key id> 10` to
  expire the session
  - [x] Try to continue browsing, and confirm that you are logged out automatically
  - [x] Confirm that a "logged out due to inactivity" message is displayed on the login screen
  * Login to the JI
  * use `KEYS *` and `EXPIRE <key> 1799` to set the key expiry time to less than 30min
  - [x] check the key value with `GET <key>` and verify that the `renew-count` value is 5
  * continue browsing in the JI
  - [x] Check the key TTL with `TTL <key>` and verify that it has had an additional 2hrs added
  - [x] check the key value with `GET <key>` and verify that the `renew-count` value is 4
  * repeat the expiry/renewal process 4 more times, verifying that `renew-count` decreases each time
  - [x] once `renew-count` is 0, verify that the TTL is no longer renewed by browsing the JI

#### Logout works

  * Login to the JI as user X in browser A
  * Login to the JI as user Y in browser B
  * Logout from user X in browser A
  - [x] Confirm that user X is logged out
  - [x] Confirm that user Y is still logged in

#### Deleting a user destroy all sessions of the user

  * Login to the JI as admin X in browser A
  * Login to the JI as admin/user Y in browser B
  * From admin X in browser A, delete user Y
  - [x] Confirm that user Y in browser B is logged out

#### Changing a user password destroy all sessions of the user

  * Login to the JI as admin X in browser A
  * Login to the JI as admin/user Y in browser B
  * From admin X in browser A, change password of user Y
  - [x] Confirm that user Y in browser B is logged out

  * Login to the JI as admin X
  * Change admin X password
  - [x] Confirm that admin X is logged out on password change

#### API and securedrop-client
  **Note:** use SecureDrop Workstation, configured to connect to your QA instance
  * Login to securedrop-client
  - [x] Confirm that the login is succesful
  - [x] on the app server, confirm that a session id was created
  - [x] confirm that basic authenticated operations (syncing sources, downloading docs, replies) work in the client
  - [x] Log out in the client (keeping the client session open in offline mode
  - [x] on the app server, confirm that the session id was destroyed
  - [x] Confirm that basic authenticated operations are no longer available in the client
---

- [x] [#6557, #6475 - locale changes](https://github.com/freedomofpress/securedrop/pull/6557)
  - [x] Run `./securedrop_admin sdconfig` on the Admin Workstation, and confirm that
  the list of available languages matches those in the file`securedrop/i18n.json`
  - [x] (install only) set up both Portugese locales during installation, and confirm that they are available in the locale widget in the SI and JI, listed including the locale country name.
---

- [x] [#6550 - double-escaped org names](https://github.com/freedomofpress/securedrop/pull/6550)
  * In the Admin Interface, update the organization name to a string including an ampersand
  - [x] verify that the ampersand is rendered correctly in the SI and JI
---

- [x] [#6543 - consistent terminology](https://github.com/freedomofpress/securedrop/pull/6543)
  - [x] there are no references to `documents` when using the SI, only `files`, `messages`, and `submissions`
---

- [x] [#6425 - removal of minification](https://github.com/freedomofpress/securedrop/pull/6425)
  - [x] in the SI index page source, there is no reference to `static/gen/source.js`, with the file included from `static/js/source.js` instead.
  - [x] on the JI all sources page, there is no reference to `static/gen/journalist.js`, with the file included from `static/js/journalist.js` instead.
  - [x] on the JI all sources page, with JS enabled, source filtering works correctly.
---

**Comment by zenmonkeykstop** [comment]
(VMs, install scenario, Tails 5.4)

### 2.5.0 release-specific changes

- [x] [#6403 Unified Redis-backed sessions](https://github.com/freedomofpress/securedrop/pull/6403)

  **Note:** session info is now stored server-side using Redis. Some useful `redis-cli` commands for testing include:
  * `KEYS <pattern>` - lists all keys matching a given pattern
  * `GET <key>` - returns the given key's value
  * `TTL <key>` - returns the time-to-live for a given key
  * `EXPIRE <key> <sec>` - sets a given key's expiry to the `<sec>` value in seconds

  `redis-cli` should be run in an app server terminal as the instance redis server is
  only available locally.

#### Upgrade-only
  - [ ] ~~Upgrade completed successfully from 2.4.2~~
  - [ ] ~~`revoked_tokens` table is no longer present in database~~

#### Login
  * Log in to the JI
  - [x] Confirm that  you are logged in as the expected user
  * Edit the `js` cookie signature in Tor Browser and try to continue browsing the JI
  - [x] Confirm that you are logged out
  - Login to the JI
  * note your session id (in an app-server ssh session, use `redis-cli` and `KEYS js_session:*` to check it)
  *  Log out, then log back in again
  - [x] check your session id again and confirm that you received a new random-looking
      session id, and that your previous session id is no longer present

#### Sessions of multiple users are separate
  * Login to the JI as user X in browser A
  * Login to the JI as user Y in browser B
  - [x] Confirm that you are logged in as the expected user in each session

#### Sessions are renewed in accordance with the new expiration/renewal policy
  * Login to the JI
  * in an app server ssh session use `redis-cli`, `KEYS *`, and `EXPIRE <key id> 10` to
  expire the session
  - [x] Try to continue browsing, and confirm that you are logged out automatically
  - [x] Confirm that a "logged out due to inactivity" message is displayed on the login screen
  * Login to the JI
  * use `KEYS *` and `EXPIRE <key> 1799` to set the key expiry time to less than 30min
  - [x] check the key value with `GET <key>` and verify that the `renew-count` value is 5
  * continue browsing in the JI
  - [x] Check the key TTL with `TTL <key>` and verify that it has had an additional 2hrs added
  - [x] check the key value with `GET <key>` and verify that the `renew-count` value is 4
  * repeat the expiry/renewal process 4 more times, verifying that `renew-count` decreases each time
  - [x] once `renew-count` is 0, verify that the TTL is no longer renewed by browsing the JI

#### Logout works

  * Login to the JI as user X in browser A
  * Login to the JI as user Y in browser B
  * Logout from user X in browser A
  - [x] Confirm that user X is logged out
  - [x] Confirm that user Y is still logged in

#### Deleting a user destroy all sessions of the user

  * Login to the JI as admin X in browser A
  * Login to the JI as admin/user Y in browser B
  * From admin X in browser A, delete user Y
  - [x] Confirm that user Y in browser B is logged out

#### Changing a user password destroy all sessions of the user

  * Login to the JI as admin X in browser A
  * Login to the JI as admin/user Y in browser B
  * From admin X in browser A, change password of user Y
  - [x] Confirm that user Y in browser B is logged out

  * Login to the JI as admin X
  * Change admin X password
  - [x] Confirm that admin X is logged out on password change

#### API and securedrop-client
  ~~SKIPPED as my sdw install is currently b0rked~~
---

- [x] [#6557, #6475 - locale changes](https://github.com/freedomofpress/securedrop/pull/6557)
  - [x] Run `./securedrop_admin sdconfig` on the Admin Workstation, and confirm that
  the list of available languages matches those in the file`securedrop/i18n.json`
  - [x] (install only) set up both Portugese locales during installation, and confirm that they are available in the locale widget in the SI and JI, listed including the locale country name.
---

- [x] [#6550 - double-escaped org names](https://github.com/freedomofpress/securedrop/pull/6550)
  * In the Admin Interface, update the organization name to a string including an ampersand
  - [ ] verify that the ampersand is rendered correctly in the SI and JI
---

- [x] [#6543 - consistent terminology](https://github.com/freedomofpress/securedrop/pull/6543)
  - [x] there are no references to `documents` when using the SI, only `files`, `messages`, and `submissions`
---

- [x] [#6425 - removal of minification](https://github.com/freedomofpress/securedrop/pull/6425)
  - [x] in the SI index page source, there is no reference to `static/gen/source.js`, with the file included from `static/js/source.js` instead.
  - [x] on the JI all sources page, there is no reference to `static/gen/journalist.js`, with the file included from `static/js/journalist.js` instead.
  - [x] on the JI all sources page, with JS enabled, source filtering works correctly.
---
