### ISSUE TITLE
unattended-upgrades does not automatically remove old kernel packages

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6762]
## Plan to fix

1. [x] Release securedrop-grsec metapackage that depends on current and previous kernel: #6789
2. [x] Set `Unattended-Upgrade::Remove-Unused-Dependencies "true"`; via securedrop-config package, ship in 2.6.0 release: https://github.com/freedomofpress/securedrop/pull/6791
3. [x] Build next (May hopefully) kernel with correct version format (https://github.com/freedomofpress/kernel-builder/pull/33), but keep a manual dependency on 5.15.89 so we still have an old kernel installed.
4. [x] Build next next (June) kernel using the new version format, drop the manual dependency on 5.15.89. unattended-upgrades will automatically keep 3 kernel packages around, so the May kernel should not be removed.

## Description

unattended-upgrades should, by default, automatically remove old kernel packages to prevent too many from accumulating and taking up disk space (especially on /boot). But it doesn't

## Steps to Reproduce

1. Have an instance that's been running for a while through multiple kernel versions.
3. Run `sudo apt autoremove`

## Expected Behavior

* There are no kernel packages pending autoremoval because unattended-upgrades already removed them

## Actual Behavior

* You see:
```
The following packages will be REMOVED:
  linux-image-5.15.26-grsec-securedrop linux-image-5.15.57-grsec-securedrop
```

## Comments

The regex used by unattended-upgrades is https://github.com/mvo5/unattended-upgrades/blob/2.3/unattended-upgrade#L716

The simplified version is `re.compile('(^linux-.*-[1-9][0-9]*\\.[0-9]+\\.[0-9]+-[0-9]+(-.+)?$)')`. The gotcha is that this regex matches against packages with a Debian version, not a plain upstream version. So we basically need linux-image-5.15.74<b>-1</b>-grsec-securedrop instead of our current linux-image-5.15.74-grsec-securedrop.

**Comment by legoktm** [comment]
Fixing the package name to include the Debian revision seems straightforward. I think we just need to throw in a "-1" in https://github.com/freedomofpress/kernel-builder/blob/main/scripts/mkdebian#L89

This wouldn't take care of existing kernel packages. We could advise admins to run `sudo apt autoremove -y` as a one-off? Or maybe don't bother if they haven't run out of disk space yet.

This should probably be a blocker for the March kernel update. We should also take the opportunity to verify that unattended-upgrades does keep the last 2 old kernels or however many we want.

**Comment by legoktm** [comment]
@eloquence shared the list of kernels installed on their long-running instance, which confirmed that this has always been an issue and not a recent regression. It's just that we didn't do kernel updates frequently enough for it to be an issue.

I haven't looked up how the size of `/boot` is determined by the installer. Mine is 1.5G while Erik's is 974M, so I think it's safe to expect other instances to have a non-consistent partition size. It seems possible that if we ship another kernel update, it could run out of space.

----

My current idea is that we have the securedrop-grsec metapackage conflict/replace a hardcoded list of known old kernel versions, so when the next update happens, it forces the removal of any old kernel packages automatically. And going forward we'd rely on unattended-upgrades to do the removal.

**Comment by legoktm** [comment]
May have overcomplicated things :/

If we set `Unattended-Upgrade::Remove-Unused-Dependencies "true";` then it'll just run the equivalent of `apt-get autoremove`, which ends up like:
```
Option --dry-run given, *not* performing real actions
Packages that will be upgraded: 
marking linux-image-5.15.26-grsec-securedrop for removal
marking linux-image-5.15.74-grsec-securedrop for removal
marking linux-image-5.15.57-grsec-securedrop for removal
```

We still want to do the versioning change so that it removes them as a kernel package instead of a generic unused package, but probably this route is the right way to go for now. BUT it requires a SecureDrop release since this config file is maintained in the `securedrop-config` package

**Comment by legoktm** [comment]
The new plan is that we will set `Unattended-Upgrade::Remove-Unused-Dependencies "true";` in the 2.6.0 SecureDrop server release. However, this will cause all old kernels to be removed immediately, and we want to keep at least one behind.

So my plan is:
1. Manually create a new `securedrop-grsec` meta-package that depends on 5.15.89 (current) and 5.15.81 (previous). Publish this to apt-prod
2. Set `Unattended-Upgrade::Remove-Unused-Dependencies "true";` via securedrop-config package, ship in 2.6.0 release.
3. Build next (May hopefully) kernel with correct version format (https://github.com/freedomofpress/kernel-builder/pull/33), but keep a manual dependency on 5.15.89 so we still have an old kernel installed.
4. Build next next (June) kernel using the new version format, drop the manual dependency on 5.15.89. unattended-upgrades will automatically keep 3 kernel packages around, so the May kernel should not be removed.

Testing steps 1-2 is straightforward, for 3 and 4 I'm thinking of creating dummy kernel packages (all the correct metadata, but they're empty) so we can verify the unattended-upgrades behavior.

**Comment by legoktm** [comment]
For step 1, it actually wasn't that terrible to manually build securedrop-grsec as I wanted. Here's the git diff in the kernel-builder repository (the commenting out of the various make commands was so I didn't have to wait 4 hours just to get the thing to build):
<details>

```diff
diff --git a/scripts/mkdebian b/scripts/mkdebian
index a76a9f2..37ba56a 100755
--- a/scripts/mkdebian
+++ b/scripts/mkdebian
@@ -149,7 +149,7 @@ packagetimestamp="$(date -R $packagetimestamp_opts)"
 
 # Generate a simple changelog template
 cat <<EOF > debian/changelog
-$sourcename ($packageversion) $distribution; urgency=low
+$sourcename (5.15.89-grsec-securedrop-2) $distribution; urgency=low
 
   * Custom built Linux kernel.
 
@@ -224,7 +224,7 @@ cat <<EOF >> debian/control
 Package: securedrop-grsec
 Section: admin
 Architecture: $debarch
-Depends: $packagename-$version, intel-microcode, paxctld
+Depends: linux-image-5.15.89-grsec-securedrop, linux-image-5.15.81-grsec-securedrop, intel-microcode, paxctld
 Description: Metapackage providing a grsecurity-patched Linux kernel for use
  with SecureDrop. Depends on the most recently built patched kernel maintained
  by FPF. Package also includes sysctl and PaX flags calls for GRUB.
@@ -263,15 +263,15 @@ srctree ?= .
 
 build-indep:
 build-arch:
-       \$(MAKE) KERNELRELEASE=${version} ARCH=${ARCH} \
-       KBUILD_BUILD_VERSION=${revision} -f \$(srctree)/Makefile
+       #\$(MAKE) KERNELRELEASE=${version} ARCH=${ARCH} \
+       #KBUILD_BUILD_VERSION=${revision} -f \$(srctree)/Makefile
 
 build: build-arch
 
 binary-indep:
 binary-arch: build-arch
-       \$(MAKE) KERNELRELEASE=${version} ARCH=${ARCH} \
-       KBUILD_BUILD_VERSION=${revision} -f \$(srctree)/Makefile intdeb-pkg
+       #\$(MAKE) KERNELRELEASE=${version} ARCH=${ARCH} \
+       #KBUILD_BUILD_VERSION=${revision} -f \$(srctree)/Makefile intdeb-pkg
        sed -i s/#DEB_VERSION_UPSTREAM#/${version}/ debian/$metapackage/DEBIAN/postinst
        chmod 775 debian/$metapackage/DEBIAN/postinst
        dpkg-gencontrol -p$metapackage -P"debian/$metapackage"
diff --git a/securedrop-grsec/DEBIAN/postinst b/securedrop-grsec/DEBIAN/postinst
index d7f31ba..0b8d654 100755
--- a/securedrop-grsec/DEBIAN/postinst
+++ b/securedrop-grsec/DEBIAN/postinst
@@ -17,7 +17,7 @@ set -x
 # the debian-policy package
 
 # Pin current version of custom kernel
-GRSEC_VERSION="#DEB_VERSION_UPSTREAM#"
+GRSEC_VERSION="5.15.89-grsec-securedrop"
 
 # Sets default grub boot parameter to the kernel version specified
 # by $GRSEC_VERSION.
```
</details>

And the resulting diffoscope, which shows no changes except for the extra dependency:
<details>

```diff
user@sd-kernel-builder:~/kernel-builder$ diffoscope securedrop-grsec_5.15.89-grsec-securedrop-1_amd64.deb build/securedrop-grsec_5.15.89-grsec-securedrop-2_amd64.deb 
--- securedrop-grsec_5.15.89-grsec-securedrop-1_amd64.deb
+++ build/securedrop-grsec_5.15.89-grsec-securedrop-2_amd64.deb
├── control.tar.xz
│ ├── control.tar
│ │ ├── file list
│ │ │ @@ -1,3 +1,3 @@
│ │ │  drwxr-xr-x   0 root         (0) root         (0)        0 2011-06-29 20:23:37.000000 ./
│ │ │ --rw-r--r--   0 root         (0) root         (0)      543 2011-06-29 20:23:37.000000 ./control
│ │ │ +-rw-r--r--   0 root         (0) root         (0)      581 2011-06-29 20:23:37.000000 ./control
│ │ │  -rwxr-xr-x   0 root         (0) root         (0)     2029 2011-06-29 20:23:37.000000 ./postinst
│ │ ├── ./control
│ │ │ @@ -1,13 +1,13 @@
│ │ │  Package: securedrop-grsec
│ │ │  Source: linux-upstream
│ │ │ -Version: 5.15.89-grsec-securedrop-1
│ │ │ +Version: 5.15.89-grsec-securedrop-2
│ │ │  Architecture: amd64
│ │ │  Maintainer: SecureDrop Team <securedrop@freedom.press>
│ │ │  Installed-Size: 15
│ │ │ -Depends: linux-image-5.15.89-grsec-securedrop, intel-microcode, paxctld
│ │ │ +Depends: linux-image-5.15.89-grsec-securedrop, linux-image-5.15.81-grsec-securedrop, intel-microcode, paxctld
│ │ │  Section: admin
│ │ │  Priority: optional
│ │ │  Homepage: https://securedrop.org/
│ │ │  Description: Metapackage providing a grsecurity-patched Linux kernel for use
│ │ │   with SecureDrop. Depends on the most recently built patched kernel maintained
│ │ │   by FPF. Package also includes sysctl and PaX flags calls for GRUB.
```
</details>

I'm going to use similar hacks to prep the empty kernel packages for testing steps 3-4.

**Comment by legoktm** [comment]
apt (and this was backported to focal) now protects the latest 2 kernels: https://askubuntu.com/questions/620266/how-does-apt-decide-how-many-old-kernels-to-keep - this makes things a lot simpler and from my testing today, the plan should work!!

Here are all the kernel packages I have installed:
```
ii  linux-image-5.15.100-1-grsec-securedrop 5.15.100-1-grsec-securedrop-1     amd64        Linux kernel, version 5.15.100-1-grsec-securedrop
ii  linux-image-5.15.26-grsec-securedrop    5.15.26-grsec-securedrop-1        amd64        Linux kernel, version 5.15.26-grsec-securedrop
ii  linux-image-5.15.42-1-grsec-securedrop  5.15.42-1-grsec-securedrop-1      amd64        Linux kernel, version 5.15.42-1-grsec-securedrop
ii  linux-image-5.15.43-1-grsec-securedrop  5.15.43-1-grsec-securedrop-1      amd64        Linux kernel, version 5.15.43-1-grsec-securedrop
ii  linux-image-5.15.44-1-grsec-securedrop  5.15.44-1-grsec-securedrop-1      amd64        Linux kernel, version 5.15.44-1-grsec-securedrop
ii  linux-image-5.15.45-1-grsec-securedrop  5.15.45-1-grsec-securedrop-1      amd64        Linux kernel, version 5.15.45-1-grsec-securedrop
ii  linux-image-5.15.46-1-grsec-securedrop  5.15.46-1-grsec-securedrop-1      amd64        Linux kernel, version 5.15.46-1-grsec-securedrop
ii  linux-image-5.15.57-grsec-securedrop    5.15.57-grsec-securedrop-1        amd64        Linux kernel, version 5.15.57-grsec-securedrop
ii  linux-image-5.15.74-grsec-securedrop    5.15.74-grsec-securedrop-1        amd64        Linux kernel, version 5.15.74-grsec-securedrop
ii  linux-image-5.15.81-grsec-securedrop    5.15.81-grsec-securedrop-1        amd64        Linux kernel, version 5.15.81-grsec-securedrop
ii  linux-image-5.15.89-grsec-securedrop    5.15.89-grsec-securedrop-1        amd64        Linux kernel, version 5.15.89-grsec-securedrop
```

The 42-46 and 100 kernel packages are fake, but using the new versioning scheme so they are recognized as "kernel packages" by u-u and apt. The patched securedrop-grsec depends on 81 and 89 explicitly, so those are safe and will be kept. Then it's smart enough to keep 100 automatically, since that's the most recent kernel.

Then I set `Unattended-Upgrade::Remove-Unused-Dependencies "true";` so all the old kernels that are unused will also get removed. 

Here's the u-u dry run output:
```
Removing unused kernel packages: linux-image-5.15.44-1-grsec-securedrop linux-image-5.15.45-1-grsec-securedrop linux-image-5.15.42-1-grsec-securedrop linux-image-5.15.43-1-grsec-securedrop linux-image-5.15.46-1-grsec-securedrop
marking linux-image-5.15.44-1-grsec-securedrop for removal
marking linux-image-5.15.45-1-grsec-securedrop for removal
marking linux-image-5.15.42-1-grsec-securedrop for removal
marking linux-image-5.15.43-1-grsec-securedrop for removal
marking linux-image-5.15.46-1-grsec-securedrop for removal
Packages that were successfully auto-removed: 
Packages that are kept back: 
Option --dry-run given, *not* performing real actions
Packages that will be upgraded: 
marking linux-image-5.15.74-grsec-securedrop for removal
marking linux-image-5.15.44-1-grsec-securedrop for removal
marking linux-image-5.15.45-1-grsec-securedrop for removal
marking linux-image-5.15.57-grsec-securedrop for removal
marking linux-image-5.15.42-1-grsec-securedrop for removal
marking linux-image-5.15.43-1-grsec-securedrop for removal
marking linux-image-5.15.46-1-grsec-securedrop for removal
marking linux-image-5.15.26-grsec-securedrop for removal
```

**Comment by legoktm** [comment]
This was resolved a while back.
