### ISSUE TITLE
Update the release pubkey to version with expiry date of 2024-07-08

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#6794]
(Cloned from freedomofpress/securedrop#6449)

The securedrop release key expiry needs to be bumped before 2023-07-04. The pubkey is used in the following areas:

- verifying apt repo Release signatures (via the usual Ubuntu and Debian apt tools in servers and the Qubes Debian sd-* VMs)
- verifying git tags for Tails code updates (via gpg and git in the CLI and GUI updaters)
- verifying RPM package signatures (via dnf on Qubes dom0 and sys-firewall VMs)
- verifying updates to the HTTPSEverywhere onion names channel (in Tor Browser)

Note that:
- no HTTPSEverywhere logic needs to change, as the PEM-format key used there doesn't include an expiry date 
- packages or Release files should not need to be re-signed, as the private key is not being rotated.
- external documentation updates should not be necessary as the key fingerprint doesn't change and documentation referencing the pubkey doesn't mention the expiry date.

Tasks to update the pubkey for the areas above are summarized below:
# To complete (ASAP / before 2023-07-04) 
- [x] freedomofpress/securedrop#6803
- [x] freedomofpress/securedrop#6804
- [x] freedomofpress/securedrop#6805
- [x]  Release Focal securedrop-keyring package (either as a scheduled or point release) 
- [x] freedomofpress/securedrop-builder#442
- [x] freedomofpress/securedrop-builder#443
- [x] freedomofpress/securedrop-workstation#885
- [x] freedomofpress/securedrop-workstation#887
- [x] freedomofpress/securedrop-workstation#888
- [x] https://github.com/freedomofpress/securedrop-workstation/issues/903 (replaces https://github.com/freedomofpress/securedrop-workstation/issues/886)
- [x] freedomofpress/securedrop#6813 
- [x] Update redirects in https://securedrop.org/admin/redirects/ to point to new release key
- [x] Contact SDW pilot participants, ask them to be sure to update.

**Comment by eloquence** [comment]
(I think @legoktm previously pointed out that it's a bit odd to put the expiry on July 4 (US holiday), so just noting that here again in case we want to use the oppty to shift to a different cycle.)

**Comment by legoktm** [comment]
Indeed, if we could have it expire on the 8th or 9th I think that would be better. In the rare case something does go wrong with this procedure, it's going to fail on the 4th or 5th, which is a day we already know for sure we have less availability with at least all US people off.

**Comment by zenmonkeykstop** [comment]
Amended title accordingly - 7th seems good enough.

**Comment by rocodes** [comment]
(Update - new expiry date 2024-07-08 per https://github.com/freedomofpress/securedrop/pull/6819)

**Comment by zenmonkeykstop** [comment]
Added in an explicit "release it on servers already" issue - this is covered currently by the 2.6.0 release issue but if schedules slip we may nee a point one instead.

**Comment by zenmonkeykstop** [comment]
Closing this - if anything breaks on July 5 we can deal with it separately

**Comment by eloquence** [comment]
Just a note for future reference that we've got a few redirects set up in https://securedrop.org/admin/redirects/ for historical release key URLs like https://securedrop.org/securedrop-release-key.asc. I've updated all of these today (our monitoring alerted us to them as well), and I've updated the issue template to make a note of this for the person who copies and pastes it for the next round.
