### ISSUE TITLE
Make SecureDrop compatible with Python 3

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#997]
SecureDrop is currently written in and for Python 2.7. However, Python 2 will be [officially EOL'ed on January 1, 2020](https://pythonclock.org/) and we must migrate to Python 3 well before then. This work will be undertaken in stages.

## Phase 1: Make SecureDrop compatible with Python 3
- [ ] Check SecureDrop's dependencies for Python 3 compatibility
- [ ] Support running the development environment and tests with Python 3
- [ ] Update developer documentation

**2019-04-15 edit by @eloquence: Re-scoped Garrett's original issue per the work currently being undertaken.**

**Comment by heartsucker** [comment]
Hey guys. I actually did most of this in relation an old PR that I never finished, but it wasn't that big of a change. There were just a couple of places where `str` and `bytes` had to be manually converted. Is this something that people still are interested in?

**Comment by redshiftzero** [comment]
We're still interested in this, see list of dependencies here and their Python 3 status here: https://github.com/freedomofpress/securedrop/issues/2554#issuecomment-356105553

**Comment by eloquence** [comment]
For the 3/6-3/20 sprint, we're aiming to support both versions of Python in `develop`, with Python 2.7 as the default, but tests and development environment runnable in Python 3.5. This will require additional environment-variable based branching logic.

This work will be done in the `pyyy3` branch, with @kushaldas at the helm, and the goal to merge into `develop` during this sprint (these changes will not be picked up for the 0.12.1 release). However, any and all dev work on this should be considered **blocked** until we have closed all 0.12.1 milestone issues: https://github.com/freedomofpress/securedrop/milestone/51

**Comment by redshiftzero** [comment]
#4327 made the SecureDrop web app code compatible with Python 3, closing
